#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TOEIC 1000 Vocab Part 2: Days 11 to 20 (~340 words)
"""

DAYS_11_TO_20 = {
    # DAY 11: 회의, 일정 및 의사결정 (34 words)
    11: ("회의/일정", "620도약", [
        ("agenda", "의제, 안건", "noun", "on the agenda / adopt the agenda", "schedule / program / list of topics",
         "The committee adopted the finalized agenda before starting the quarterly review.", "위원회는 분기별 검토를 시작하기 전에 확정된 회의 의제를 채택했습니다."),
        ("convene", "소집하다, 회합하다", "verb", "convene a meeting / formally convene", "assemble / gather / summon",
         "The board of directors will convene an extraordinary session next Tuesday morning.", "이사회는 다음 주 화요일 아침에 임시 총회를 소집할 예정입니다."),
        ("adjourn", "휴회하다, 잠시 중단하다", "verb", "adjourn the meeting / adjourn for lunch", "suspend / postpone / recess",
         "The chairperson decided to adjourn the contentious meeting until nine tomorrow.", "의장은 논란이 많은 회의를 내일 오전 9시까지 휴회하기로 결정했습니다."),
        ("consensus", "합의, 의견 일치", "noun", "reach a consensus / general consensus", "agreement / accord / unanimity",
         "After two hours of rigorous debate, participants reached a unanimous consensus.", "2시간의 치열한 토론 끝에 참석자들은 만장일치 합의에 도달했습니다."),
        ("preside", "주재하다, 사회를 보다", "verb", "preside over the meeting / preside at the hearing", "chair / lead / moderate",
         "The senior vice president will preside over the annual shareholder symposium.", "수석 부사장이 연례 주주 심포지엄의 회의를 주재할 예정입니다."),
        ("minutes", "회의록", "noun", "take the minutes / approve the minutes", "notes / records / transcript",
         "The executive assistant was instructed to take detailed minutes of the session.", "비서실 직원은 회의의 상세한 회의록을 작성하라는 지시를 받았습니다."),
        ("quorum", "의사 정족수", "noun", "form a quorum / lack of a quorum", "minimum attendance / majority",
         "Because two directors were stranded in transit, the board failed to meet a quorum.", "두 명의 이사가 이동 중 발이 묶여 이사회는 의사 정족수를 채우지 못했습니다."),
        ("motion", "동의, 발의; 움직임", "noun", "table a motion / carry a motion", "proposal / proposition / resolution",
         "The treasurer made a formal motion to approve the capital investment roadmap.", "재무이사는 자본 투자 로드맵을 승인하자는 정식 동의를 발의했습니다."),
        ("unanimous", "만장일치의", "adj", "unanimous vote / unanimous decision", "undisputed / agreed by all / solid",
         "The revised emission standards passed following a decisive unanimous vote.", "개정된 탄소 배출 기준안은 결정적인 만장일치 투표를 거쳐 통과되었습니다."),
        ("postpone", "연기하다, 미루다", "verb", "postpone the presentation / postpone indefinitely", "delay / defer / put off",
         "Bad winter blizzards forced the organizer to postpone the product rollout by a week.", "혹독한 겨울 눈보라로 인해 주최 측은 제품 출시 행사를 일주일 연기해야 했습니다."),
        ("reschedule", "일정을 변경하다", "verb", "reschedule an appointment / reschedule for Friday", "change date / move / readjust",
         "Please phone our reception desk if you need to reschedule your dental examination.", "치과 검진 일정을 변경하셔야 할 경우 안내 데스크로 전화해 주시기 바랍니다."),
        ("schedule", "일정, 예정; 일정을 잡다", "noun", "ahead of schedule / tight schedule", "timetable / calendar / itinerary",
         "Thanks to overtime weekend shifts, the bridge renovation is two weeks ahead of schedule.", "주말 연장 근무 덕분에 교량 보수 공사는 예정된 일정보다 2주 앞서 진행되고 있습니다."),
        ("itinerary", "여행 일정표, 여정", "noun", "detailed itinerary / travel itinerary", "schedule / route / program",
         "Travelers were provided with an official itinerary detailing hotel addresses and flights.", "여행객들에게 호텔 주소와 항공편이 상세히 기재된 공식 일정표가 제공되었습니다."),
        ("facilitator", "진행자, 조력자", "noun", "meeting facilitator / workshop facilitator", "moderator / coordinator / mediator",
         "An external facilitator guided the interactive team-building brainstorming drill.", "외부 전문 진행자가 팀 빌딩 브레인스토밍 훈련을 원활히 이끌었습니다."),
        ("moderator", "사회자, 중재자", "noun", "panel moderator / forum moderator", "chairperson / mediator / arbitrator",
         "The seasoned journalist served as the moderator for the ninety-minute mayoral debate.", "노련한 언론인이 90분간 이어진 시장 후보 토론회의 사회자를 맡았습니다."),
        ("brainstorm", "자유롭게 아이디어를 내다, 브레인스토밍하다", "verb", "brainstorm solutions / brainstorm new campaigns", "generate ideas / devise",
         "Marketing specialists gathered to brainstorm catchy slogans for the eco-friendly detergent.", "마케팅 전문가들이 모여 친환경 세제의 눈길을 끄는 슬로건을 브레인스토밍했습니다."),
        ("actionable", "실행 가능한", "adj", "actionable insights / actionable steps", "practical / workable / feasible",
         "The consultant summarized the client review into five immediate actionable steps.", "컨설턴트는 고객사 리뷰를 즉각 실행 가능한 5가지 단계로 요약 정리했습니다."),
        ("recap", "요약하다, 개괄하다; 개요", "verb", "recap the discussion / quick recap", "summarize / review / outline",
         "Before concluding the call, the project lead gave a five-minute recap of decisions.", "통화를 마치기 전, 프로젝트 총괄 책임자는 결정 사항에 대해 5분간의 요약을 제공했습니다."),
        ("wrap up", "마무리 짓다, 완료하다", "phrase", "wrap up the session / wrap up talks", "conclude / finish / finalize",
         "We hope to wrap up negotiations by Friday afternoon so contracts can be printed.", "계약서를 인쇄할 수 있도록 금요일 오후까지 협상을 마무리 짓기를 희망합니다."),
        ("table", "상정하다; (미국) 연기하다, 보류하다", "verb", "table the discussion / table a bill", "postpone / defer / shelve",
         "Members agreed to table the bonus discussion until second-quarter numbers arrive.", "위원들은 2분기 실적 수치가 나올 때까지 보너스 관련 논의를 보류하기로 합의했습니다."),
        ("ballot", "투표용지, 비밀 투표; 투표하다", "noun", "secret ballot / cast a ballot", "vote / referendum / poll",
         "Union delegates cast their paper ballots regarding the proposed five percent wage hike.", "노조 대의원들은 제안된 5% 임금 인상안에 대해 서면 투표용지를 행사했습니다."),
        ("proxy", "위임장, 대리인", "noun", "vote by proxy / proxy statement", "deputy / representative / surrogate",
         "Shareholders unable to attend the annual meeting in person may submit votes by proxy.", "연례 주총에 직접 참석할 수 없는 주주들은 위임장을 통해 의결권을 행사할 수 있습니다."),
        ("collaborative", "협력적인, 공동의", "adj", "collaborative effort / collaborative environment", "cooperative / collective / joint",
         "The successful satellite launch was the culmination of a decade of collaborative effort.", "성공적인 인공위성 발사는 10년에 걸친 공동 협력 노력의 결실이었습니다."),
        ("briefing", "브리핑, 요약 보고", "noun", "press briefing / daily security briefing", "update / report / summary",
         "Reporters assembled in the auditorium for a forty-minute press briefing on the merger.", "기자들은 합병에 관한 40분간의 기자 브리핑을 듣기 위해 대강당에 집결했습니다."),
        ("memo", "메모, 사내 공문", "noun", "internal memo / circulate a memo", "memorandum / circular / notice",
         "A companywide memo was circulated warning staff of upcoming power maintenance.", "예정된 사내 전력 점검을 직원들에게 알리는 전사 공문 메모가 회람되었습니다."),
        ("tentative", "잠정적인, 확정되지 않은", "adj", "tentative schedule / tentative agreement", "provisional / preliminary / temporary",
         "We agreed on a tentative launch date of October 15, subject to regulatory approval.", "규제 당국의 승인을 조건으로 10월 15일을 잠정적인 출시일로 합의했습니다."),
        ("firm", "확고한, 변동 없는; 회사", "adj", "firm commitment / firm deadline", "solid / unyielding / settled",
         "The client insisted on a firm completion deadline with financial penalty penalties.", "고객사는 지체 보상금 조항이 포함된 확고한 완공 기한을 요구했습니다."),
        ("reschedule", "다시 일정을 잡다", "verb", "reschedule for next week", "rearrange / adjust timetable",
         "Because the flight was grounded, the keynote address had to be rescheduled for noon.", "비행기 결항으로 인해 기조연설 일정을 정오로 다시 잡아야 했습니다."),
        ("conflicting", "상충하는, 충돌하는", "adj", "conflicting schedules / conflicting priorities", "clashing / opposing / incompatible",
         "Due to conflicting appointment schedules, the marketing vice president sent a deputy.", "상충하는 약속 일정 때문에 마케팅 부사장은 대리인을 참석시켰습니다."),
        ("punctuality", "시간 엄수", "noun", "emphasize punctuality / strict punctuality", "promptness / timeliness",
         "Our corporate culture places tremendous premium on professionalism and punctuality.", "당사의 기업 문화는 전문성과 시간 엄수를 대단히 중요하게 평가합니다."),
        ("promptly", "즉시, 정각에", "adv", "arrive promptly at 9 / reply promptly", "punctually / immediately / swiftly",
         "The morning session will begin promptly at eight o'clock in the main ballroom.", "오전 세션은 메인 볼룸에서 오전 8시 정각에 시작될 예정입니다."),
        ("attendance", "참석, 출석", "noun", "confirm attendance / high attendance", "presence / turnout",
         "Please RSVP by Friday so we can confirm total dinner attendance with the caterers.", "출장 뷔페 업체에 총 참석 인원을 확정할 수 있도록 금요일까지 참석 여부를 회신해 주십시오."),
        ("RSVP", "회신 요망", "verb", "RSVP before the deadline / RSVP via email", "reply / respond / confirm",
         "Invitees are cordially requested to RSVP online by the tenth of next month.", "초청받으신 분들은 다음 달 10일까지 온라인으로 참석 여부를 회신해 주시기 바랍니다."),
        ("feedback", "의견, 피드백", "noun", "solicit feedback / valuable feedback", "input / critique / review",
         "The committee chairman asked attendees for honest feedback regarding the proposed bylaws.", "위원회 의장은 참석자들에게 제안된 내규 개정안에 대한 솔직한 피드백을 요청했습니다.")
    ]),

    # DAY 12: 컨퍼런스, 전시회 및 발표 (34 words)
    12: ("회의/일정", "800필수", [
        ("keynote", "기조연설; 기본 방침", "noun", "keynote speaker / keynote address", "main address / featured speech",
         "The tech visionary delivered an inspiring keynote address on generative artificial intelligence.", "그 기술 분야의 선구자는 생성형 인공지능에 관한 감동적인 기조연설을 전달했습니다."),
        ("symposium", "심포지엄, 학술 토론회", "noun", "annual symposium / host a symposium", "conference / seminar / convention",
         "Biochemists from thirty universities registered for the international cancer symposium.", "30개 대학의 생화학자들이 국제 암 학술 심포지엄에 등록했습니다."),
        ("venue", "행사장, 개최 장소", "noun", "conference venue / change the venue", "location / site / hall",
         "The newly opened waterfront convention center was chosen as the primary exhibition venue.", "새로 개장한 수변 컨벤션 센터가 주요 전시 개최 장소로 선정되었습니다."),
        ("auditorium", "강당, 대강당", "noun", "school auditorium / fill the auditorium", "hall / theater / amphitheater",
         "Over eight hundred attendees packed the municipal auditorium for the product demo.", "800명이 넘는 참가자들이 제품 시연을 보기 위해 시립 대강당을 가득 메웠습니다."),
        ("podium", "연단, 지휘대", "noun", "approach the podium / step up to the podium", "lectern / platform / stage",
         "Dr. Vance approached the podium to accept the lifetime technological achievement award.", "밴스 박사는 평생 기술 공로상을 수상하기 위해 연단으로 걸어 나갔습니다."),
        ("panelist", "패널 토론자", "noun", "expert panelist / invite panelists", "discussant / speaker / debater",
         "Four distinguished panelists debated the economic ramifications of regional free trade.", "4명의 저명한 패널 토론자들이 역내 자유무역의 경제적 파급 효과에 대해 열띤 토론을 벌였습니다."),
        ("attendee", "참석자, 출석자", "noun", "conference attendee / registered attendee", "participant / delegate / guest",
         "Every registered conference attendee will receive a commemorative tote bag and lanyard.", "모든 등록된 컨퍼런스 참석자는 기념 토트백과 명찰 목걸이를 받게 됩니다."),
        ("delegate", "대표자, 대의원", "noun", "foreign delegate / international delegates", "representative / envoy / commissioner",
         "Over five hundred trade delegates from thirty-two sovereign nations signed the accord.", "32개 주권 국가에서 모인 500명 이상의 무역 대표단이 협정에 서명했습니다."),
        ("exhibition", "전시회, 박람회", "noun", "art exhibition / trade exhibition", "expo / showcase / display",
         "The automotive technology exhibition showcases autonomous driving sensor arrays.", "자동차 기술 전시회는 첨단 자율주행 센서 어레이를 선보이고 있습니다."),
        ("exposition", "엑스포, 박람회, 설명", "noun", "industrial exposition / world exposition", "expo / fair / trade show",
         "Startups secured angel funding after demonstrating prototypes at the technology exposition.", "스타트업들은 기술 박람회에서 시제품을 시연한 후 엔젤 투자를 유치했습니다."),
        ("banquet", "연회, 만찬", "noun", "awards banquet / annual banquet", "feast / dinner / gala",
         "The corporation concluded its global sales rally with an elegant seven-course banquet.", "그 기업은 품격 있는 7코스 만찬 연회로 글로벌 영업 결의대회를 마무리했습니다."),
        ("catering", "출장 뷔페, 케이터링", "noun", "catering service / outside catering", "food service / hospitality / provision",
         "The event planner contracted an award-winning organic catering service for lunch.", "행사 기획자는 점심 식사를 위해 수상 경력이 있는 유기농 출장 뷔페 업체와 계약했습니다."),
        ("refreshment", "다과, 가벼운 음식물", "noun", "light refreshments / complimentary refreshments", "snacks / food and drink / beverages",
         "Complimentary coffee and light refreshments will be served during the twenty-minute intermission.", "20분간의 중간 휴식 시간 동안 무료 커피와 가벼운 다과가 제공될 예정입니다."),
        ("accommodate", "수용하다, 편의를 도모하다", "verb", "accommodate large groups / accommodate requests", "house / seat / hold / oblige",
         "The grand ballroom can comfortably accommodate up to six hundred banquet guests.", "그 대연회장은 최대 600명의 만찬 하객을 편안하게 수용할 수 있습니다."),
        ("session", "세션, 기간, 회기", "noun", "breakout session / morning session", "meeting / assembly / gathering",
         "Attendees may select two interactive breakout sessions during the afternoon schedule.", "참석자들은 오후 일정 중에 2개의 참여형 소그룹 세션을 선택할 수 있습니다."),
        ("intermission", "중간 휴식 시간", "noun", "fifteen-minute intermission / during the intermission", "break / interval / recess",
         "Patrons stretched their legs in the outdoor courtyard during the twenty-minute intermission.", "관객들은 20분간의 중간 휴식 시간 동안 야외 안뜰에서 다리를 풀었습니다."),
        ("handout", "유인물, 배포 자료", "noun", "distribute handouts / instructional handout", "pamphlet / worksheet / flyer",
         "Download the digital speaker handouts by scanning the QR code on the welcome brochure.", "환영 브로슈어의 QR 코드를 스캔하여 강연자의 디지털 배포 자료를 다운로드하십시오."),
        ("badge", "명찰, 배지, 휘장", "noun", "name badge / visitor badge", "pass / tag / ID",
         "Security personnel require everyone inside the exhibition hall to display their name badge.", "보안 요원은 전시장 내부의 모든 인원이 명찰을 패용할 것을 요구합니다."),
        ("registration", "등록, 접수", "noun", "early registration / registration fee", "enrollment / sign-up / booking",
         "Take advantage of early registration discounts by submitting paperwork before May 1.", "5월 1일 전에 신청 서류를 제출하셔서 조기 등록 할인 혜택을 누리십시오."),
        ("booth", "부스, 홍보 부스, 칸막이", "noun", "exhibition booth / information booth", "stand / stall / kiosk",
         "Representatives at our promotional booth distributed sample software trial drives.", "저희 홍보 부스의 담당자들은 소프트웨어 체험판 드라이브 샘플을 배포했습니다."),
        ("hallmark", "특징, 품질 보증 마크", "noun", "hallmark of excellence / distinct hallmark", "trademark / signature / characteristic",
         "Impeccable acoustic clarity is the celebrated hallmark of the newly constructed symphony hall.", "결점 없는 음향의 선명함은 새로 지어진 심포니 홀의 유명한 고유 특징입니다."),
        ("acoustics", "음향, 음향 시설", "noun", "excellent acoustics / concert hall acoustics", "sound quality / audio properties",
         "Architects consulted acoustic specialists to guarantee optimal audio clarity for speeches.", "건축가들은 연설의 최적 음향 선명도를 보장하기 위해 음향 전문가들의 자문을 구했습니다."),
        ("complimentary", "무료의, 칭찬하는", "adj", "complimentary admission / complimentary shuttle", "free of charge / gratuitous / gratis",
         "All registered delegates receive complimentary shuttle passes to the downtown hotels.", "등록된 모든 대표단은 시내 호텔로 향하는 무료 셔틀버스 탑승권을 받습니다."),
        ("interactivity", "상호작용, 소통성", "noun", "enhance interactivity / high interactivity", "engagement / participation",
         "The presenter utilized real-time digital polling to maximize audience interactivity.", "발표자는 청중과의 실시간 상호작용을 극대화하기 위해 디지털 실시간 투표를 활용했습니다."),
        ("demonstration", "시연, 증명, 설명", "noun", "product demonstration / hands-on demo", "presentation / display / exhibition",
         "Crowds gathered around the platform to watch a live demonstration of the surgical robot.", "수술용 로봇의 실시간 작동 시연을 보기 위해 연단 주변으로 군중이 몰려들었습니다."),
        ("showcase", "전시하다, 소개하다; 진열장", "verb", "showcase cutting-edge technology", "display / exhibit / unveil",
         "The tech expo offered international startups a prime platform to showcase mobile games.", "그 기술 엑스포는 글로벌 스타트업들에게 모바일 게임을 선보일 최적의 무대를 제공했습니다."),
        ("plenary", "총회의, 전원 출석의", "adj", "plenary session / plenary assembly", "full / complete / general",
         "All six hundred delegates must gather inside the main arena for the morning plenary session.", "600명의 전 대표단은 오전 전원 총회 세션을 위해 메인 아레나에 모여야 합니다."),
        ("symposium", "학술 토론회, 심포지엄", "noun", "annual research symposium", "colloquium / seminar / convention",
         "Scholars will deliver papers on renewable energy during the three-day energy symposium.", "학자들은 사흘간 진행되는 에너지 심포지엄 기간 동안 재생 가능 에너지에 관한 논문을 발표할 것입니다."),
        ("lectern", "독서대, 보면대, 강연대", "noun", "step up to the lectern / speak from the lectern", "podium / stand / desk",
         "The visiting foreign minister adjusted the microphone on the wooden lectern.", "방문한 외무부 장관은 목재 강연대에 부착된 마이크를 조절했습니다."),
        ("lanyard", "목걸이 줄, 랜야드", "noun", "wear a lanyard / pass on a lanyard", "cord / strap / neckband",
         "Keep your color-coded VIP pass secured to your lanyard throughout the convention.", "컨벤션 기간 내내 색상별로 구분된 VIP 출입증을 목걸이 줄에 항상 걸어 두십시오."),
        ("conclude", "결론짓다, 마무리하다", "verb", "conclude the remarks / formally conclude", "finish / end / wrap up",
         "The keynote speaker concluded her remarks by challenging engineers to innovate sustainably.", "기조연설자는 엔지니어들에게 지속 가능한 혁신을 촉구하며 강연을 마무리했습니다."),
        ("enthusiastic", "열렬한, 열광적인", "adj", "enthusiastic response / enthusiastic applause", "eager / keen / passionate",
         "The audience gave an enthusiastic standing ovation following the piano concerto.", "피아노 협주곡 연주가 끝난 후 관객들은 열렬한 기립 박수를 보냈습니다."),
        ("ovation", "열렬한 박수, 환호", "noun", "standing ovation / receive an ovation", "applause / cheers / acclaim",
         "The retiring founder received a spontaneous five-minute standing ovation from staff.", "은퇴하는 창업주는 전 직원들로부터 자발적인 5분간의 기립 박수를 받았습니다."),
        ("hospitality", "환대, 서비스업", "noun", "warm hospitality / hospitality industry", "welcome / friendliness / warmth",
         "We express our sincerest gratitude to the host city for its extraordinary hospitality.", "놀라운 환대를 베풀어 준 주최 도시에 진심으로 깊은 감사의 말씀을 전합니다.")
    ]),

    # DAY 13: 출장, 항공 및 대중교통 (34 words)
    13: ("출장/교통", "620도약", [
        ("itinerary", "여행 일정표", "noun", "flight itinerary / business trip itinerary", "schedule / travel plan / route",
         "The administrative assistant emailed the confirmed flight itinerary and lodging vouchers.", "비서 직원은 확정된 항공 일정표와 숙박 바우처를 이메일로 전송했습니다."),
        ("reservation", "예약", "noun", "make a reservation / confirmed reservation", "booking / appointment",
         "We strongly advise booking hotel reservations early because of the medical convention.", "의학 학술대회로 인해 호텔 예약을 일찍 진행하실 것을 강력히 권장합니다."),
        ("layover", "경유, 환승 대기 시간", "noun", "two-hour layover / long layover", "stopover / transit wait / connection",
         "Passengers on flight 402 face a three-hour international layover in Frankfurt.", "402편 승객들은 프랑크푸르트에서 3시간의 국제선 환승 대기 시간을 갖게 됩니다."),
        ("terminal", "터미널, 종점; 말기의", "noun", "international terminal / departure terminal", "station / depot / terminus",
         "Shuttle buses circulate every ten minutes between airport parking and Terminal 2.", "공항 주차장과 제2터미널 사이를 10분 간격으로 셔틀버스가 순환 운행합니다."),
        ("boarding", "탑승; 하숙", "noun", "boarding pass / priority boarding", "embarkation / entry",
         "First-class and loyalty club members are invited to proceed for priority boarding.", "일등석 및 우수 고객 클럽 회원은 우선 탑승을 위해 이동해 주시기 바랍니다."),
        ("departure", "출발, 출발편", "noun", "scheduled departure / departure gate", "leaving / takeoff / exit",
         "Severe fog forced the control tower to halt all domestic runway departures.", "짙은 안개로 인해 관제탑은 모든 국내선 활주로 이륙 출발을 일시 중단시켰습니다."),
        ("arrival", "도착, 도착편", "noun", "estimated time of arrival / arrival lounge", "coming / landing / entry",
         "Family members awaited travelers near the baggage carousel in the international arrival hall.", "가족들은 국제선 입국장 수하물 수취대 근처에서 여행객들을 기다렸습니다."),
        ("commute", "통근하다; 통근, 통근 거리", "verb", "commute by train / daily commute", "travel to work / journey",
         "Many suburban employees commute over forty minutes daily on the rapid commuter train.", "많은 교외 거주 직원들은 쾌속 통근 열차를 타고 매일 40분 이상 통근합니다."),
        ("transit", "수송, 환승, 통과", "noun", "public transit / in transit", "transportation / carriage / passage",
         "Subsidized public transit cards encourage staff to leave personal vehicles at home.", "보조금이 지급되는 대중교통 카드는 직원들이 자가용을 집에 두고 출퇴근하도록 장려합니다."),
        ("fare", "교통 요금, 운임", "noun", "bus fare / discounted fare", "ticket price / tariff / charge",
         "The municipal transit authority raised peak subway fares by twenty-five cents.", "시 교통국은 출퇴근 피크 시간대 지하철 요금을 25센트 인상했습니다."),
        ("detour", "우회로, 우회; 돌아가다", "noun", "take a detour / traffic detour", "bypass / diversion / roundabout route",
         "Highway resurfacing required morning drivers to take a scenic rural detour.", "고속도로 포장 공사로 인해 아침 운전자들은 경치 좋은 시골 우회로를 이용해야 했습니다."),
        ("delay", "지연, 연기; 지연시키다", "noun", "flight delay / unavoidable delay", "postponement / hold-up / setback",
         "Mechanical inspection of the left jet engine caused an unforeseen two-hour flight delay.", "왼쪽 제트 엔진에 대한 기계 점검으로 인해 예상치 못한 2시간의 항공편 지연이 발생했습니다."),
        ("cancellation", "취소", "noun", "flight cancellation / cancellation fee", "abandonment / annulment / repeal",
         "Travel insurance reimburses nonrefundable tour deposits in the event of illness cancellation.", "여행자 보험은 질병으로 인한 여행 취소 시 환불 불가 투어 보증금을 보상해 줍니다."),
        ("baggage", "수하물, 짐", "noun", "baggage claim / excess baggage", "luggage / suitcases / packs",
         "Airlines impose steep surcharges if checked baggage exceeds fifty pounds per passenger.", "체크인 수하물이 승객당 50파운드를 초과할 경우 항공사는 비싼 추가 요금을 부과합니다."),
        ("claim", "요구하다, 청구하다; 수취대, 권리", "verb", "claim luggage / claim reimbursement", "collect / demand / request",
         "Proceed downstairs to Carousel 4 to claim all oversized sports gear and skis.", "특대형 스포츠 장비와 스키를 수취하시려면 아래층 4번 수하물 수취대로 이동하십시오."),
        ("shuttle", "왕복 셔틀버스/열차; 왕복 운행하다", "noun", "airport shuttle / courtesy shuttle", "van / bus / transport",
         "The hotel provides a twenty-four-hour courtesy shuttle to all four airport gates.", "호텔은 4개의 공항 게이트 전체를 왕복하는 24시간 무료 셔틀 서비스를 제공합니다."),
        ("valet", "발레파킹, 주차 대행; 대행 주차하다", "noun", "valet parking / complimentary valet", "parking attendant / service",
         "Guests arriving in personal sedans may utilize the hotel's complimentary valet service.", "자가용 세단을 타고 도착하는 투숙객은 호텔의 무료 발레파킹 서비스를 이용하실 수 있습니다."),
        ("destination", "목적지, 행선지", "noun", "final destination / tourist destination", "journey's end / terminus",
         "Passengers whose final destination is Tokyo must clear border immigration upon arrival.", "최종 목적지가 도쿄인 승객들은 도착 즉시 출입국 심사를 받아야 합니다."),
        ("connection", "연결편, 환승", "noun", "tight connection / miss a connection", "connecting flight / transfer",
         "Because the first leg arrived late, several travelers missed their European connection.", "첫 번째 구간 항공편이 늦게 도착하는 바람에 여러 승객이 유럽행 환승 연결편을 놓쳤습니다."),
        ("reimburse", "변제하다, 환급하다", "verb", "reimburse mileage / reimburse expenses", "refund / repay / compensate",
         "Corporate travel guidelines state that the firm will reimburse standard taxi fares.", "사내 출장 규정은 회사가 표준 택시 요금을 환급해 줄 것이라고 명시하고 있습니다."),
        ("per diem", "하루당 일비, 출장 수당", "noun", "daily per diem / receive a per diem", "daily allowance / expense stipend",
         "Employees on domestic assignments receive a seventy-five-dollar daily food per diem.", "국내 출장 중인 직원들은 하루 75달러의 일일 식대 출장 수당(일비)을 지급받습니다."),
        ("mileage", "마일리지, 주행거리, 연비", "noun", "frequent flyer mileage / log mileage", "distance / air miles / travel points",
         "Executives accumulated enough airline mileage to redeem two round-trip companion tickets.", "임원진은 동반자 왕복 항공권 2매를 교환할 수 있을 만큼 충분한 항공사 마일리지를 적립했습니다."),
        ("congestion", "혼잡, 정체", "noun", "traffic congestion / port congestion", "jam / gridlock / overcrowding",
         "The municipal council introduced congestion pricing to ease rush-hour vehicular gridlock.", "시의회는 출퇴근 시간대 차량 정체를 완화하기 위해 혼잡 통행료를 도입했습니다."),
        ("commuter", "통근자", "noun", "suburban commuter / rail commuter", "traveler / daily passenger",
         "Thousands of daily rail commuters were inconvenienced by signal maintenance repairs.", "신호 설비 보수 공사로 인해 매일 통근 열차를 이용하는 수천 명의 승객이 불편을 겪었습니다."),
        ("convenience", "편의, 편리함", "noun", "for your convenience / modern conveniences", "ease / handiness / comfort",
         "For customer convenience, automated self-service boarding kiosks operate non-stop.", "고객의 편의를 위해 24시간 무중단으로 자동 셀프 탑승 수속 키오스크가 운영됩니다."),
        ("round-trip", "왕복의; 왕복 여행", "adj", "round-trip ticket / round-trip flight", "return / two-way",
         "Securing a round-trip ticket three weeks ahead saved the enterprise twenty percent.", "3주 전에 왕복 항공권을 미리 예매하여 기업은 20%의 출장비를 절감할 수 있었습니다."),
        ("one-way", "편도의", "adj", "one-way street / one-way ticket", "single / outbound",
         "Consultants booked a one-way ticket because the assignment's duration was uncertain.", "파견 프로젝트 기간이 불확실했기 때문에 컨설턴트들은 편도 항공권을 예약했습니다."),
        ("express", "급행의, 고속의, 특급의; 표현하다", "adj", "express train / express delivery", "rapid / fast / non-stop",
         "The express airport train reaches downtown within thirty-five traffic-free minutes.", "공항 급행열차를 타면 교통 체증 없이 35분 만에 시내에 도착할 수 있습니다."),
        ("valid", "유효한, 타당한", "adj", "valid passport / valid driver's license", "legal / current / legitimate",
         "Ensure your international passport remains valid for at least six months from departure.", "출발일로부터 여권의 유효기간이 최소 6개월 이상 남아 있는지 반드시 확인하십시오."),
        ("expire", "만료되다, 기한이 지나다", "verb", "passport expires / contract expires", "lapse / terminate / end",
         "The entry visa will expire on November 30 unless a formal extension is granted.", "공식 연장이 허가되지 않는 한 해당 입국 비자는 11월 30일에 만료됩니다."),
        ("customs", "세관, 관세", "noun", "customs declaration / clear customs", "import duty / border inspection",
         "Fill out the agricultural customs declaration card prior to landing at Heathrow.", "히드로 공항에 착륙하기 전에 농산물 세관 신고서 카드를 작성해 주십시오."),
        ("embark", "탑승하다, 착수하다", "verb", "embark on a flight / embark on a project", "board / start / commence",
         "Travelers queued along the gangway to embark upon the luxury river cruise.", "여행객들은 고급 유람선에 탑승하기 위해 승강 트랩을 따라 줄을 섰습니다."),
        ("disembark", "내리다, 하선하다, 비행기에서 내리다", "verb", "disembark from the aircraft / safely disembark", "leave / get off / deplane",
         "Remain seated with seatbelts fastened until instructions are given to disembark.", "비행기에서 내리라는 안내 방송이 나올 때까지 안전벨트를 맨 채 자리에 착석해 주십시오."),
        ("grounded", "이륙이 금지된, 결항된", "adj", "flights were grounded / grounded aircraft", "stranded / halted",
         "All commercial passenger jets were grounded due to a thick volcanic ash cloud.", "자욱한 화산재 구름으로 인해 모든 상업용 여객기의 이륙이 전면 금지(결항)되었습니다.")
    ]),

    # DAY 14: 호텔 및 편의시설 (34 words)
    14: ("출장/교통", "800필수", [
        ("accommodations", "숙박 시설, 숙소", "noun", "luxury accommodations / overnight accommodations", "lodging / quarters / rooms",
         "The conference registration includes luxury hotel accommodations near the harbor.", "컨퍼런스 등록비에는 항구 근처의 고급 호텔 숙박 시설 이용이 포함되어 있습니다."),
        ("amenity", "편의시설, 쾌적함", "noun", "hotel amenities / standard amenities", "facility / convenience / service",
         "Guests praised the property for upscale amenities like heated pools and sauna baths.", "투숙객들은 온수 수영장과 사우나 등 고급스러운 편의시설에 대해 찬사를 보냈습니다."),
        ("hospitality", "환대, 서비스업", "noun", "Southern hospitality / hospitality management", "welcome / kindness / warmth",
         "She earned a master's degree in international hospitality and tourism management.", "그녀는 국제 환대 및 호텔 관광 경영학 석사 학위를 취득했습니다."),
        ("concierge", "호텔 안내원, 컨시어지", "noun", "ask the concierge / concierge desk", "guest advisor / hotel attendant",
         "The concierge secured last-minute orchestra tickets for the visiting foreign diplomats.", "호텔 컨시어지는 방문한 외국 외교관들을 위해 매진 직전의 오케스트라 티켓을 확보해 주었습니다."),
        ("suite", "스위트룸, 특실", "noun", "presidential suite / executive suite", "luxury apartment / interconnected rooms",
         "The visiting CEO was upgraded to the top-floor executive suite overlooking the bay.", "방문한 CEO는 바다가 내려다보이는 최상층 이그제큐티브 스위트룸으로 무료 업그레이드되었습니다."),
        ("complimentary", "무료의, 칭찬하는", "adj", "complimentary breakfast / complimentary toiletries", "free / gratis / at no charge",
         "A complimentary continental breakfast buffet is served daily from six to ten.", "무료 유럽식 조식 뷔페가 매일 오전 6시부터 10시까지 제공됩니다."),
        ("vacancy", "빈 객실, 공실, 공석", "noun", "no vacancy / hotel vacancy", "available room / opening",
         "Because of the downtown film festival, every reputable hotel hung 'No Vacancy' signs.", "시내 영화제로 인해 평판 좋은 모든 호텔들이 '빈방 없음(만실)' 표지판을 내걸었습니다."),
        ("front desk", "프런트 데스크, 접수처", "noun", "leave keys at the front desk / call the front desk", "reception / lobby counter",
         "If you require extra feather pillows, simply dial zero for the front desk.", "깃털 베개가 더 필요하시다면 프런트 데스크로 0번을 눌러 주시면 됩니다."),
        ("housekeeping", "객실 청소, 시설 관리", "noun", "housekeeping service / call housekeeping", "room cleaning / maintenance",
         "The housekeeping staff replaces linens daily unless guests display eco-cards.", "친환경 카드를 올려놓지 않는 한 객실 청소 직원이 매일 침대 시트를 교체해 드립니다."),
        ("adjoining", "인접한, 서로 붙어 있는", "adj", "adjoining rooms / adjoining terrace", "connecting / neighboring / adjacent",
         "Families traveling with small children frequently request adjoining hotel rooms.", "어린 자녀와 함께 여행하는 가족들은 서로 연결된 인접한 객실을 자주 요청합니다."),
        ("patron", "고객, 단골, 후원자", "noun", "hotel patron / library patron", "customer / client / guest",
         "Hotel patrons enjoy private access to the third-floor fitness center and spa.", "호텔 투숙 고객들은 3층 피트니스 센터와 스파를 전용으로 이용하실 수 있습니다."),
        ("bellhop", "벨보이, 호텔 짐꾼", "noun", "tip the bellhop / friendly bellhop", "porter / luggage attendant",
         "The bellhop placed the heavy suitcases onto a brass trolley and guided guests upstairs.", "벨보이는 황동 카트에 무거운 여행 가방을 싣고 고객들을 위층 객실로 안내했습니다."),
        ("porter", "짐꾼, 수하물 운반원", "noun", "station porter / hotel porter", "baggage handler / bellhop",
         "A uniformed porter met the VIP delegation at the curb to assist with luggage.", "제복을 입은 포터가 짐을 도와주기 위해 차량 진입로에서 VIP 대표단을 맞이했습니다."),
        ("check-in", "체크인, 투숙 수속", "noun", "check-in time / online check-in", "registration / arrival procedure",
         "Standard hotel check-in time begins at three in the afternoon.", "호텔의 표준 체크인(투숙 수속) 시간은 오후 3시부터 시작됩니다."),
        ("checkout", "체크아웃, 퇴실", "noun", "late checkout / checkout desk", "departure / departure time",
         "Diamond loyalty club members are entitled to complimentary late checkout until two.", "다이아몬드 우수 회원에게는 오후 2시까지 무료 레이트 체크아웃 혜택이 주어집니다."),
        ("occupancy", "투숙률, 점유율", "noun", "occupancy rate / maximum occupancy", "inhabitation / tenanted ratio",
         "Peak summer tourist season boosted resort hotel occupancy rates to ninety-eight percent.", "여름 휴가 성수기 덕분에 리조트 호텔의 객실 투숙률이 98%까지 치솟았습니다."),
        ("surcharge", "추가 요금, 할증료", "noun", "fuel surcharge / late surcharge", "extra fee / additional charge",
         "A nominal five-dollar surcharge applies for room service orders placed past midnight.", "자정 이후에 주문하시는 룸서비스에는 5달러의 소액 추가 할증료가 부과됩니다."),
        ("cancellation", "예약 취소, 취소", "noun", "free cancellation / cancellation deadline", "revocation / refund notice",
         "Bookings carry free cancellation up to forty-eight hours prior to scheduled arrival.", "예정된 도착일 48시간 전까지는 위약금 없는 무료 예약 취소가 가능합니다."),
        ("deposit", "보증금, 착수금; 예치하다", "noun", "security deposit / nonrefundable deposit", "down payment / retainer",
         "Guests must furnish a credit card imprint as a security deposit for incidental room costs.", "투숙객은 부대시설 이용 보증금으로 신용카드 승인 내역을 제공해야 합니다."),
        ("incidental", "부수적인; 부대비용", "adj", "incidental expenses / incidental charges", "minor / secondary / subsidiary",
         "Minibar snacks and long-distance phone calls constitute incidental room charges.", "미니바 간식과 국제 전화 요금은 객실 부대비용(기타 경비)에 해당합니다."),
        ("valet", "주차 대행원, 시중꾼", "noun", "valet parking / valet service", "parking service / attendant",
         "Hand your vehicle keys to the curbside valet upon arriving at the hotel entryway.", "호텔 입구에 도착하신 후 승차장의 주차 요원(발레)에게 차 키를 맡겨 주십시오."),
        ("shuttle", "왕복 운행 셔틀", "noun", "hotel shuttle / complimentary airport shuttle", "transfer van / transit",
         "The complimentary hotel shuttle departs every half-hour for the convention center.", "무료 호텔 셔틀버스는 컨벤션 센터를 향해 30분 간격으로 출발합니다."),
        ("linens", "침구류, 시트, 리넨", "noun", "fresh linens / clean bed linens", "bedding / sheets / pillowcases",
         "The resort uses only hypoallergenic organic cotton linens in all oceanfront bungalows.", "그 리조트는 모든 해변 방갈로에서 저자극성 유기농 면 침구류만을 사용합니다."),
        ("toiletries", "세면도구, 화장품류", "noun", "complimentary toiletries / travel toiletries", "bath products / soaps",
         "Eco-friendly bamboo toothbrushes and organic shampoos are provided among the toiletries.", "친환경 대나무 칫솔과 유기농 샴푸가 세면도구 어메니티로 제공됩니다."),
        ("refurbish", "새로 꾸미다, 개조하다", "verb", "refurbish guest rooms / completely refurbished", "renovate / remodel / modernize",
         "The historic downtown hotel spent millions to refurbish all two hundred guest rooms.", "역사 깊은 시내 호텔은 200개 전 객실을 새로 단장하기 위해 수백만 달러를 투자했습니다."),
        ("renovation", "보수 공사, 리모델링", "noun", "undergo renovation / hotel renovation", "remodeling / overhaul / restoration",
         "The indoor swimming pavilion will be closed next month for scheduled tiled renovation.", "실내 수영장은 타일 보수 공사 일정으로 인해 다음 달 임시 휴관합니다."),
        ("cordial", "다정한, 진심 어린", "adj", "cordial welcome / cordial invitation", "warm / gracious / friendly",
         "We extend our most cordial welcome to all visiting executives and their families.", "방문하신 모든 임원진과 가족 여러분께 가장 다정하고 진심 어린 환영의 인사를 전합니다."),
        ("impeccable", "흠잡을 데 없는, 완벽한", "adj", "impeccable service / impeccable hygiene", "flawless / spotless / faultless",
         "The five-star resort is globally renowned for its impeccable personalized room service.", "그 5성급 리조트는 흠잡을 데 없는 맞춤형 룸서비스로 전 세계적인 명성을 얻고 있습니다."),
        ("patronage", "단골 이용, 후원, 애용", "noun", "thank you for your patronage / corporate patronage", "custom / business / support",
         "We value your continuous patronage and are pleased to offer you an upgraded room.", "고객님의 지속적인 애용에 감사드리며, 업그레이드된 객실을 제공해 드리게 되어 기쁩니다."),
        ("hospitality", "환대, 서비스업", "noun", "genuine hospitality / hospitality sector", "warmth / welcome / graciousness",
         "Frontline desk clerks undergo rigorous sensitivity training in authentic hospitality.", "프런트 데스크 직원들은 진정한 고객 환대 정신에 관한 철저한 친절 교육을 받습니다."),
        ("spacious", "넓은, 널찍한", "adj", "spacious bathroom / spacious suite", "roomy / capacious / commodious",
         "The corner suite offers a spacious balcony with sweeping panoramic vistas of the marina.", "코너 스위트룸은 마리나 항구의 파노라마 전망이 시원하게 펼쳐지는 널찍한 발코니를 자랑합니다."),
        ("panoramic", "파노라마의, 전경의", "adj", "panoramic views / panoramic observation deck", "wide-angle / scenic / bird's-eye",
         "Diners at the rooftop terrace enjoy panoramic skyline views of downtown skyscrapers.", "루프탑 테라스의 식사 손님들은 도심 마천루의 파노라마 스카이라인 전망을 감상할 수 있습니다."),
        ("soundproof", "방음의; 방음 장치를 하다", "adj", "soundproof windows / fully soundproofed", "insulated / acoustic",
         "Double-glazed soundproof glass ensures tranquil sleep despite busy runway departures.", "이중 접합 방음 유리 덕분에 활주로의 잦은 비행기 이륙 소음에도 편안한 숙면이 보장됩니다."),
        ("beverage", "음료", "noun", "alcoholic beverages / hot and cold beverages", "drinks / refreshments / spirits",
         "Complimentary hot and cold beverages are accessible twenty-four hours in the lounge.", "라운지에서는 24시간 내내 따뜻한 음료와 시원한 음료를 무료로 이용하실 수 있습니다.")
    ]),

    # DAY 15: 고객 서비스 및 상담 지원 (34 words)
    15: ("고객지원", "800필수", [
        ("inquiry", "문의, 질문, 조사", "noun", "handle customer inquiries / direct inquiries", "query / question / interrogation",
         "Customer care agents respond to general product inquiries within twenty-four hours.", "고객 지원 상담원들은 일반 제품 문의 사항에 대해 24시간 이내에 답변을 제공합니다."),
        ("complaint", "불만, 항의, 민원", "noun", "file a complaint / resolve complaints", "grievance / objection / dispute",
         "The store manager resolved the billing complaint immediately by issuing a store gift card.", "매장 지점장은 매장 상품권을 지급하여 결제 불만 민원을 즉시 원만하게 해결했습니다."),
        ("resolution", "해결, 해결책, 결의안", "noun", "dispute resolution / satisfactory resolution", "settlement / solution / remedy",
         "Our primary focus is the swift, courteous resolution of every reported delivery delay.", "저희의 최우선 과제는 접수된 모든 배송 지연 건에 대한 신속하고 정중한 해결입니다."),
        ("satisfaction", "만족, 만족도", "noun", "customer satisfaction / guarantee satisfaction", "contentment / pleasure / happiness",
         "The brand maintains a celebrated ninety-five percent customer satisfaction index.", "그 브랜드는 95%라는 높은 고객 만족도 지수를 자랑스럽게 유지하고 있습니다."),
        ("courteous", "정중한, 공손한", "adj", "courteous representative / courteous service", "polite / respectful / civil",
         "Call center staff are instructed to remain exceptionally courteous even with angry callers.", "콜센터 상담원들은 화가 난 고객과의 통화에서도 각별히 정중한 태도를 유지하도록 교육받습니다."),
        ("promptly", "지체 없이, 신속하게", "adv", "respond promptly / promptly address", "swiftly / immediately / without delay",
         "Technical tickets marked 'Urgent' must be addressed promptly within sixty minutes.", "'긴급'으로 표시된 기술 지원 요청 건은 60분 이내에 지체 없이 처리되어야 합니다."),
        ("warranty", "품질 보증서", "noun", "valid warranty / claim under warranty", "guarantee / certificate",
         "Defective microchips will be repaired or swapped free of charge while under warranty.", "품질 보증 기간 동안 결함이 있는 마이크로칩은 무료로 수리되거나 교체됩니다."),
        ("refund", "환불; 환불하다", "noun", "full refund / request a refund", "reimbursement / repayment / rebate",
         "Shoppers unsatisfied with their online orders may claim a full refund within thirty days.", "온라인 주문에 만족하지 못한 구매 고객은 30일 이내에 전액 환불을 요청할 수 있습니다."),
        ("exchange", "교환; 교환하다", "noun", "exchange for another size / exchange policy", "swap / substitution / trade",
         "Bring the original store receipt to facilitate an immediate size exchange for footwear.", "신발의 즉각적인 사이즈 교환을 원활히 진행하시려면 매장 영수증 원본을 지참하십시오."),
        ("representative", "상담원, 대표자; 대표하는", "noun", "customer service representative / sales rep", "agent / delegate / proxy",
         "A friendly representative is available via online chat to guide you through order setup.", "주문 설정을 도와드리기 위해 친절한 고객 지원 상담원이 온라인 채팅 대기 중입니다."),
        ("hotline", "직통 상담 전화, 핫라인", "noun", "toll-free hotline / emergency hotline", "helpline / support line",
         "Dial our toll-free customer assistance hotline for immediate billing assistance.", "청구서 결제 관련 즉각적인 도움이 필요하시면 당사의 수신자 부담 고객 직통 핫라인으로 전화하십시오."),
        ("toll-free", "수신자 부담의, 무료 전화의", "adj", "toll-free number / toll-free calling", "freephone / complimentary call",
         "Call our toll-free customer support number from anywhere across the United States.", "미국 전역 어디에서나 당사의 수신자 부담 고객 지원 번호로 전화해 주십시오."),
        ("escalate", "상부로 이관하다, 확대되다", "verb", "escalate the issue / escalate a complaint", "raise / elevate / pass up",
         "If the frontline agent cannot settle the billing discrepancy, escalate it to the supervisor.", "일선 상담원이 청구액 불일치를 해결할 수 없을 경우, 상급 관리자에게 안건을 이관하십시오."),
        ("apologize", "사과하다", "verb", "apologize for the inconvenience / sincerely apologize", "express regret / make amends",
         "We sincerely apologize for the unexpected flight delay caused by thunderstorm turbulence.", "뇌우 난기류로 인한 갑작스러운 항공편 지연에 대해 고객 여러분께 진심으로 사과드립니다."),
        ("compensation", "배상금, 보상", "noun", "financial compensation / offer compensation", "reparation / restitution / indemnity",
         "The airline provided hotel vouchers and cash compensation for canceled holiday departures.", "항공사는 취소된 연휴 항공편에 대해 호텔 숙박 바우처와 현금 배상금을 제공했습니다."),
        ("rectify", "바로잡다, 시정하다", "verb", "rectify the mistake / rectify a situation", "correct / amend / remedy / fix",
         "Our team worked feverishly through the night to rectify the inventory database glitch.", "저희 팀은 재고 데이터베이스의 오류를 바로잡기 위해 밤새 맹렬히 작업했습니다."),
        ("remedy", "구제책, 해결책; 바로잡다", "noun", "legal remedy / effective remedy", "cure / solution / corrective action",
         "Replacing the malfunctioning compressor is the only reliable remedy for cooling failure.", "오작동하는 압축기를 교체하는 것만이 냉각 장애를 해결할 유일하고 확실한 해결책입니다."),
        ("discontent", "불만, 불평", "noun", "customer discontent / express discontent", "dissatisfaction / unhappiness",
         "Frequent price increases without added services generated widespread subscriber discontent.", "서비스 추가 없는 잦은 요금 인상은 광범위한 구독자들의 불만을 초래했습니다."),
        ("survey", "설문 조사; 조사하다", "noun", "conduct a survey / satisfaction survey", "poll / questionnaire / review",
         "We regularly conduct random telephone surveys to evaluate field technician professionalism.", "우리는 현장 기술자의 전문성을 평가하기 위해 무작위 전화 설문 조사를 정기적으로 실시합니다."),
        ("empathy", "공감, 감정이입", "noun", "show empathy / listen with empathy", "compassion / understanding / rapport",
         "Frontline support agents must listen with genuine empathy when callers face disruptions.", "고객이 서비스 장애를 겪고 있을 때 일선 지원 상담원은 진심 어린 공감을 담아 경청해야 합니다."),
        ("assurance", "확신, 보증, 장담", "noun", "give assurances / quality assurance", "guarantee / promise / pledge",
         "The chief operations officer gave public assurances that customer data remained secure.", "최고운영책임자는 고객 데이터가 안전하게 보호되고 있다는 점을 대외적으로 공식 확약했습니다."),
        ("defect", "결함, 하자", "noun", "inherent defect / report a defect", "fault / flaw / blemish",
         "Customers who report a manufacturer defect within ninety days receive an instant replacement.", "90일 이내에 제조사 결함을 신고하시는 고객에게는 즉각적인 새 제품 교환이 제공됩니다."),
        ("reiterate", "되풀이하다, 거듭 강조하다", "verb", "reiterate our commitment / reiterate policy", "repeat / restate / emphasize",
         "Management wishes to reiterate its unwavering commitment to customer data privacy.", "경영진은 고객 데이터 프라이버시 보호에 대한 확고한 약속을 거듭 강조하고자 합니다."),
        ("retrieve", "조회하다, 되찾다", "verb", "retrieve customer records / retrieve orders", "access / fetch / recover",
         "Please give the agent your phone number so she can retrieve your active service profile.", "상담원이 고객님의 활성 서비스 프로필을 조회할 수 있도록 전화번호를 알려주시기 바랍니다."),
        ("clarify", "명확하게 설명하다, 해명하다", "verb", "clarify the policy / clarify terms", "explain / elucidate / spell out",
         "The supervisor came on the line to clarify the international roaming charge structure.", "관리자가 직접 전화를 넘겨받아 해외 로밍 요금 부과 체계를 명확하게 설명했습니다."),
        ("courtesy", "예의, 공손함, 무료 서비스", "noun", "as a courtesy / common courtesy", "politeness / civility / generosity",
         "As a special courtesy for the postal delay, we have waived your shipping and handling fees.", "배송 지연에 대한 특별한 배려(무료 서비스) 차원에서 배송 및 취급 수수료를 면제해 드렸습니다."),
        ("unattended", "방치된, 돌보지 않는", "adj", "leave luggage unattended / unattended terminal", "abandoned / neglected",
         "For security reasons, any luggage left unattended in the terminal will be confiscated.", "보안상의 이유로 터미널 내에 방치된 모든 수하물은 즉시 압수 조치됩니다."),
        ("dedication", "헌신, 전념", "noun", "dedication to customer excellence / tireless dedication", "commitment / devotion / loyalty",
         "Our staff was honored with an industry award for their tireless dedication to service.", "저희 직원들은 고객 서비스를 향한 지칠 줄 모르는 헌신을 인정받아 업계 표창을 받았습니다."),
        ("informative", "유익한, 정보를 주는", "adj", "informative guidebook / highly informative", "educational / enlightening / helpful",
         "Customers found the newly redesigned website FAQ section exceptionally informative.", "고객들은 새롭게 개편된 웹사이트 FAQ 질문 코너가 매우 유익하다고 평가했습니다."),
        ("troubleshoot", "문제점을 해결하다", "verb", "troubleshoot hardware / remote troubleshooting", "diagnose / resolve / fix",
         "Our technical helpdesk can connect remotely to your terminal to troubleshoot network setup.", "네트워크 설정을 점검 해결해 드리기 위해 기술 지원팀이 고객 단말기에 원격으로 접속할 수 있습니다."),
        ("feedback", "피드백, 소감", "noun", "positive feedback / solicit feedback", "comments / reviews / suggestions",
         "We value your honest feedback and utilize it daily to refine our customer journey.", "저희는 고객님의 솔직한 피드백을 소중히 여기며, 고객 여정을 개선하는 데 매일 반영하고 있습니다."),
        ("loyal", "충성스러운, 단골의", "adj", "loyal clientele / loyal subscribers", "faithful / devoted / committed",
         "Exclusive loyalty points are awarded to thank our most loyal long-term subscribers.", "가장 충성도 높은 장기 구독자 고객분들께 감사드리기 위해 전용 로열티 포인트를 적립해 드립니다."),
        ("conciliatory", "달래는, 회유적인", "adj", "conciliatory gesture / conciliatory tone", "appeasing / pacifying / accommodating",
         "The airline offered complimentary flight upgrades as a conciliatory gesture to passengers.", "항공사는 승객들을 달래기 위한 유화적인 조치로 무료 좌석 업그레이드를 제공했습니다."),
        ("exceptional", "탁월한, 예외적인", "adj", "exceptional service / exceptional quality", "outstanding / extraordinary / superb",
         "The boutique law firm prides itself on delivering exceptional personalized advisory care.", "그 부티크 로펌은 탁월한 맞춤형 자문 케어 서비스를 제공하는 것에 큰 자부심을 가지고 있습니다.")
    ]),

    # DAY 16: 부동산, 임대차 및 리모델링 (34 words)
    16: ("부동산/시설", "800필수", [
        ("lease", "임대차 계약; 임대하다", "noun", "sign a commercial lease / expire on lease", "rental agreement / charter / tenancy",
         "The architecture firm signed a five-year commercial lease for the downtown warehouse loft.", "그 건축 사무소는 시내 창고 로프트 공간에 대해 5년간의 상업용 임대차 계약을 체결했습니다."),
        ("tenant", "임차인, 세입자", "noun", "prospective tenant / commercial tenant", "renter / leaseholder / occupant",
         "Building management notified all commercial tenants about the upcoming elevator upgrade.", "건물 관리사무소는 예정된 엘리베이터 교체 공사에 대해 모든 상가 세입자에게 공지했습니다."),
        ("landlord", "임대인, 건물주", "noun", "property landlord / negotiate with the landlord", "owner / lessor / proprietor",
         "The landlord agreed to replace all fluorescent fixtures with modern LED lighting.", "건물주는 모든 형광등 조명을 현대적인 LED 조명으로 교체해 주기로 합의했습니다."),
        ("premises", "부지, 구내, 사업장 건물", "noun", "on the premises / vacate the premises", "property / site / grounds / facility",
         "Smoking and the possession of open flames are strictly forbidden on these premises.", "본 사업장 건물 구내에서는 흡연 및 화기 소지가 엄격히 금지되어 있습니다."),
        ("real estate", "부동산", "noun", "commercial real estate / real estate broker", "property / realty / land and buildings",
         "Investing in metropolitan commercial real estate yielded solid quarterly dividend returns.", "대도시 상업용 부동산에 대한 투자는 견고한 분기별 배당 수익률을 가져다주었습니다."),
        ("renovation", "보수 공사, 리모델링", "noun", "extensive renovation / kitchen renovation", "refurbishment / remodeling / makeover",
         "The historic downtown bank building underwent extensive renovation to become luxury condos.", "유서 깊은 시내 은행 건물은 고급 콘도로 탈바꿈하기 위해 광범위한 보수 공사를 거쳤습니다."),
        ("refurbish", "재단장하다, 새로 꾸미다", "verb", "refurbish the lobby / newly refurbished", "renovate / remodel / recondition",
         "Work crews labored around the clock to refurbish the corporate reception foyer.", "작업반원들은 본사 접견실 로비를 재단장하기 위해 24시간 내내 작업했습니다."),
        ("deposit", "임대 보증금, 예치금", "noun", "security deposit / return the deposit", "down payment / bond / guarantee",
         "The landlord will return the one-month security deposit upon final move-out inspection.", "임대인은 최종 퇴거 점검 완료 즉시 한 달 치 임대 보증금을 반환해 줄 것입니다."),
        ("evict", "퇴거시키다, 쫓아내다", "verb", "evict delinquent tenants / legally evict", "expel / oust / remove",
         "The municipal court authorized the landlord to legally evict the nonpaying commercial tenant.", "시 법원은 임대료를 미납한 상가 세입자를 합법적으로 강제 퇴거시킬 수 있도록 허가했습니다."),
        ("sublet", "전대하다 (세입자가 다른 사람에게 재임대하다)", "verb", "sublet the office / sublet space", "sublease / re-rent",
         "With half its workforce remote, the law firm decided to sublet its unused third floor.", "인력의 절반이 원격 근무를 하게 되자 그 로펌은 사용하지 않는 3층 공간을 전대하기로 결정했습니다."),
        ("amenities", "생활 편의시설", "noun", "building amenities / fitness amenities", "facilities / conveniences / features",
         "The newly erected residential high-rise offers upscale amenities including a rooftop pool.", "새로 지어진 고층 주거용 타워는 루프탑 수영장을 포함한 고급 편의시설을 제공합니다."),
        ("occupancy", "입주, 점유", "noun", "ready for occupancy / certificate of occupancy", "possession / habitation / tenancy",
         "Building inspectors issued an official certificate of occupancy for the new laboratory.", "건축 점검관들은 새 연구소 건물에 대해 공식 입주 허가증을 발급했습니다."),
        ("vacate", "비우다, 퇴거하다", "verb", "vacate the apartment / promptly vacate", "leave / abandon / quit",
         "Tenants whose leases terminate on June 30 are expected to vacate the rooms by noon.", "6월 30일에 계약이 만료되는 세입자들은 정오까지 방을 비워 주셔야 합니다."),
        ("demolish", "철거하다, 허물다", "verb", "demolish old structures / completely demolish", "tear down / raze / level",
         "City contractors were commissioned to demolish the derelict warehouse along the pier.", "시 계약업체들은 부두를 따라 늘어선 방치된 폐창고를 철거하도록 의뢰받았습니다."),
        ("spacious", "널찍한, 넓은", "adj", "spacious floor plan / spacious corner office", "roomy / capacious / large",
         "The newly renovated design studio features a spacious open-concept conference lounge.", "새로 리모델링된 디자인 스튜디오는 널찍한 오픈형 회의 라운지를 갖추고 있습니다."),
        ("adjacent", "인접한, 바로 옆의", "adj", "adjacent to the highway / adjacent parcel", "neighboring / adjoining / contiguous",
         "The developer acquired two acres of farmland adjacent to the newly opened freight rail spur.", "개발업자는 새로 개통된 화물 철도 인입선에 인접한 2에이커의 농지를 매입했습니다."),
        ("utility", "공과금 (수도/전기/가스), 다용도의", "noun", "utilities included / public utility", "services / gas and electric",
         "Unless specified otherwise in the agreement, the monthly rent does not cover utilities.", "계약서에 별도로 명시되지 않는 한, 월 임대료에 수도·전기 등 공과금은 포함되지 않습니다."),
        ("furnish", "가구를 비치하다, 공급하다", "verb", "fully furnished / tastefully furnish", "equip / outfit / provide",
         "Corporate expatriates were accommodated in tastefully furnished luxury harbor condos.", "해외 파견 임원들은 가구가 완벽하고 품격 있게 비치된 고급 하버 콘도에 머물렀습니다."),
        ("zoning", "용도 지역제, 토지 구획", "noun", "zoning laws / commercial zoning", "land division / planning regulation",
         "The municipal council amended regional zoning laws to encourage green technology parks.", "시의회는 친환경 기술 연구단지 조성을 장려하기 위해 지역 토지 구획 조례를 개정했습니다."),
        ("contractor", "시공업체, 도급업자", "noun", "general contractor / certified contractor", "builder / developer / specialist",
         "The general contractor estimates structural framing will conclude by early November.", "종합 시공업체는 골조 공사가 11월 초까지 마무리될 것으로 추정하고 있습니다."),
        ("blueprint", "설계도, 도면", "noun", "review the blueprints / architectural blueprint", "floor plan / schematic / plan",
         "Inspectors compared the actual electrical conduit runs directly against the approved blueprints.", "점검관들은 실제 전기 배관 시공 상태를 승인된 청사진(설계도)과 대조 확인했습니다."),
        ("fixtures", "정착물, 붙박이 설비", "noun", "lighting fixtures / plumbing fixtures", "fittings / installations",
         "The commercial lease stipulates that all installed ceiling fixtures become landlord property.", "상가 임대차 계약서는 설치된 모든 천장 조명 부착 설비가 건물주의 소유가 된다고 규정합니다."),
        ("ventilation", "환기, 통풍 장치", "noun", "proper ventilation / ventilation system", "air circulation / aeration",
         "Labor regulations mandate proper industrial ventilation throughout battery charging rooms.", "노동 규정은 배터리 충전실 전역에 적절한 산업용 환기 시설을 갖출 것을 의무화합니다."),
        ("insulation", "단열재, 절연", "noun", "thermal insulation / sound insulation", "lagging / protective barrier",
         "Adding high-density thermal insulation into attic spaces slashed winter heating bills by 20%.", "다락방 공간에 고밀도 단열재를 추가 시공하여 겨울철 난방비를 20% 대폭 절감했습니다."),
        ("facade", "건물 외벽, 정면, 겉모습", "noun", "limestone facade / modern glass facade", "frontage / exterior / face",
         "Architects preserved the century-old brick facade while completely modernizing interior spaces.", "건축가들은 내부 공간을 전면 현대화하면서도 100년 된 벽돌 외벽(파사드)을 온전히 보존했습니다."),
        ("scaffolding", "비계 (건설 현장 발판)", "noun", "erect scaffolding / dismantling scaffolding", "framework / staging / platform",
         "Painters mounted twenty-foot metal scaffolding along the exterior of the museum building.", "도색공들은 박물관 건물 외벽을 따라 20피트 높이의 금속 작업 발판(비계)을 설치했습니다."),
        ("plumbing", "배관 설비", "noun", "plumbing contractor / faulty plumbing", "pipes / water drainage",
         "A master plumber was dispatched immediately to repair burst underground supply pipes.", "파열된 지하 송수관을 수리하기 위해 전문 배관 기사가 즉시 급파되었습니다."),
        ("electrical", "전기의, 전력의", "adj", "electrical wiring / electrical engineer", "power / electric / electronic",
         "Certified electricians upgraded all basement wiring to support high-speed vehicle chargers.", "공인 전기 기술자들은 고속 전기차 충전기를 지원하기 위해 지하실의 모든 배선을 업그레이드했습니다."),
        ("appraisal", "감정 평가, 부동산 가치 산정", "noun", "property appraisal / independent appraisal", "valuation / assessment / estimate",
         "The mortgage bank required an official certified real estate appraisal before loan approval.", "주택담보대출 은행은 대출 승인 전 공인 부동산 감정 평가서를 제출할 것을 요구했습니다."),
        ("surveyor", "측량사, 감정인", "noun", "land surveyor / licensed surveyor", "assessor / inspector / valuer",
         "A licensed surveyor mapped the precise perimeter boundaries prior to fence installation.", "울타리 설치에 앞서 공인 토지 측량사가 정확한 외곽 부지 경계선을 측정했습니다."),
        ("demarcation", "경계 설정, 구분", "noun", "line of demarcation / property demarcation", "boundary / separation / division",
         "Yellow painted stripes mark the clear demarcation between public sidewalks and private patios.", "노란색 페인트 선은 공공 인도와 사유 테라스 간의 명확한 경계 구분을 나타냅니다."),
        ("dilapidated", "황폐한, 다 허물어져 가는", "adj", "dilapidated building / dilapidated state", "run-down / ramshackle / decayed",
         "The investor acquired the dilapidated historic mill and transformed it into a technology hub.", "그 투자자는 다 허물어져 가던 유서 깊은 방직공장을 인수하여 첨단 기술 허브로 변모시켰습니다."),
        ("residential", "주거의, 주택가의", "adj", "residential area / residential zoning", "domestic / housing / neighborhood",
         "Commercial retail stores are barred from opening within this strictly residential district.", "이 엄격한 주거 전용 구역 내에서는 상업용 소매점 개업이 금지되어 있습니다."),
        ("commercial", "상업의, 영리적인", "adj", "commercial property / commercial district", "business / mercantile / trade",
         "Vacant commercial office spaces downtown are gradually being repurposed as residential lofts.", "시내의 비어 있는 상업용 오피스 공간들이 점차 주거용 로프트로 용도 변경되고 있습니다.")
    ]),

    # DAY 17: 환경, 에너지 및 자원 관리 (34 words)
    17: ("환경/에너지", "800필수", [
        ("sustainable", "지속 가능한, 환경을 파괴하지 않는", "adj", "sustainable energy / sustainable practices", "renewable / eco-friendly / green",
         "The corporate charter requires suppliers to adopt verified sustainable forestry methods.", "회사 규정은 공급업체들이 검증된 지속 가능한 삼림 벌채 방식을 채택하도록 요구합니다."),
        ("renewable", "재생 가능한", "adj", "renewable energy sources / renewable resources", "sustainable / green / inexhaustible",
         "The municipality powers eighty percent of municipal streetlamps with renewable solar power.", "시는 시내 가로등의 80%를 재생 가능한 태양광 전력으로 가동하고 있습니다."),
        ("emission", "배출, 배출물", "noun", "carbon emissions / zero emissions", "exhaust / discharge / pollutant",
         "New industrial scrubbers cut harmful factory sulfur emissions by over ninety percent.", "새 산업용 세정 장치를 도입하여 유해한 공장 황 배출량을 90% 이상 줄였습니다."),
        ("conserve", "보존하다, 아끼다, 절약하다", "verb", "conserve energy / conserve natural resources", "save / preserve / protect",
         "Staff are requested to switch off all monitor arrays each evening to conserve power.", "전력을 절약하기 위해 매일 저녁 모든 모니터를 꺼 주실 것을 직원들에게 당부드립니다."),
        ("conservation", "보존, 절약", "noun", "water conservation / energy conservation", "preservation / economy / protection",
         "The paper mill introduced an innovative water conservation recycling loop.", "그 제지 공장은 혁신적인 용수 절약 재활용 순환 시스템을 도입했습니다."),
        ("footprint", "발자국, 탄소 발자국, 면적", "noun", "carbon footprint / environmental footprint", "ecological impact / impact",
         "Relocating parts sourcing domestically slashed our corporate logistics carbon footprint.", "부품 조달처를 국내로 이전하여 기업 물류의 탄소 발자국을 대폭 줄였습니다."),
        ("hazardous", "유해한, 위험한", "adj", "hazardous waste / hazardous chemicals", "dangerous / toxic / toxic",
         "Federal manifests must accompany all interstate transfers of hazardous chemical drums.", "유해 화학물질 드럼통의 모든 주간 운송에는 연방 안전 명세서가 동봉되어야 합니다."),
        ("pollutant", "오염 물질", "noun", "air pollutants / industrial pollutants", "contaminant / toxin / waste",
         "Advanced catalytic converters trap toxic microscopic pollutants before exhaust vents.", "첨단 촉매 변환기는 배기구가 배출되기 전에 유독한 미세 오염 물질을 포집합니다."),
        ("contaminate", "오염시키다", "verb", "contaminate groundwater / accidentally contaminate", "pollute / taint / poison",
         "Improper disposal of spent lithium batteries can severely contaminate local water tables.", "폐리튬 배터리를 부적절하게 폐기하면 지역 지하수층을 심각하게 오염시킬 수 있습니다."),
        ("recycle", "재활용하다", "verb", "recycle paper / recyclable packaging", "reuse / reprocess / reclaim",
         "The cafeteria replaced plastic cutlery with compostable cups that staff can recycle.", "구내식당은 플라스틱 식기를 직원들이 재활용할 수 있는 퇴비화 가능 컵으로 교체했습니다."),
        ("deplete", "고갈시키다, 대폭 줄이다", "verb", "deplete resources / deplete reserves", "exhaust / drain / empty",
         "Overfishing during the past decade threatened to deplete indigenous coastal fish stocks.", "지난 10년간의 남획은 연안 토착 어류 자원을 고갈시킬 위협을 초래했습니다."),
        ("depletion", "고갈, 소모", "noun", "ozone depletion / resource depletion", "exhaustion / reduction / consumption",
         "International treaties were ratified to halt the chemical depletion of the ozone layer.", "오존층의 화학적 고갈을 막기 위한 국제 조약이 비준되었습니다."),
        ("efficient", "효율적인, 유능한", "adj", "energy-efficient / highly efficient", "productive / economical / effective",
         "Upgrading to energy-efficient heat pump systems lowered annual operating overhead.", "에너지 효율적인 히트펌프 시스템으로 교체하여 연간 운영비를 절감했습니다."),
        ("efficiency", "효율, 능률", "noun", "thermal efficiency / operational efficiency", "productivity / economy / performance",
         "Automated climate control sensors improved heating efficiency by fourteen percent.", "자동 냉난방 센서 덕분에 난방 효율이 14% 향상되었습니다."),
        ("consumption", "소비, 소비량", "noun", "fuel consumption / power consumption", "usage / expenditure / burn rate",
         "Aerodynamic side skirts on long-haul trucks cut diesel fuel consumption considerably.", "장거리 대형 트럭의 공기역학 사이드 스커트는 디젤 연료 소비량을 상당히 줄여줍니다."),
        ("ecology", "생태, 생태학", "noun", "marine ecology / fragile ecology", "ecosystem / environment",
         "Developers altered pipeline routing to avoid disrupting fragile wetland bird ecology.", "개발업자들은 연약한 습지 조류 생태계 파괴를 피하기 위해 송유관 경로를 변경했습니다."),
        ("biodegradable", "생분해성의", "adj", "biodegradable packaging / biodegradable materials", "degradable / compostable / eco-friendly",
         "All packing peanuts used in our parcel shipments are made from biodegradable cornstarch.", "저희 택배 배송에 사용되는 모든 완충재는 생분해성 옥수수 전분으로 제작됩니다."),
        ("solar", "태양광의, 태양의", "adj", "solar panels / solar energy", "sun-powered / photovoltaic",
         "Installing rooftop solar panels enabled the manufacturing facility to achieve net-zero power.", "지붕에 태양광 패널을 설치하여 제조 시설은 전력 넷제로를 달성할 수 있었습니다."),
        ("turbine", "터빈, 풍차 발전기", "noun", "wind turbine / steam turbine", "generator / windmill / rotor",
         "Offshore wind turbines generate enough clean kilowatt-hours to illuminate twenty thousand homes.", "해상 풍력 터빈은 2만 가구에 전력을 공급할 만큼 충분한 청정에너지를 생산합니다."),
        ("grid", "전력망, 격자", "noun", "power grid / electrical grid", "network / transmission system",
         "Surplus solar power generated on sunny afternoons is fed back into the regional grid.", "맑은 날 오후에 생산된 잉여 태양광 전력은 지역 전력망으로 다시 공급됩니다."),
        ("subsidy", "보조금, 장려금", "noun", "government subsidies / renewable energy subsidy", "grant / financial aid / allowance",
         "Federal subsidies helped offset the upfront capital expenditure of installing geothermal heat.", "연방 정부 보조금 덕분에 지열 냉난방 설비 설치에 따른 초기 자본 지출을 상쇄할 수 있었습니다."),
        ("incentive", "혜택, 유인책", "noun", "tax incentive / environmental incentives", "motivation / inducement / rebate",
         "Homeowners receive generous state tax incentives for replacing aging oil boilers.", "주택 소유자들은 노후 기름보일러를 교체할 경우 후한 주 정부 세금 감면 혜택을 받습니다."),
        ("scrutiny", "정밀 조사, 면밀한 검토", "noun", "environmental scrutiny / close scrutiny", "examination / inspection / audit",
         "Chemical waste processing protocols came under intense public regulatory scrutiny.", "화학 폐기물 처리 절차는 대중과 규제 당국의 집중적인 정밀 조사를 받게 되었습니다."),
        ("compliance", "준수, 순응", "noun", "environmental compliance / strict compliance", "adherence / conformity / observance",
         "The enterprise hired a dedicated auditing officer to oversee environmental compliance.", "기업은 환경 규정 준수를 총괄 감독하기 위해 전담 감사관을 고용했습니다."),
        ("mandate", "의무화하다; 지시, 명령", "verb", "mandate recycling / statutory mandate", "require / dictate / order",
         "New municipal ordinances mandate that retail stores charge fifteen cents for plastic bags.", "새로운 시 조례는 소매점이 비닐봉지에 대해 15센트의 요금을 부과하도록 의무화하고 있습니다."),
        ("penalize", "처벌하다, 불이익을 주다", "verb", "penalize polluters / heavily penalized", "punish / fine / discipline",
         "The maritime port authority will penalize cargo vessels that burn bunker fuel near coastlines.", "해양 항만청은 해안선 부근에서 벙커유를 연소하는 화물선에 무거운 벌금을 부과(처벌)할 것입니다."),
        ("repurpose", "용도를 변경하다, 재활용하다", "verb", "repurpose industrial waste / creative repurposing", "reuse / recycle / modify",
         "The brewery discovered an innovative method to repurpose spent yeast into livestock feed.", "맥주 양조장은 사용된 폐효모를 가축 사료로 재활용(용도 변경)하는 혁신적인 방법을 찾아냈습니다."),
        ("compost", "퇴비로 만들다; 퇴비", "verb", "compost food waste / organic compost", "fertilize / rot / decay",
         "Office kitchenettes are equipped with airtight countertop bins to compost coffee grounds.", "사무실 탕비실에는 커피 찌꺼기를 퇴비화할 수 있도록 밀폐형 조리대 전용 통이 비치되어 있습니다."),
        ("byproduct", "부산물", "noun", "industrial byproduct / natural byproduct", "side effect / secondary product",
         "Steam generated as an industrial byproduct is captured to heat adjacent greenhouses.", "산업 부산물로 생성되는 수증기를 포집하여 인접한 온실을 난방하는 데 활용합니다."),
        ("disposal", "폐기, 처분", "noun", "waste disposal / safe disposal", "removal / discard / destruction",
         "Licensed specialists supervise the safe underground disposal of low-grade nuclear remnants.", "공인된 전문가들이 저준위 방사성 잔재물의 안전한 지하 폐기 처분을 감독합니다."),
        ("discharge", "방출하다, 배출하다; 방출", "verb", "discharge pollutants / accidental discharge", "release / emit / leak",
         "The chemical factory was fined half a million dollars for illegally discharging untreated dyes.", "그 화학공장은 정화되지 않은 염료를 불법 방출한 혐의로 50만 달러의 벌금을 부과받았습니다."),
        ("runoff", "유출 액체, 빗물 유출수", "noun", "agricultural runoff / surface runoff", "drainage / overflow / wash",
         "Retention ponds were excavated alongside the plant to filter chemical agricultural runoff.", "화학적 농경지 유출수를 정화하기 위해 공장 부지 옆에 저류지가 굴착되었습니다."),
        ("ecological", "생태학의, 친환경의", "adj", "ecological balance / ecological disaster", "environmental / organic / natural",
         "Protecting coastal mangrove estuaries preserves the fragile ecological balance of the reef.", "연안의 맹그로브 하구를 보호하는 것은 산호초의 취약한 생태학적 균형을 유지해 줍니다."),
        ("neutrality", "중립, 중립성 (탄소 중립)", "noun", "carbon neutrality / achieve neutrality", "impartiality / zero-net balance",
         "The multinational technology giant pledged to attain complete carbon neutrality by 2030.", "그 다국적 기술 대기업은 2030년까지 완전한 탄소 중립을 달성하겠다고 서약했습니다.")
    ]),

    # DAY 18: 은행, 금융 및 투자 (34 words)
    18: ("금융/투자", "800필수", [
        ("transaction", "거래, 매매, 처리", "noun", "financial transaction / processing transactions", "deal / transfer / payment",
         "The mobile banking app allows users to authorize international wire transactions instantly.", "모바일 뱅킹 앱을 통해 사용자들은 해외 송금 거래를 즉시 승인할 수 있습니다."),
        ("deposit", "예금하다, 입금하다; 예금, 보증금", "verb", "deposit funds / direct deposit", "pay in / bank / put down",
         "Salaries are automatically deposited into employee checking accounts on the final Friday.", "급여는 매월 마지막 금요일에 직원 당좌 예금 계좌로 자동 입금됩니다."),
        ("withdrawal", "인출, 회수, 철회", "noun", "ATM withdrawal / make a withdrawal", "taking out / removal / extraction",
         "Daily automated cash withdrawal limits protect customers against unauthorized card fraud.", "일일 자동 현금 인출 한도는 무단 카드 사기로부터 고객을 보호해 줍니다."),
        ("mortgage", "주택담보대출; 저당 잡히다", "noun", "fixed-rate mortgage / apply for a mortgage", "home loan / property loan",
         "Homebuyers locked in thirty-year fixed-rate mortgages before central bank interest increases.", "주택 구매자들은 중앙은행의 금리 인상 전에 30년 고정금리 주택담보대출을 확정 지었습니다."),
        ("interest", "이자, 이율, 관심", "noun", "interest rate / earn interest", "yield / return / percentage",
         "High-yield certificate accounts offer four percent annual interest on locked balances.", "고수익 정기예금 계좌는 묶인 잔액에 대해 연 4%의 이자를 지급합니다."),
        ("collateral", "담보, 담보물", "noun", "pledge collateral / loan collateral", "security / guarantee / surety",
         "The commercial borrower pledged heavy industrial equipment as collateral for the line of credit.", "상업용 차주는 신용 한도 대출의 담보로 중장비 산업 설비를 제공했습니다."),
        ("creditworthiness", "신용도, 지불 능력", "noun", "assess creditworthiness / high creditworthiness", "solvency / credit rating / reliability",
         "Underwriters review five years of audited accounts to evaluate the firm's creditworthiness.", "대출 심사관들은 회사의 신용도를 평가하기 위해 5년 치의 감사된 회계장부를 검토합니다."),
        ("portfolio", "투자 포트폴리오, 작품집", "noun", "investment portfolio / diversify the portfolio", "holdings / asset mix / range",
         "Wealth managers advised clients to diversify their stock portfolios into overseas bonds.", "자산 관리사들은 고객들에게 주식 투자 포트폴리오를 해외 채권으로 다각화할 것을 권고했습니다."),
        ("yield", "수익률, 산출량; 산출하다", "noun", "bond yield / high dividend yield", "return / profit / earnings",
         "Rising benchmark treasury yields attracted conservative institutional pension investors.", "기준 국채 수익률의 상승은 보수적인 기관 연금 투자자들의 자금을 끌어들였습니다."),
        ("dividend", "배당금", "noun", "quarterly dividend / dividend payout", "share of profit / distribution",
         "Energy conglomerates declared record quarterly dividend payouts following surging crude sales.", "에너지 대기업들은 원유 판매 급증에 힘입어 사상 최대 규모의 분기 배당금 지급을 발표했습니다."),
        ("brokerage", "중개업, 증권회사, 중개 수수료", "noun", "brokerage firm / discount brokerage", "agency / broker / commission",
         "Trading stocks through online discount brokerage portals eliminated traditional commissions.", "온라인 할인 증권사 포털을 통해 주식을 거래하면서 기존의 비싼 중개 수수료가 사라졌습니다."),
        ("securities", "유가증권, 주식 및 채권", "noun", "marketable securities / securities exchange", "stocks and bonds / equities / assets",
         "The financial authority audits securities trading accounts to detect insider market tipping.", "금융 당국은 내부자 정보 거래를 적발하기 위해 유가증권 거래 계좌를 감사하고 있습니다."),
        ("fluctuation", "변동, 오르내림", "noun", "currency fluctuation / price fluctuations", "oscillation / variation / volatility",
         "Exporters utilize derivative forward contracts to hedge against sharp currency fluctuations.", "수출업체들은 급격한 환율 변동 위험을 분산(헤지)하기 위해 파생 선물환 계약을 활용합니다."),
        ("hedge", "위험을 분산하다, 헤지하다; 방어책", "verb", "hedge against inflation / risk hedge", "insure / protect / safeguard",
         "Airlines commonly hedge against jet fuel price spikes by purchasing futures options.", "항공사들은 항공유 가격 급등 위험을 방어하기 위해 선물 옵션을 매수하는 헤지 전략을 흔히 사용합니다."),
        ("venture", "벤처, 모험적 사업; 과감히 착수하다", "noun", "venture capital / joint venture", "enterprise / speculation / undertaking",
         "A leading Silicon Valley venture capital fund invested ten million dollars in the biotech lab.", "실리콘밸리의 선도적인 벤처 캐피털 펀드가 그 바이오 기술 연구소에 1,000만 달러를 투자했습니다."),
        ("speculate", "투기하다, 추측하다", "verb", "speculate on real estate / speculate on commodities", "gamble / hypothesize / invest",
         "Financial regulators warned retail investors not to speculate wildly on volatile tokens.", "금융 규제 당국은 일반 개인 투자자들에게 변동성이 심한 코인에 무모하게 투기하지 말 것을 경고했습니다."),
        ("maturity", "만기, 성숙", "noun", "reach maturity / date of maturity", "due date / expiration / fulfillment",
         "Upon the bond reaching its five-year maturity, the principal sum is returned in full.", "채권이 5년 만기에 도달하면 원금 전액이 온전히 반환됩니다."),
        ("principal", "원금, 주요한; 교장", "noun", "principal and interest / repay the principal", "capital / initial sum / original amount",
         "Borrowers may make additional payments directly against the loan principal to cut interest.", "대출 고객은 이자 부담을 줄이기 위해 대출 원금을 직접 조기 상환할 수 있습니다."),
        ("default", "채무 불이행, 부도; 불이행하다", "noun", "default on a loan / risk of default", "failure to pay / delinquency / bankruptcy",
         "Failing to remit bond coupon payments on time pushed the overseas developer into default.", "제때 채권 이자를 송금하지 못한 그 해외 개발업체는 결국 채무 불이행(부도) 상태에 빠졌습니다."),
        ("delinquent", "연체된, 체납된; 체납자", "adj", "delinquent account / delinquent payment", "overdue / past due / unpaid",
         "The bank transfers delinquent credit card accounts to specialized legal recovery agencies.", "은행은 연체된 신용카드 계좌를 전문 채권 추심 법률 대행업체로 이관합니다."),
        ("overdraft", "당좌 대월, 마이너스 통장", "noun", "overdraft protection / overdraft fees", "deficit / overdraft facility",
         "Enabling overdraft protection prevents debit card transactions from bouncing at retail counters.", "마이너스 통장(당좌 대월) 보호 기능을 켜 두면 매장 결제 시 직불카드가 잔액 부족으로 튕기는 것을 방지할 수 있습니다."),
        ("statement", "명세서, 성명서, 진술", "noun", "bank statement / monthly account statement", "financial record / summary / bill",
         "Log in to your mobile portal to download electronic copies of your monthly bank statement.", "월별 은행 거래 명세서 전자 사본을 다운로드하시려면 모바일 포털에 로그인하십시오."),
        ("remittance", "송금, 송금액", "noun", "electronic remittance / foreign remittance", "wire transfer / payment / transfer",
         "The financial app processes international foreign remittances within sixty seconds.", "그 금융 앱은 해외 외화 송금을 60초 이내에 초고속으로 처리합니다."),
        ("clearinghouse", "어음 교환소, 결제원", "noun", "automated clearinghouse / financial clearinghouse", "settlement house / exchange",
         "All interbank electronic direct transfers pass through the federal automated clearinghouse.", "모든 은행 간 전자 계좌이체 거래는 연방 자동 어음 교환소(ACH)를 거치게 됩니다."),
        ("solvency", "지불 능력", "noun", "maintain financial solvency / test bank solvency", "creditworthiness / soundness / stability",
         "National banking authorities review liquidity ratios annually to verify commercial solvency.", "국가 금융 당국은 시중은행의 지급 능력을 검증하기 위해 연례 유동성 비율을 점검합니다."),
        ("depreciation", "가치 하락, 감가상각", "noun", "currency depreciation / asset depreciation", "devaluation / cheapening / drop",
         "Sharp currency depreciation made imported machinery considerably more expensive.", "급격한 자국 통화 가치 하락으로 인해 수입 기계 장비의 가격이 상당히 비싸졌습니다."),
        ("appreciation", "가치 상승, 감사, 이해", "noun", "capital appreciation / currency appreciation", "increase in value / rise / gratitude",
         "Investors seek high-growth technology equities primarily for long-term capital appreciation.", "투자자들은 주로 장기적인 자본 가치 상승(시세 차익)을 노리고 고성장 기술주를 찾습니다."),
        ("convertible", "전환 가능한; 전환사채", "adj", "convertible bond / convertible currency", "exchangeable / adaptable / transferable",
         "The venture issued convertible bonds that can be swapped for common equity in three years.", "그 벤처기업은 3년 후 보통주 지분으로 전환할 수 있는 전환사채(CB)를 발행했습니다."),
        ("lucrative", "수익성이 좋은, 유리한", "adj", "lucrative portfolio / lucrative deal", "profitable / advantageous / gainful",
         "Arbitrage trading in foreign exchange markets can prove exceptionally lucrative.", "외환 시장에서의 차익 거래는 대단히 높은 수익성을 안겨줄 수 있습니다."),
        ("insolvent", "지급 불능의, 파산한", "adj", "declared insolvent / insolvent borrower", "bankrupt / ruined / broke",
         "After defaulting on its bond obligations, the shipping line was declared commercially insolvent.", "채권 채무를 불이행한 후, 그 해운회사는 상업적 지급 불능(파산)을 선고받았습니다."),
        ("fiduciary", "수탁자의, 신임의; 수탁자", "adj", "fiduciary duty / fiduciary responsibility", "trust-based / trustee",
         "Financial investment advisors hold a strict fiduciary duty to prioritize their clients' interests.", "금융 투자 자문사는 고객의 이익을 최우선으로 해야 할 엄격한 수탁자 책임(충실 의무)을 집니다."),
        ("liquidity", "유동성, 환금성", "noun", "ample liquidity / liquidity crisis", "cash availability / cash flow",
         "The central bank injected emergency credit to ensure uninterrupted market liquidity.", "중앙은행은 시장 유동성이 중단 없이 원활히 유지되도록 긴급 자금을 투입했습니다."),
        ("benchmark", "기준점, 지표", "noun", "benchmark rate / industry benchmark", "standard / reference point",
         "The prime rate serves as the standard commercial benchmark for setting variable loan terms.", "우대금리(프라임 레이트)는 변동금리 대출 조건을 설정하는 표준적인 금융 기준점 역할을 합니다."),
        ("recapitalize", "자본을 재구성하다, 증자하다", "verb", "recapitalize the bank / corporate recapitalization", "refinance / inject capital",
         "The consortium voted to recapitalize the struggling airline with five hundred million dollars.", "컨소시엄은 어려움을 겪고 있는 항공사에 5억 달러의 자본을 추가 투입(증자)하기로 결의했습니다.")
    ]),

    # DAY 19: 법률, 규제 및 컴플라이언스 (34 words)
    19: ("법률/규제", "800필수", [
        ("compliance", "법규 준수, 컴플라이언스", "noun", "regulatory compliance / ensure compliance", "conformity / adherence / observance",
         "All international transactions undergo automated monitoring to guarantee sanctions compliance.", "모든 국제 금융 거래는 제재 법규 준수를 보장하기 위해 자동 모니터링을 거칩니다."),
        ("regulation", "규정, 규제, 법규", "noun", "government regulation / safety regulations", "rule / law / directive / ordinance",
         "The environmental protection bureau enacted stringent regulations on factory chimney filters.", "환경보호국은 공장 굴뚝 필터에 관한 엄격한 규정을 제정했습니다."),
        ("legislation", "법률, 입법, 법률 제정", "noun", "pass legislation / propose legislation", "laws / statutes / acts",
         "Parliament passed landmark legislation capping pharmaceutical prescription prices.", "의회는 처방 의약품 가격의 상한을 정하는 획기적인 법률을 통과시켰습니다."),
        ("statute", "법령, 법규, 규칙", "noun", "statute of limitations / federal statute", "law / decree / enactment",
         "The statute of limitations for challenging commercial patent validity is seven years.", "상업용 특허권의 유효성에 이의를 제기할 수 있는 소멸시효 법령 기한은 7년입니다."),
        ("litigation", "소송, 소송 절차", "noun", "pending litigation / commercial litigation", "lawsuit / legal dispute / legal action",
         "The pharmaceutical rivals resolved their bitter patent litigation with a mutual licensing deal.", "제약업계의 라이벌 기업들은 상호 라이선스 계약을 통해 치열했던 특허 소송을 원만히 해결했습니다."),
        ("lawsuit", "소송, 고소", "noun", "file a lawsuit / settle a lawsuit", "suit / action / case / trial",
         "Former employees filed a class-action lawsuit alleging unpaid overtime compensation.", "퇴직한 직원들은 미지급 초과근무 수당을 청구하는 집단 소송을 제기했습니다."),
        ("counsel", "변호인단, 법률 고문; 조언하다", "noun", "legal counsel / general counsel", "lawyer / attorney / advisor",
         "The firm's chief legal counsel advised the board against signing without warranty terms.", "회사의 수석 법률 고문은 품질 보증 조항이 빠진 계약서에 서명하지 말 것을 이사회에 조언했습니다."),
        ("attorney", "변호사, 대리인", "noun", "patent attorney / power of attorney", "lawyer / counsel / advocate",
         "A registered patent attorney prepared the intricate technical diagrams for patent filing.", "공인 특허 변호사가 특허 출원을 위해 복잡한 기술 도면을 작성했습니다."),
        ("plaintiff", "원고 (소송을 제기한 사람)", "noun", "plaintiff's attorney / represent the plaintiff", "claimant / accuser / complainant",
         "The plaintiff presented clear forensic invoices proving unauthorized software usage.", "원고 측은 무단 소프트웨어 사용을 입증하는 명확한 포렌식 청구서를 증거로 제시했습니다."),
        ("defendant", "피고 (소송을 당한 사람)", "noun", "counsel for the defendant / corporate defendant", "accused / respondent",
         "The corporate defendant argued that the disputed marketing slogans were fair parody.", "피고 측 기업은 논란이 된 마케팅 슬로건이 공정한 패러디에 해당한다고 변론했습니다."),
        ("verdict", "평결, 판결", "noun", "reach a verdict / jury verdict", "decision / judgment / ruling",
         "The twelve-person jury delivered an unanimous verdict vindicating the manufacturer.", "12명의 배심원단은 제조사의 책임을 면제하는 만장일치 무죄 평결을 내렸습니다."),
        ("settlement", "합의, 화해, 정산", "noun", "reach an out-of-court settlement / confidential settlement", "agreement / resolution / accord",
         "Both parties signed a multimillion-dollar out-of-court settlement to avert a public trial.", "양측은 공개 재판을 피하기 위해 수백만 달러 규모의 법정 밖 합의서에 서명했습니다."),
        ("indemnify", "배상하다, 면책하다", "verb", "indemnify against losses / fully indemnify", "compensate / reimburse / protect",
         "The contractor agreed to indemnify the building owner against any construction injuries.", "시공업체는 모든 공사 중 안전사고 부상에 대해 건물주를 면책(배상)하기로 합의했습니다."),
        ("liability", "법적 책임, 부채", "noun", "admit liability / strict liability", "responsibility / culpability / legal obligation",
         "The enterprise accepted full legal liability for the unintended oil transport spillage.", "그 기업은 의도치 않은 원유 운송 유출 사고에 대해 모든 법적 책임을 전적으로 인정했습니다."),
        ("testimony", "증언, 증거", "noun", "expert testimony / witness testimony", "evidence / statement / deposition",
         "The structural engineer provided compelling expert testimony on structural steel rust.", "구조 엔지니어는 구조용 강철의 부식 메커니즘에 관한 설득력 있는 전문가 증언을 제공했습니다."),
        ("subpoena", "소환장; 소환하다", "noun", "issue a subpoena / comply with a subpoena", "summons / court order / writ",
         "Corporate officers complied with the federal subpoena by handing over deleted emails.", "회사 임원들은 삭제된 이메일을 제출함으로써 연방 법원의 소환장(자료 제출 명령)을 준수했습니다."),
        ("deposition", "증언 녹취, 선서 증언", "noun", "give a deposition / videotaped deposition", "testimony / sworn statement",
         "The chief financial officer spent five grueling hours answering questions in a deposition.", "최고재무책임자는 증언 녹취 절차에서 5시간 동안 지친 상태로 질문에 답변했습니다."),
        ("infringement", "침해, 위반", "noun", "patent infringement / copyright infringement", "violation / breach / transgression",
         "The electronics giant was awarded damages after proving deliberate patent infringement.", "그 전자 대기업은 고의적인 특허 침해를 입증한 후 손해배상 판결을 받아냈습니다."),
        ("injunction", "금지 명령", "noun", "preliminary injunction / grant an injunction", "court order / restraining order / ban",
         "The federal judge granted an immediate preliminary injunction halting sales of the copycat phone.", "연방 판사는 모방 스마트폰의 판매를 즉시 중단시키는 예비 금지 명령을 승인했습니다."),
        ("monopoly", "독점, 독점권", "noun", "antitrust monopoly / market monopoly", "exclusive control / corner",
         "Regulators investigated the railway merger to prevent the formation of an unfair monopoly.", "규제 당국은 불공정한 시장 독점 형성을 막기 위해 철도 합병 건을 면밀히 조사했습니다."),
        ("antitrust", "독점 금지의", "adj", "antitrust laws / antitrust violation", "anti-monopoly / competition policy",
         "The tech conglomerate faces severe antitrust scrutiny over its mobile app store rules.", "그 기술 대기업은 모바일 앱스토어 수수료 규정과 관련해 혹독한 반독점법 조사를 받고 있습니다."),
        ("unauthorized", "인가되지 않은, 무단횡단의", "adj", "unauthorized access / unauthorized disclosure", "unofficial / illicit / unlicensed",
         "Firewalls immediately block any unauthorized external attempts to log into the database.", "방화벽은 데이터베이스에 접속하려는 모든 외부의 무단 침입 시도를 즉각 차단합니다."),
        ("jurisdiction", "사법권, 관할 구역", "noun", "under the jurisdiction / legal jurisdiction", "authority / purview / command",
         "The commercial dispute falls under the maritime legal jurisdiction of the London courts.", "해당 상업 분쟁은 런던 법원의 해사법 관할 구역에 속합니다."),
        ("repeal", "폐지하다, 철회하다; 폐지", "verb", "repeal the statute / repeal regulations", "revoke / annul / overturn",
         "Lawmakers voted to repeal the archaic import licensing tariff on raw wool textiles.", "의원들은 생양모 직물에 부과되던 낡은 수입 허가 관세를 폐지하기로 가결했습니다."),
        ("enact", "제정하다, 법제화하다", "verb", "enact safety measures / enact legislation", "pass / establish / institute",
         "The state legislature moved swiftly to enact emergency flood insurance safeguards.", "주 의회는 긴급 홍수 보험 안전장치를 법제화(제정)하기 위해 신속하게 움직였습니다."),
        ("revoke", "취소하다, 폐지하다, 철회하다", "verb", "revoke a license / revoke privileges", "cancel / annul / rescind",
         "The licensing board voted to revoke the doctor's practice license following malpractice.", "의료 면허 위원회는 의료 과실 사고 이후 해당 의사의 진료 면허를 취소하기로 의결했습니다."),
        ("arbitration", "중재", "noun", "commercial arbitration / binding arbitration", "mediation / adjudication",
         "Submitting disputes to binding commercial arbitration avoids years of costly public trials.", "분쟁을 구속력 있는 상업 중재에 회부하면 수년간 소요되는 막대한 공개 재판 비용을 절약할 수 있습니다."),
        ("mediator", "중재자, 조정관", "noun", "neutral mediator / certified mediator", "arbitrator / conciliator / go-between",
         "A certified mediator helped the disputing partners divide company assets equitably.", "공인 조정관은 분쟁 중인 동업자들의 회사 자산을 공평하게 분할할 수 있도록 도왔습니다."),
        ("binding", "구속력이 있는", "adj", "binding agreement / legally binding", "enforceable / obligatory / mandatory",
         "Both corporate boards signed a legally binding memorandum to finalize the purchase.", "양사 이사회는 최종 인수 완료를 위해 법적 구속력이 있는 각서에 서명했습니다."),
        ("covenant", "서약, 계약 조항", "noun", "restrictive covenant / non-compete covenant", "pledge / undertaking / promise",
         "The employment contract includes a two-year non-compete restrictive covenant.", "고용 계약서에는 2년간의 경업 금지(경쟁사 취업 제한) 서약 조항이 포함되어 있습니다."),
        ("stipulation", "규정, 조건, 약정", "noun", "contractual stipulation / key stipulation", "requirement / condition / provision",
         "Strict on-time delivery was a non-negotiable stipulation of the government procurement contract.", "엄격한 적시 납품은 정부 조달 계약의 절대 타협할 수 없는 필수 규정 조건이었습니다."),
        ("null and void", "무효의", "phrase", "declared null and void / render null and void", "invalid / canceled / inoperative",
         "Failure to provide genuine signatures renders the entire partnership accord null and void.", "진본 자필 서명을 제공하지 못할 경우 파트너십 협약 전체가 원천 무효가 됩니다."),
        ("indemnity", "보상, 배상, 면책", "noun", "indemnity insurance / seek indemnity", "compensation / protection / guarantee",
         "Subcontractors must maintain two million dollars in general commercial indemnity coverage.", "하도급업체는 200만 달러 상당의 일반 상업용 배상 책임 보험을 의무적으로 유지해야 합니다."),
        ("clause", "조항, 조문", "noun", "arbitration clause / penalty clause", "provision / section / article",
         "Legal counsel recommended adding an escape clause in case raw material prices spike.", "법률 고문은 원자재 가격이 급등할 경우를 대비해 면책(계약 해제) 조항을 추가할 것을 권고했습니다.")
    ]),

    # DAY 20: 의료, 건강 및 제약 산업 (34 words)
    20: ("의료/건강", "800필수", [
        ("prescription", "처방, 처방약", "noun", "fill a prescription / doctor's prescription", "recipe / medicine order",
         "You can have your allergy medicine prescription filled at any licensed local pharmacy.", "지역의 공인된 약국 어디서나 알레르기 약 처방전을 조제받으실 수 있습니다."),
        ("pharmaceutical", "제약의, 약학의; 제약 회사", "adj", "pharmaceutical industry / pharmaceutical giant", "medicinal / drug-related",
         "The pharmaceutical enterprise invested thirty million dollars into cardiovascular research.", "그 제약 기업은 심혈관 질환 연구에 3,000만 달러를 투자했습니다."),
        ("clinical", "임상의, 치료의", "adj", "clinical trials / clinical evidence", "medical / practical / experimental",
         "Phase three clinical trials demonstrated that the vaccine induced robust antibody titers.", "3상 임상 시험 결과 해당 백신이 강력한 항체가를 형성하는 것으로 입증되었습니다."),
        ("efficacy", "효능, 유효성", "noun", "proven efficacy / drug efficacy", "effectiveness / potency / success",
         "Regulatory agencies demand rigorous double-blind trials before certifying drug efficacy.", "규제 당국은 약품의 효능을 공인하기 전에 엄격한 이중 맹검 시험을 요구합니다."),
        ("dosage", "복용량, 투약량", "noun", "recommended dosage / exceed the dosage", "dose / portion / administration",
         "Patients must not exceed the recommended daily dosage stated on the medication carton.", "환자는 약품 포장 상자에 기재된 하루 권장 복용량을 절대 초과해서는 안 됩니다."),
        ("symptom", "증상, 징후", "noun", "alleviate symptoms / flu symptoms", "indication / sign / manifestation",
         "Consult a certified physician immediately if respiratory symptoms persist past three days.", "호흡기 증상이 사흘 이상 지속되면 공인된 의사의 진료를 즉시 받으십시오."),
        ("alleviate", "완화하다, 경감하다", "verb", "alleviate pain / alleviate symptoms", "ease / relieve / lessen",
         "The new non-drowsy antihistamine proved remarkably effective at alleviating nasal allergies.", "새로 나온 졸림 없는 항히스타민제는 비염 알레르기 완화에 매우 효과적인 것으로 나타났습니다."),
        ("physician", "내과의사, 의사", "noun", "licensed physician / attending physician", "doctor / practitioner / specialist",
         "The attending physician reviewed the patient's radiology scans before performing surgery.", "담당 주치의는 수술을 집도하기 전에 환자의 방사선 영상 판독 자료를 검토했습니다."),
        ("outpatient", "외래 환자; 외래의", "noun", "outpatient clinic / outpatient surgery", "ambulatory patient / day patient",
         "Minimally invasive arthroscopic procedures can now be performed safely on an outpatient basis.", "최소 침습 관절경 시술은 이제 외래 환자 기준으로 당일 안전하게 시행될 수 있습니다."),
        ("inpatient", "입원 환자", "noun", "inpatient care / inpatient facility", "hospitalized patient",
         "The newly dedicated cardiovascular tower expanded inpatient bed capacity by thirty percent.", "새로 준공된 심혈관 센터 병동은 입원 환자 병상 수용 능력을 30% 확충했습니다."),
        ("chronic", "만성의, 고질적인", "adj", "chronic condition / chronic pain", "persistent / long-term / recurring",
         "Telemedicine apps enable rural residents to manage chronic diabetes with remote doctors.", "원격의료 앱을 통해 외곽 지역 주민들은 원격 의사와 함께 고질적인 만성 당뇨를 관리할 수 있습니다."),
        ("acute", "급성의, 극심한", "adj", "acute pain / acute shortage", "severe / sharp / intense",
         "Patients experiencing acute chest pressure should call emergency dispatchers without delay.", "극심한 급성 흉통을 겪는 환자는 지체 없이 응급 구조대에 연락해야 합니다."),
        ("diagnosis", "진단", "noun", "early diagnosis / confirm a diagnosis", "identification / assessment / detection",
         "Advanced MRI magnetic imaging aids physicians in making an accurate neurological diagnosis.", "첨단 MRI 자기공명영상은 의사들이 정확한 신경학적 진단을 내릴 수 있도록 돕습니다."),
        ("prognosis", "예후 (치료 전망)", "noun", "favorable prognosis / poor prognosis", "forecast / outlook / prediction",
         "Because the tumor was excised at an early stage, the oncologist gave an excellent prognosis.", "종양이 초기 단계에 절제되었기 때문에 종양내과 전문의는 매우 좋은 치료 예후를 전망했습니다."),
        ("hygiene", "위생, 청결", "noun", "personal hygiene / dental hygiene", "cleanliness / sanitation / health",
         "Hand-washing sanitizer stations were mounted on every floor to promote hospital hygiene.", "병원 내 위생 청결을 도모하기 위해 전 층에 손 소독 거치대가 설치되었습니다."),
        ("sanitation", "공중위생, 위생 시설", "noun", "food sanitation / public sanitation", "cleanliness / cleanliness systems",
         "Health inspectors award sanitation excellence certificates to commercial resort kitchens.", "보건 위생 검사관들은 청결 기준을 통과한 상업용 리조트 주방에 우수 위생 인증서를 수여합니다."),
        ("sterilize", "살균하다, 소독하다", "verb", "sterilize instruments / thoroughly sterilize", "disinfect / sanitize / cleanse",
         "Surgical autoclaves use pressurized superheated steam to sterilize scalpels and forceps.", "수술용 고압 멸균기는 메스와 겸자를 완벽히 소독(살균)하기 위해 고압 과열 증기를 사용합니다."),
        ("contagious", "전염성의, 감염성의", "adj", "highly contagious / contagious disease", "infectious / transmissible / catching",
         "Children diagnosed with contagious viral measles must isolate at home for ten days.", "전염성 홍역 진단을 받은 아동은 10일간 가정에서 격리 치료를 받아야 합니다."),
        ("vaccine", "백신", "noun", "administer a vaccine / seasonal flu vaccine", "immunization / inoculation / jab",
         "Public health clinics administer complimentary seasonal flu vaccines to senior citizens.", "보건소는 노인분들을 대상으로 무료 계절 독감 백신을 접종해 드립니다."),
        ("wellness", "웰빙, 건강 관리", "noun", "corporate wellness / wellness retreat", "healthiness / well-being / fitness",
         "Employees earn insurance premium discounts by enrolling in the annual corporate wellness plan.", "직원들은 연례 사내 건강 웰빙 프로그램에 등록함으로써 보험료 할인 혜택을 받습니다."),
        ("checkup", "건강검진, 점검", "noun", "annual checkup / routine medical checkup", "examination / physical / inspection",
         "Corporate benefits cover hundred percent of the expenses for a comprehensive annual checkup.", "회사 복리후생 제도는 종합 연례 건강검진 비용을 100% 전액 지원합니다."),
        ("pediatric", "소아과의", "adj", "pediatric clinic / pediatric care", "children's medicine",
         "The hospital opened a specialized pediatric emergency ward staffed with child specialists.", "병원은 소아 전문의들로 구성된 소아과 전용 응급실을 새로 개설했습니다."),
        ("orthopedic", "정형외과의", "adj", "orthopedic surgeon / orthopedic shoes", "musculoskeletal",
         "The orthopedic surgeon recommended six weeks of targeted physical therapy for the knee.", "정형외과 수술 전문의는 무릎 관절에 대해 6주간의 집중 물리치료를 권고했습니다."),
        ("radiology", "방사선과, 영상의학과", "noun", "radiology department / diagnostic radiology", "medical imaging / X-ray",
         "Technicians in the radiology wing upload digital computed tomography scans in real time.", "영상의학과(방사선과) 병동 기술자들은 디지털 CT 스캔 이미지를 실시간으로 전산망에 업로드합니다."),
        ("anesthesia", "마취, 마취법", "noun", "general anesthesia / local anesthesia", "narcosis / numbing",
         "The anesthesiologist monitored heart rhythm continuously while the patient was under general anesthesia.", "마취과 전문의는 환자가 전신마취 상태에 있는 동안 심장 박동 리듬을 지속적으로 모니터링했습니다."),
        ("rehabilitation", "재활, 회복", "noun", "physical rehabilitation / cardiac rehabilitation", "recovery / therapy / restorative care",
         "After hip replacement surgery, patients enter an intensive physical rehabilitation program.", "고관절 치환 수술을 마친 환자들은 집중적인 신체 재활 치료 프로그램에 들어갑니다."),
        ("therapy", "치료, 요법", "noun", "physical therapy / occupational therapy", "treatment / counseling / healing",
         "Regular physical therapy restored full shoulder flexibility within two months.", "규칙적인 물리치료 덕분에 두 달 만에 어깨의 완전한 유연성을 회복할 수 있었습니다."),
        ("medication", "약, 약물 치료", "noun", "prescribe medication / take medication", "drugs / medicine / pharmaceuticals",
         "Always consult your attending pharmacist regarding possible interactions with existing medication.", "기존에 복용 중인 약물과의 상호작용 가능성에 대해서는 항상 담당 약사와 상의하십시오."),
        ("over-the-counter", "처방전 없이 살 수 있는 (일반의약품의)", "adj", "over-the-counter drugs / OTC medication", "non-prescription / retail medicine",
         "Mild headache analgesics are available over-the-counter at most neighborhood grocery stores.", "가벼운 두통 진통제는 대부분의 동네 식료품점에서 처방전 없이 일반의약품으로 구매 가능합니다."),
        ("side effect", "부작용", "noun", "adverse side effects / minor side effect", "secondary effect / reaction / complication",
         "Common side effects of the tablet include mild drowsiness and dry throat irritation.", "그 정제의 흔한 부작용으로는 가벼운 졸림 증상과 목 안의 건조한 자극감이 있습니다."),
        ("vital", "필수적인, 생명의, 극히 중대한", "adj", "vital signs / play a vital role", "essential / crucial / indispensable",
         "Nurses record patient vital signs such as blood pressure and pulse rate every two hours.", "간호사들은 2시간마다 혈압과 맥박 등 환자의 생체 활력 징후(바이탈)를 기록합니다."),
        ("regimen", "식이요법, 치료 계획, 양생법", "noun", "treatment regimen / exercise regimen", "routine / schedule / program",
         "Adhering strictly to the prescribed dietary regimen helped reduce cholesterol counts.", "처방된 식이요법 양생 계획을 엄격히 준수한 덕분에 콜레스테롤 수치를 낮출 수 있었습니다."),
        ("sanitary", "위생적인, 깨끗한", "adj", "sanitary conditions / sanitary inspection", "hygienic / clean / sterile",
         "Operating theaters must be maintained under meticulously sanitary sterile conditions.", "수술실은 멸균된 꼼꼼한 위생 환경 속에서 엄격히 유지 관리되어야 합니다."),
        ("quarantine", "격리, 검역; 격리하다", "noun", "place in quarantine / quarantine inspection", "isolation / confinement",
         "Imported exotic livestock must spend thirty days in veterinary quarantine at the border.", "수입된 외래 가축은 국경에서 30일간의 수의학적 검역 격리 기간을 거쳐야 합니다.")
    ])
}

print("Part 2 loaded successfully (Days 11 to 20)")
