#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TOEIC 1000 Vocab Part 3: Days 21 to 30 (~340 words)
Completes the full 1,000 top-frequency TOEIC vocabulary curriculum!
"""

DAYS_21_TO_30 = {
    # DAY 21: IT, 소프트웨어 및 정보보안 (34 words)
    21: ("IT/보안", "800필수", [
        ("infrastructure", "사회 기반 시설, IT 인프라", "noun", "IT infrastructure / network infrastructure", "foundation / framework / systems",
         "The bank migrated its entire database infrastructure onto a secure cloud cluster.", "은행은 전체 데이터베이스 인프라를 안전한 클라우드 클러스터로 마이그레이션했습니다."),
        ("authentication", "인증, 신원 확인", "noun", "two-factor authentication / biometric authentication", "verification / validation / identification",
         "Enabling two-factor authentication drastically diminishes unauthorized login attempts.", "이중 인증(2FA)을 활성화하면 무단 로그인 시도를 대폭 줄일 수 있습니다."),
        ("vulnerability", "취약점, 취약성", "noun", "security vulnerability / patch a vulnerability", "weakness / flaw / susceptibility",
         "Software developers issued an emergency hotfix to patch a zero-day security vulnerability.", "소프트웨어 개발자들은 제로데이 보안 취약점을 패치하기 위해 긴급 핫픽스를 배포했습니다."),
        ("encryption", "암호화", "noun", "end-to-end encryption / data encryption", "encoding / ciphering / scrambling",
         "Messaging apps utilize 256-bit encryption to safeguard user communication privacy.", "메신저 앱은 사용자 대화 프라이버시를 보호하기 위해 256비트 암호화를 사용합니다."),
        ("compatibility", "호환성", "noun", "backward compatibility / system compatibility", "interoperability / consistency / match",
         "The new operating system update ensures seamless compatibility with legacy peripherals.", "새로운 운영체제 업데이트는 기존의 구형 주변 기기들과의 매끄러운 호환성을 보장합니다."),
        ("configuration", "환경 설정, 구성", "noun", "default configuration / system configuration", "setup / arrangement / structure",
         "Administrators altered the server configuration to manage sudden traffic surges.", "관리자들은 갑작스러운 트래픽 폭증을 관리하기 위해 서버 설정을 변경했습니다."),
        ("bandwidth", "대역폭, 데이터 전송 용량", "noun", "high bandwidth / consume bandwidth", "data capacity / network speed",
         "Streaming video conferences without lag requires reliable high-speed network bandwidth.", "지연 없이 화상 회의를 스트리밍하려면 안정적인 고속 네트워크 대역폭이 필요합니다."),
        ("firewall", "방화벽", "noun", "configure a firewall / enterprise firewall", "security barrier / network shield",
         "The enterprise firewall automatically isolates IP addresses that exhibit malicious probes.", "기업용 방화벽은 악의적인 탐색 행위를 보이는 IP 주소를 자동으로 격리합니다."),
        ("malware", "악성 소프트웨어, 멀웨어", "noun", "detect malware / remove malware", "spyware / malicious code / virus",
         "Endpoint security scanners run daily scans to detect and eradicate intrusive malware.", "단말 보안 검사기는 침투한 악성코드를 탐지하고 박멸하기 위해 매일 검사를 수행합니다."),
        ("downtime", "가동 중단 시간, 시스템 정지", "noun", "unplanned downtime / minimize downtime", "outage / idle time / stoppage",
         "Routine server maintenance is performed during early dawn hours to minimize business downtime.", "업무 중단 시간(다운타임)을 최소화하기 위해 정기 서버 점검은 이른 새벽 시간에 수행됩니다."),
        ("deployment", "배포, 배치", "noun", "software deployment / rapid deployment", "rollout / release / implementation",
         "Continuous automated deployment pipelines allow developers to push code updates daily.", "지속적 자동 배포 파이프라인 덕분에 개발자들은 매일 코드 업데이트를 배포할 수 있습니다."),
        ("proprietary", "독점적인, 등록 상표의", "adj", "proprietary software / proprietary algorithm", "patented / exclusive / private",
         "The firm guards its proprietary recommendation algorithm as a critical trade secret.", "그 회사는 자사의 독점 추천 알고리즘을 핵심 영업 비밀로 엄격히 보호합니다."),
        ("cloud", "클라우드 컴퓨팅; 구름", "noun", "cloud storage / cloud migration", "remote servers / online network",
         "Adopting cloud computing reduced capital expenditures on physical server racks.", "클라우드 컴퓨팅을 도입하여 물리적 서버 랙에 투입되던 자본 지출을 절감했습니다."),
        ("interface", "인터페이스, 접점", "noun", "user interface / intuitive interface", "connection / UX / UI",
         "The modern graphic user interface allows non-technical employees to query sales data.", "직관적인 그래픽 사용자 인터페이스(UI) 덕분에 비개발자 직원들도 매출 데이터를 쉽게 조회할 수 있습니다."),
        ("scalable", "확장 가능한", "adj", "scalable architecture / highly scalable", "expandable / flexible / adaptable",
         "Microservices architecture provides a scalable backend that grows with customer volume.", "마이크로서비스 아키텍처는 고객 수 증가에 맞춰 유연하게 확장 가능한 백엔드를 제공합니다."),
        ("latency", "지연 시간, 대기 시간", "noun", "low latency / ultra-low latency", "delay / lag / waiting time",
         "Financial trading algorithms rely on fiber connections with ultra-low milliseconds latency.", "금융 트레이딩 알고리즘은 밀리초 단위의 극초저지연 광케이블 회선에 의존합니다."),
        ("redundancy", "이중화, 중복성, 잉여", "noun", "system redundancy / build redundancy", "backup / duplication / safeguard",
         "Dual power generators provide essential hardware redundancy against municipal blackouts.", "이중 발전기는 시 전력 정전 사태에 대비해 필수적인 하드웨어 이중화 장치를 제공합니다."),
        ("troubleshoot", "문제점을 해결하다", "verb", "troubleshoot network issues / remote troubleshooting", "diagnose / debug / resolve",
         "The IT helpdesk technician connected via secure screen-sharing to troubleshoot the bug.", "IT 헬프데스크 기사는 화면 공유를 통해 보안 접속하여 버그를 해결(트러블슈팅)했습니다."),
        ("protocol", "통신 규약, 프로토콜, 행동 수칙", "noun", "communication protocol / standard protocol", "procedure / standard / rules",
         "HTTPS has become the universally mandated security transmission protocol for websites.", "HTTPS는 웹사이트의 보편적인 필수 보안 전송 프로토콜로 자리 잡았습니다."),
        ("repository", "저장소, 리포지토리", "noun", "code repository / central repository", "archive / storage / database",
         "Engineers push daily bug fixes and feature branches to the shared Git code repository.", "엔지니어들은 공유 Git 코드 저장소에 매일 버그 수정과 기능 브랜치를 푸시합니다."),
        ("automation", "자동화", "noun", "workflow automation / process automation", "mechanization / robotics",
         "Implementing workflow automation software reduced repetitive manual entry errors by 90%.", "워크플로우 자동화 소프트웨어를 도입하여 반복적인 수작업 입력 오류를 90% 줄였습니다."),
        ("telecommuting", "재택근무, 원격근무", "noun", "encourage telecommuting / telecommuting policy", "remote work / working from home",
         "Cloud-based collaboration platforms make productive telecommuting possible for all teams.", "클라우드 협업 플랫폼 덕분에 모든 팀이 생산적인 원격 재택근무를 수행할 수 있습니다."),
        ("phishing", "피싱 (금융 사기)", "noun", "phishing attack / phishing simulation", "online scam / fraudulent email",
         "Employees receive simulated phishing emails every month to test cybersecurity vigilance.", "직원들은 사이버 보안 경각심을 점검하기 위해 매월 모의 피싱 훈련 이메일을 받습니다."),
        ("server", "서버 컴퓨터", "noun", "dedicated server / crash the server", "host machine / mainframe",
         "Heavy holiday e-commerce traffic threatened to overwhelm the primary retail web server.", "연말 연휴의 막대한 전자상거래 트래픽으로 인해 주력 소매 웹 서버가 과부하에 걸릴 뻔했습니다."),
        ("credential", "자격 증명서, 로그인 정보", "noun", "login credentials / verify credentials", "passwords / tokens / qualifications",
         "Never share your administrative login credentials via unsecured chat channels.", "보안되지 않은 채팅 채널을 통해 관리자 로그인 자격 증명(비밀번호)을 공유하지 마십시오."),
        ("patch", "패치 (수정 프로그램); 덧대다", "noun", "apply a security patch / software patch", "hotfix / update / repair",
         "System engineers worked over the weekend to apply the critical security kernel patch.", "시스템 엔지니어들은 주말 동안 핵심 보안 커널 패치를 적용하기 위해 근무했습니다."),
        ("obsolete", "더 이상 쓸모없는, 구식의", "adj", "rendered obsolete / obsolete hardware", "outdated / superseded / defunct",
         "Faster solid-state flash memory made magnetic tape storage largely obsolete.", "더 빠른 솔리드 스테이트(SSD) 플래시 메모리로 인해 자기 테이프 저장 장치는 거의 구식으로 전락했습니다."),
        ("restore", "복구하다, 복원하다", "verb", "restore backups / restore connectivity", "recover / reinstate / fix",
         "Database administrators were able to restore customer records from overnight snapshots.", "데이터베이스 관리자는 야간 백업 스냅샷을 통해 고객 기록을 완벽히 복원할 수 있었습니다."),
        ("breach", "위반, 침해, 침투; 위반하다", "noun", "data breach / security breach", "infringement / violation / leak",
         "The cybersecurity firm alerted consumers immediately following the unauthorized database breach.", "사이버 보안 업체는 무단 데이터베이스 침투 유출 사고 직후 소비자들에게 즉각 경고했습니다."),
        ("interoperable", "상호 운용 가능한", "adj", "interoperable software / highly interoperable", "compatible / integrated",
         "Standardized API design allows disparate healthcare databases to remain fully interoperable.", "표준화된 API 설계 덕분에 이종 의료 데이터베이스들이 완벽하게 상호 운용될 수 있습니다."),
        ("benchmark", "벤치마크, 성능 지표; 성능 평가하다", "noun", "performance benchmark / run a benchmark", "standard / test / evaluation",
         "The flagship gaming processor set record-breaking scores in multi-core speed benchmarks.", "그 플래그십 게이밍 프로세서는 멀티코어 속도 성능 벤치마크에서 역대 최고 점수를 기록했습니다."),
        ("bandwidth", "대역폭, 처리 용량", "noun", "lack bandwidth / allocate bandwidth", "mental capacity / data throughput",
         "Due to the upcoming product launch, our design team simply lacks bandwidth for extra work.", "다가오는 제품 출시 행사로 인해 저희 디자인 팀은 추가 업무를 감당할 처리 용량(여력)이 없습니다."),
        ("algorithm", "알고리즘", "noun", "search algorithm / predictive algorithm", "formula / calculation / rule set",
         "Engineers refined the delivery routing algorithm to shave miles off daily truck dispatches.", "엔지니어들은 일일 배송 트럭 운행 거리를 단축하기 위해 배차 경로 알고리즘을 개선했습니다."),
        ("upgrade", "업그레이드, 품질 향상; 향상시키다", "verb", "upgrade the system / hardware upgrade", "improve / enhance / modernize",
         "The headquarters opted to upgrade all desktop workstations to high-performance workstations.", "본사는 모든 데스크톱 워크스테이션을 고성능 워크스테이션으로 업그레이드하기로 결정했습니다.")
    ]),

    # DAY 22: R&D, 혁신 및 지식재산권 (34 words)
    22: ("R&D/혁신", "850+킬러", [
        ("prototype", "시제품, 원형", "noun", "build a prototype / working prototype", "mock-up / model / test unit",
         "Engineers test-drove the electric SUV prototype in extreme arctic weather chambers.", "엔지니어들은 혹독한 극지방 기후 챔버에서 전기 SUV 시제품의 시험 주행을 진행했습니다."),
        ("patent", "특허, 특허권; 특허를 받다", "noun", "patent application / grant a patent", "copyright / intellectual property / license",
         "The university laboratory submitted three provisional patent applications for solar dyes.", "대학 연구소는 태양광 염료와 관련하여 3건의 임시 특허 출원서를 제출했습니다."),
        ("innovative", "혁신적인", "adj", "innovative design / innovative approach", "groundbreaking / novel / pioneering",
         "The startup won international accolades for its innovative water-harvesting mesh panels.", "그 스타트업은 혁신적인 대기 수분 포집 메시 패널로 국제적인 찬사를 받았습니다."),
        ("breakthrough", "비약적 발전, 돌파구", "noun", "major breakthrough / scientific breakthrough", "discovery / leap / milestone",
         "Researchers celebrated a major scientific breakthrough in room-temperature superconductors.", "연구원들은 상온 초전도체 분야에서 중대한 과학적 돌파구(비약적 발전)를 이뤄내 환호했습니다."),
        ("feasibility", "실현 가능성, 타당성", "noun", "feasibility study / economic feasibility", "viability / practicability / workability",
         "The civil engineering consortium conducted a thorough environmental feasibility study.", "토목공학 컨소시엄은 철저한 환경 실현 가능성(타당성) 조사를 수행했습니다."),
        ("state-of-the-art", "최첨단의, 최신식의", "adj", "state-of-the-art laboratory / state-of-the-art facility", "cutting-edge / modern / advanced",
         "The biotechnology campus is equipped with state-of-the-art gene-sequencing machinery.", "그 생명공학 캠퍼스는 최첨단 유전자 염기서열 분석 장비를 완비하고 있습니다."),
        ("cutting-edge", "최첨단의", "adj", "cutting-edge technology / cutting-edge research", "advanced / pioneering / forefront",
         "Our enterprise invests twenty percent of gross revenues into cutting-edge optical research.", "저희 기업은 총매출의 20%를 최첨단 광학 연구에 적극 투자합니다."),
        ("intellectual property", "지식재산권 (IP)", "noun", "protect intellectual property / IP rights", "copyrights / patents / trademarks",
         "Venture investors scrutinize whether startups legally protect their intellectual property.", "벤처 투자자들은 스타트업이 자사의 지식재산권(IP)을 법적으로 잘 보호하고 있는지 면밀히 조사합니다."),
        ("trademark", "등록 상표; 상표를 등록하다", "noun", "registered trademark / trademark infringement", "brand / logo / hallmark",
         "The distinctive cursive company logo has been a registered federal trademark since 1950.", "그 독특한 필기체 회사 로고는 1950년 이래로 연방 정부에 등록된 등록 상표입니다."),
        ("infringement", "침해, 위반", "noun", "patent infringement / copyright infringement", "violation / breach / trespassing",
         "The electronics rivals agreed to settle their bilateral patent infringement disputes.", "전자 업계의 경쟁사들은 상호 간의 특허 침해 분쟁을 원만히 합의하기로 결정했습니다."),
        ("experiment", "실험; 실험하다", "noun", "conduct an experiment / laboratory experiment", "trial / test / research",
         "Clinical researchers conducted a double-blind experiment to test the drug's potency.", "임상 연구원들은 약물의 효능을 검증하기 위해 이중 맹검 실험을 실시했습니다."),
        ("hypothesis", "가설, 가정", "noun", "test a hypothesis / formulate a hypothesis", "theory / premise / assumption",
         "Laboratory data from the field trial refuted the team's initial chemical hypothesis.", "현장 실증 시험에서 나온 실험실 데이터는 연구팀의 초기 화학 가설을 반박했습니다."),
        ("empirical", "경험적인, 실증적인", "adj", "empirical evidence / empirical data", "observed / factual / experimental",
         "The academic paper presents compelling empirical evidence supporting the new theorem.", "그 학술 논문은 새로운 정리를 뒷받침하는 설득력 있는 실증적 증거를 제시합니다."),
        ("commercialize", "상용화하다, 상품화하다", "verb", "commercialize technology / successfully commercialize", "market / monetize / launch",
         "The venture incubator specializes in helping university labs commercialize discoveries.", "그 벤처 인큐베이터는 대학 연구소들이 과학적 발견을 성공적으로 상용화하도록 돕는 데 특화되어 있습니다."),
        ("rigorous", "엄격한, 철저한", "adj", "rigorous testing / rigorous standards", "stringent / meticulous / exacting",
         "Automotive components must pass rigorous crash testing before securing safety badges.", "자동차 부품은 안전 인증 마크를 획득하기 전에 엄격한 충돌 테스트를 통과해야 합니다."),
        ("pioneer", "개척하다; 개척자, 선구자", "verb", "pioneer new methods / pioneer research", "trailblaze / lead / spearhead",
         "The Japanese corporation pioneered the mass production of consumer hybrid vehicles.", "그 일본 기업은 일반 소비자용 하이브리드 자동차의 대량 양산 기술을 최초로 개척했습니다."),
        ("benchmark", "벤치마크, 기준점; 기준점을 삼다", "noun", "industry benchmark / gold benchmark", "standard / yardstick / criterion",
         "The engine's fuel efficiency became the gold benchmark against which competitors were measured.", "그 엔진의 뛰어난 연비는 경쟁사들이 측정 평가되는 황금 기준점(벤치마크)이 되었습니다."),
        ("revolutionize", "대변혁을 일으키다", "verb", "revolutionize the industry / completely revolutionize", "transform / overhaul / innovate",
         "Advances in cloud-based genomics promise to revolutionize personalized medical oncology.", "클라우드 기반 유전체학의 발전은 맞춤형 암 치료 의학에 대변혁을 일으킬 것으로 기대됩니다."),
        ("specification", "명세서, 세부 사양, 제원", "noun", "technical specifications / meet specifications", "specs / details / parameters",
         "Machinists crafted the aircraft titanium bolts to exact aerodynamic specifications.", "기계공들은 항공기용 티타늄 볼트를 정확한 공기역학적 세부 사양(스펙)에 맞추어 가공했습니다."),
        ("criterion", "기준, 평가 척도", "noun", "meet the criteria / selection criteria", "standard / test / benchmark",
         "Energy conservation was the paramount criterion used in judging the design submissions.", "에너지 절약성은 디자인 출품작들을 심사하는 데 사용된 가장 중요한 평가 기준이었습니다."),
        ("obsolete", "구식의, 쇠퇴한", "adj", "make obsolete / completely obsolete", "outdated / antique / disused",
         "Smartphones with touch screens made physical keyboard handsets practically obsolete.", "터치스크린 스마트폰의 등장은 물리 키보드 휴대폰을 사실상 구식으로 만들었습니다."),
        ("proprietary", "독점적인, 소유주의", "adj", "proprietary formula / proprietary technology", "patented / copyrighted / private",
         "The soda manufacturer keeps its proprietary recipe locked inside an underground vault.", "그 탄산음료 제조사는 자사의 독점 제조법을 지하 금고 안에 엄격히 보관하고 있습니다."),
        ("trial", "시험, 시도, 재판", "noun", "clinical trials / trial period", "experiment / test run / audition",
         "Subscribers enjoy a thirty-day free trial period before their credit cards are charged.", "구독 고객은 신용카드로 요금이 청구되기 전에 30일간의 무료 체험 시험 기간을 누릴 수 있습니다."),
        ("collaborative", "협력적인, 공동의", "adj", "collaborative research / collaborative project", "joint / cooperative / collective",
         "The telescope project is a collaborative research venture between eight sovereign nations.", "그 거대 망원경 프로젝트는 8개 주권 국가 간의 공동 연구 협력 사업입니다."),
        ("simulation", "모의실험, 시뮬레이션", "noun", "computer simulation / flight simulation", "modeling / trial run / mock-up",
         "Aerospace engineers ran computer flight simulations to analyze wing stress during storms.", "항공우주 엔지니어들은 폭풍우 중 날개 응력을 분석하기 위해 컴퓨터 비행 시뮬레이션을 가동했습니다."),
        ("validate", "입증하다, 유효하게 하다", "verb", "validate the results / scientifically validate", "confirm / verify / substantiate",
         "Third-party laboratory independent testing helped validate the battery's lifespan claims.", "제3자 독립 시험기관의 검증 테스트는 배터리 수명 주장에 대한 신뢰성을 입증하는 데 기여했습니다."),
        ("modification", "수정, 변경", "noun", "minor modifications / design modification", "adjustment / alteration / tweak",
         "A few minor aerodynamic modifications reduced cockpit cabin wind resistance by 5%.", "몇 가지 경미한 공기역학적 수정(설계 변경)을 통해 조종석 캐빈의 풍절음을 5% 줄였습니다."),
        ("telecommunications", "원거리 통신, 전기통신", "noun", "telecommunications network / telecom industry", "telecoms / data transmission",
         "Major investments in fifth-generation mobile telecommunications boosted download speeds.", "5세대(5G) 이동통신망에 대한 과감한 투자를 통해 다운로드 속도를 비약적으로 끌어올렸습니다."),
        ("intellect", "지적 능력, 지성", "noun", "towering intellect / business intellect", "brainpower / mind / intelligence",
         "The research institute recruits the sharpest intellects from leading universities.", "그 연구소는 세계 유수 대학에서 가장 뛰어난 지적 인재들을 채용하고 있습니다."),
        ("synthetic", "합성의, 인조의", "adj", "synthetic materials / synthetic polymers", "artificial / man-made / manufactured",
         "The laboratory synthesized an ultra-durable synthetic rubber compound for space suits.", "그 연구실은 우주복에 사용할 극도로 내구성 높은 인조 합성 고무 화합물을 합성했습니다."),
        ("scalable", "확장 가능한, 규모 변경이 가능한", "adj", "scalable manufacturing / scalable solution", "adaptable / modular / flexible",
         "Biochemists designed a scalable synthesis process that easily transitions into mass production.", "생화학자들은 대량 생산으로 쉽게 전환할 수 있는 확장 가능한 화학 합성 공정을 설계했습니다."),
        ("pilot", "시험적인; 조종사; 시범 운영하다", "adj", "pilot program / pilot project", "experimental / test / trial",
         "The regional hospital system launched a six-month pilot program using AI triage bots.", "지역 병원 네트워크는 AI 분류 봇을 활용한 6개월간의 시범 시험 프로그램(파일럿)을 출범시켰습니다."),
        ("replicate", "복제하다, 그대로 재현하다", "verb", "replicate results / accurately replicate", "duplicate / copy / recreate",
         "Independent scientists were unable to replicate the room-temperature fusion results.", "독립된 다른 과학자들은 그 상온 핵융합 실험 결과를 그대로 재현할 수 없었습니다."),
        ("paradigm", "패러다임, 전형적인 사고 체계", "noun", "paradigm shift / new paradigm", "model / archetype / framework",
         "Electric autonomous transport represents a fundamental paradigm shift for automakers.", "전기 자율주행 교통수단은 기존 완성차 제조업체들에게 근본적인 패러다임의 대전환을 의미합니다.")
    ]),

    # DAY 23: 미디어, 마케팅 및 출판 (34 words)
    23: ("미디어/홍보", "800필수", [
        ("press release", "보도자료", "noun", "issue a press release / official press release", "news release / media statement",
         "The corporate communications team issued a press release announcing the merger.", "기업 홍보팀은 기업 합병 소식을 공식 발표하는 언론 보도자료를 배포했습니다."),
        ("coverage", "보도, 취재, 보장 범위", "noun", "media coverage / extensive coverage", "reporting / journalism / press",
         "The eco-friendly electric truck launch received extensive international media coverage.", "친환경 전기 트럭 출시는 전 세계 주요 언론의 광범위한 집중 보도를 받았습니다."),
        ("spokesperson", "대변인", "noun", "company spokesperson / official spokesperson", "press officer / representative",
         "A company spokesperson denied rumors regarding impending factory shutdowns.", "회사 공식 대변인은 임박한 공장 가동 중단에 관한 항간의 소문을 전면 부인했습니다."),
        ("circulation", "발행 부수, 유통, 순환", "noun", "daily circulation / newspaper circulation", "distribution / readership / print run",
         "The business daily boasts an audited daily circulation of over eight hundred thousand copies.", "그 경제 일간지는 80만 부가 넘는 공인된 일일 신문 발행 부수를 자랑합니다."),
        ("periodical", "정기간행물, 잡지", "noun", "subscribe to periodicals / scholarly periodical", "journal / magazine / serial",
         "University libraries archive thousands of scholarly and business scientific periodicals.", "대학 도서관은 수천 종의 학술 및 비즈니스 과학 전문 정기간행물을 보관합니다."),
        ("editorial", "사설, 논설; 편집의", "noun", "editorial column / editorial board", "leading article / opinion piece",
         "The newspaper published a stinging editorial criticizing regional public transit fares.", "그 신문사는 지역 대중교통 요금 인상을 비판하는 신랄한 사설을 게재했습니다."),
        ("manuscript", "원고", "noun", "submit a manuscript / edit the manuscript", "draft / text / typescript",
         "The novelist delivered the finalized manuscript to her publishing editor three days early.", "소설가는 출판사 편집자에게 최종 완성 원고를 마감일보다 사흘 일찍 전달했습니다."),
        ("proofread", "교정보다, 오탈자를 잡다", "verb", "proofread the copy / carefully proofread", "correct / copyedit / review",
         "Proofread all promotional marketing flyers carefully before authorizing printing runs.", "인쇄소 출력을 승인하기 전에 모든 홍보 마케팅 전단지를 꼼꼼히 교정하십시오."),
        ("circulation", "유통, 발행 부수", "noun", "in circulation / general circulation", "distribution / dissemination",
         "Commemorative gold medals will enter limited public circulation starting tomorrow.", "한정판 기념 금화가 내일부터 일반 대중 유통을 시작할 예정입니다."),
        ("advertising", "광고, 광고업", "noun", "digital advertising / advertising budget", "marketing / promotion / commercials",
         "The firm reallocated thirty percent of its print advertising budget into social video ads.", "그 회사는 인쇄 지면 광고 예산의 30%를 소셜 비디오 광고로 재배치했습니다."),
        ("commercial", "상업 광고 (TV/라디오)", "noun", "television commercial / radio commercial", "advertisement / advert / ad",
         "Broadcasting a thirty-second prime-time television commercial during sports finals costs millions.", "스포츠 결승전 중계 중 30초짜리 프라임타임 TV 광고를 내보내는 데는 수백만 달러가 듭니다."),
        ("endorse", "지지하다, 홍보하다, 배서하다", "verb", "endorse a product / celebrity endorsed", "back / promote / recommend",
         "The tennis champion signed an agreement to endorse the brand's athletic footwear line.", "그 테니스 챔피언은 해당 브랜드의 스포츠 운동화 라인을 홍보(보증)하는 계약에 서명했습니다."),
        ("endorsement", "보증, 광고 출연, 지지", "noun", "celebrity endorsement / product endorsement", "backing / sponsorship / approval",
         "Securing a celebrity endorsement accelerated the cosmetic brand's retail expansion.", "유명 연예인의 광고 출연(보증)을 확보하면서 화장품 브랜드의 매장 확장이 가속화되었습니다."),
        ("publicity", "홍보, 널리 알려짐, 세간의 관심", "noun", "garner publicity / negative publicity", "exposure / attention / hype",
         "The eccentric marketing stunt generated millions of dollars in free global publicity.", "그 기발한 마케팅 이벤트는 수백만 달러 가치의 전 세계적인 무료 언론 홍보 효과를 창출했습니다."),
        ("subscriber", "구독자, 가입자", "noun", "loyal subscriber / paid subscribers", "member / customer / reader",
         "Digital news platforms gained two million paid subscribers after erecting hard paywalls.", "디지털 뉴스 플랫폼은 유료화 장벽(페이월)을 설치한 후 200만 명의 유료 구독자를 확보했습니다."),
        ("exclusive", "독점적인; 특종 기사", "adj", "exclusive interview / exclusive rights", "sole / private / scoop",
         "The business weekly secured an exclusive interview with the elusive billionaire founder.", "그 경제 주간지는 좀처럼 모습을 드러내지 않는 억만장자 창업주와의 독점 인터뷰를 따냈습니다."),
        ("correspondent", "특파원, 기자", "noun", "foreign correspondent / war correspondent", "reporter / journalist / envoy",
         "The foreign correspondent filed nightly televised updates from the peace summit.", "외신 특파원은 평화 정상회담 현장에서 매일 밤 생생한 TV 뉴스 리포트를 보냈습니다."),
        ("broadcast", "방송하다; 방송", "verb", "broadcast live / television broadcast", "air / transmit / beam",
         "The network plans to broadcast the symphony orchestra's charity gala worldwide.", "방송 네트워크는 교향악단의 자선 갈라 콘서트를 전 세계에 라이브로 방송할 계획입니다."),
        ("bulletin", "속보, 공보, 게시", "noun", "news bulletin / daily bulletin", "flash / dispatch / announcement",
         "Radio anchors interrupted normal broadcasting to read an urgent severe storm bulletin.", "라디오 앵커들은 긴급 폭풍 기상 속보를 전하기 위해 정규 방송을 일시 중단했습니다."),
        ("syndicate", "신디케이트 조직; 여러 신문에 동시 기고하다", "verb", "syndicated columnist / news syndicate", "distribute / license / publish",
         "Her weekly financial advice column is syndicated in over one hundred newspapers.", "그녀의 주간 재테크 조언 칼럼은 100개 이상의 신문에 동시 연재(신디케이트 배급)되고 있습니다."),
        ("bestseller", "베스트셀러, 초유행 상품", "noun", "instant bestseller / bestseller list", "hit / blockbuster / success",
         "The management book shot to the summit of the non-fiction bestseller list within a week.", "그 경영 서적은 출간 일주일 만에 비소설 부문 베스트셀러 순위 정상을 차지했습니다."),
        ("disclaimer", "면책 조항, 부인 성명", "noun", "legal disclaimer / read the disclaimer", "waiver / repudiation / warning",
         "Financial newsletters display a prominent disclaimer stating that predictions are not guaranteed.", "금융 뉴스레터는 예측이 결코 보장되지 않는다는 눈에 띄는 면책 고지 문구를 명시합니다."),
        ("retract", "철회하다, 기사를 취소하다", "verb", "retract a statement / retract an article", "withdraw / take back / recant",
         "The tabloid was forced to publicly retract erroneous claims regarding the CEO's health.", "그 타블로이드지는 CEO의 건강에 관한 허위 사실 주장을 공개적으로 철회(정정보도)해야 했습니다."),
        ("retraction", "기사 취소, 철회 공고", "noun", "issue a retraction / publish a retraction", "withdrawal / correction / apology",
         "Editors published a prominent front-page retraction acknowledging the factual reporting error.", "편집진은 사실 취재 오류를 인정하는 눈에 띄는 1면 기사 취소(정정보도문)를 게재했습니다."),
        ("sponsorship", "후원, 스폰서십", "noun", "corporate sponsorship / title sponsorship", "backing / funding / patronage",
         "Corporate sponsorship covers the total staging expenses for the community jazz festival.", "기업의 후원금 덕분에 지역사회 재즈 페스티벌의 전체 무대 연출 비용이 충당되었습니다."),
        ("promotional", "홍보의, 판촉의", "adj", "promotional material / promotional campaign", "advertising / marketing / sales",
         "Retailers handed out promotional tote bags stuffed with skin lotion sample vials.", "소매점들은 스킨 로션 샘플 유리병이 가득 담긴 판촉용 토트백을 고객들에게 나눠주었습니다."),
        ("compile", "엮다, 편집하다, 수집하다", "verb", "compile data / compile a directory", "assemble / gather / collate",
         "The trade association compiled an exhaustive directory of commercial real estate brokers.", "그 무역 협회는 상업용 부동산 중개인들의 상세한 종합 인명록을 엮어 편찬했습니다."),
        ("disseminate", "유포하다, 널리 퍼뜨리다", "verb", "disseminate information / widely disseminated", "spread / distribute / circulate",
         "Public health bureaus use social media to quickly disseminate emergency heat advisories.", "공중보건 당국은 비상 폭염 경보를 신속히 전파(유포)하기 위해 소셜 미디어를 활용합니다."),
        ("segment", "세분화하다; 조각, 부문", "verb", "segment the audience / market segment", "divide / partition / categorize",
         "Marketers segment the customer database by age and purchasing history to target ads.", "마케터들은 맞춤형 광고를 타깃팅하기 위해 연령과 구매 이력별로 고객 데이터베이스를 세분화합니다."),
        ("flyer", "전단지, 광고 쪽지", "noun", "distribute flyers / promotional flyer", "leaflet / pamphlet / handout",
         "Volunteers handed out promotional flyers announcing the grand opening of the farmer's market.", "자원봉사자들은 파머스 마켓의 그랜드 오픈을 알리는 홍보 전단지를 배포했습니다."),
        ("brochure", "안내 책자, 브로슈어", "noun", "travel brochure / full-color brochure", "booklet / pamphlet / leaflet",
         "Pick up a glossy full-color brochure at the ticket desk to read about upcoming performances.", "티켓 카운터에서 향후 공연 안내가 담긴 광택지 풀컬러 브로슈어를 챙겨 가시기 바랍니다."),
        ("billboard", "광고판, 옥외 빌보드", "noun", "highway billboard / digital billboard", "hoarding / sign / display",
         "Bright digital billboards along the expressway display real-time airline ticket deals.", "고속도로변의 밝은 디지털 옥외 광고판(빌보드)은 실시간 특가 항공권 상품을 표시합니다."),
        ("influencer", "인플루언서, 영향력 있는 인사", "noun", "social media influencer / partner with influencers", "trendsetter / tastemaker",
         "The athletic apparel label partnered with fitness influencers to unbox the new sneakers.", "그 스포츠 의류 브랜드는 새 스니커즈 개봉기를 선보이기 위해 피트니스 인플루언서들과 제휴했습니다."),
        ("target", "목표로 삼다; 목표, 과녁", "verb", "target demographics / target audience", "aim at / focus on / direct to",
         "The educational software campaign is precisely targeted at parents of primary pupils.", "그 교육용 소프트웨어 캠페인은 초등학생 학부모들을 정밀하게 목표(타깃)로 삼고 있습니다.")
    ]),

    # DAY 24: 예술, 문화, 공연 및 여가 (34 words)
    24: ("예술/문화", "800필수", [
        ("admission", "입장, 입장료, 입학", "noun", "general admission / free admission", "entry / entrance fee / access",
         "General museum admission is waived for students and seniors every first Thursday.", "매월 첫째 주 목요일에는 학생과 어르신을 대상으로 박물관 일반 입장이 무료입니다."),
        ("curator", "큐레이터, 박물관 학예사", "noun", "museum curator / chief curator", "keeper / conservator / custodian",
         "The chief curator spent five years assembling rare Renaissance oil paintings for the exhibition.", "수석 큐레이터는 이번 특별전을 위해 진귀한 르네상스 유화들을 수집하는 데 5년을 바쳤습니다."),
        ("exhibit", "전시물, 전시품; 전시하다", "noun", "interactive exhibit / historical exhibit", "display / showcase / artifact",
         "The dinosaur skeleton fossil remains the science museum's most celebrated permanent exhibit.", "공룡 골격 화석은 그 과학관에서 가장 인기 있는 영구 전시품으로 남아 있습니다."),
        ("repertoire", "레퍼토리, 연주 목록, 공연 목록", "noun", "extensive repertoire / classical repertoire", "collection / range / playlist",
         "The visiting chamber quartet showcased an extensive repertoire spanning Baroque to Jazz.", "초청 실내악 4중주단은 바로크부터 재즈에 이르는 폭넓은 연주 레퍼토리를 선보였습니다."),
        ("patron", "후원자, 단골 고객", "noun", "arts patron / museum patrons", "sponsor / supporter / backer / benefactor",
         "Wealthy philanthropic patrons endowed the concert hall with ten million dollars for renovations.", "부유한 자선 후원자들은 콘서트홀 보수를 위해 1,000만 달러의 기금을 기부했습니다."),
        ("acoustics", "음향, 음향 시설", "noun", "stellar acoustics / concert hall acoustics", "sound quality / audio resonance",
         "The cedar timber ceiling panels provide warm acoustic resonance for orchestral performances.", "삼나무 목재 천장 패널은 관현악 공연에 따뜻하고 풍성한 음향 공명을 선사합니다."),
        ("matinee", "낮 공연, 마티네", "noun", "Sunday matinee / matinee performance", "afternoon show / daylight screening",
         "Tickets for the Sunday Broadway musical matinee are heavily discounted for families.", "일요일 브로드웨이 뮤지컬 낮 공연(마티네) 티켓은 가족 단위 관람객에게 대폭 할인됩니다."),
        ("premiere", "초연, 개봉; 초연하다", "noun", "world premiere / movie premiere", "debut / opening night / first showing",
         "Film directors and actors walked the crimson red carpet during the glamorous movie premiere.", "화려한 영화 시사회(개봉 행사)에서 영화감독과 주연 배우들이 붉은 레드카펫을 밟았습니다."),
        ("ensemble", "합주단, 앙상블, 어울리는 한 벌", "noun", "chamber ensemble / jazz ensemble", "troupe / band / group / orchestra",
         "The award-winning woodwind ensemble performed works by contemporary Swedish composers.", "수상 경력에 빛나는 목관 앙상블 합주단이 현대 스웨덴 작곡가들의 작품을 연주했습니다."),
        ("heritage", "유산, 전통", "noun", "cultural heritage / historical heritage", "tradition / legacy / inheritance",
         "The coastal fishing village was officially designated a UNESCO World Cultural Heritage site.", "그 연안 어촌 마을은 공식적으로 유네스코 세계문화유산 지구로 지정되었습니다."),
        ("sculpture", "조각품, 조소; 조각하다", "noun", "bronze sculpture / marble sculpture", "statue / figure / carving",
         "Visitors paused in the atrium to admire the towering bronze sculpture by Rodin.", "관람객들은 로댕의 거대한 청동 조각품을 감상하기 위해 중앙 홀에 잠시 발걸음을 멈췄습니다."),
        ("intermission", "휴식 시간 (공연 중간)", "noun", "twenty-minute intermission / during intermission", "break / interval / recess",
         "Patrons mingled in the grand lobby to purchase sparkling champagne during the intermission.", "관객들은 중간 휴식 시간 동안 샴페인을 구매하며 웅장한 로비에서 담소를 나누었습니다."),
        ("box office", "매표소, 흥행 성적", "noun", "box office hit / visit the box office", "ticket counter / commercial success",
         "Collect your reserved will-call performance passes at the exterior box office window.", "예매하신 티켓을 찾으시려면 외부 매표소 창구로 방문해 주시기 바랍니다."),
        ("philanthropy", "자선 활동, 박애주의", "noun", "corporate philanthropy / charitable philanthropy", "benevolence / altruism / charity",
         "Through tireless corporate philanthropy, the foundation funded free music lessons for youth.", "지속적인 기업 자선 활동을 통해 그 재단은 청소년들을 위한 무료 음악 수업을 후원했습니다."),
        ("artisan", "장인, 기능공", "noun", "skilled artisan / local artisans", "craftsman / tradesman / specialist",
         "Local artisans handcraft delicate ceramic tableware using generations of pottery traditions.", "지역 장인들은 대대로 내려오는 도예 전통 기법을 활용하여 정교한 도자기 식기를 손수 제작합니다."),
        ("engraving", "판화, 판각, 조각술", "noun", "woodcut engraving / copper engraving", "etching / print / carving",
         "The collector acquired a rare eighteenth-century woodcut engraving depicting the harbor.", "그 수집가는 항구의 모습을 묘사한 진귀한 18세기 목판화를 손에 넣었습니다."),
        ("virtuoso", "거장, 명연주자; 대가의", "noun", "piano virtuoso / violin virtuoso", "master / maestro / genius",
         "The twenty-year-old violin virtuoso received standing ovations for her Mendelssohn solo.", "스무 살의 천재 바이올린 명연주자는 멘델스존 독주로 기립 박수를 받았습니다."),
        ("renaissance", "부흥, 부활, 르네상스", "noun", "cultural renaissance / experience a renaissance", "revival / rebirth / resurgence",
         "Downtown revitalization triggered a thriving cultural and culinary renaissance in the city.", "도심 재생 사업은 도시 전체에 활기 넘치는 문화와 미식의 부흥(르네상스)을 촉발했습니다."),
        ("tribute", "찬사, 헌정, 공물", "noun", "pay tribute / tribute concert", "homage / salutation / eulogy",
         "The national symphony orchestra staged a moving tribute concert honoring the late conductor.", "국립 심포니 오케스트라는 작고한 지휘자를 기리는 감동적인 헌정 음악회를 무대에 올렸습니다."),
        ("appraise", "감정하다, 평가하다", "verb", "appraise artwork / professionally appraise", "evaluate / value / assess",
         "An antique specialist was commissioned to appraise the oil painting's authentic market worth.", "유화 그림의 진품 여부와 시장 가치를 감정하기 위해 골동품 전문 감정사가 의뢰를 받았습니다."),
        ("curate", "기획하다, 큐레이팅하다", "verb", "curate an exhibition / carefully curated", "organize / select / present",
         "The guest scholar was invited to curate an autumn gallery display on Islamic pottery.", "초빙 학자는 이슬람 도자기에 관한 가을 갤러리 특별전을 기획(큐레이팅)하도록 초청받았습니다."),
        ("solicit", "간청하다, 요청하다, 모금하다", "verb", "solicit donations / solicit feedback", "ask for / seek / plead",
         "Public broadcast television stations solicit viewer donations to sustain educational shows.", "공영 방송국들은 교육 프로그램을 지속하기 위해 시청자들의 자발적인 기부금을 모금(요청)합니다."),
        ("benefactor", "후원자, 기부자", "noun", "generous benefactor / anonymous benefactor", "donor / patron / supporter",
         "An anonymous benefactor donated five million dollars to build the new planetarium.", "익명의 관대한 후원자가 새 천문관 건립을 위해 500만 달러를 기부했습니다."),
        ("auditorium", "강당, 관람석", "noun", "accommodate the auditorium / filled the auditorium", "hall / concert venue / theater",
         "Every seat in the municipal auditorium was occupied for the sold-out ballet performance.", "시립 강당의 모든 좌석은 전석 매진된 발레 공연을 보러 온 관객들로 가득 찼습니다."),
        ("promenade", "산책로, 산책; 산책하다", "noun", "coastal promenade / evening promenade", "walkway / esplanade / stroll",
         "Couples enjoyed relaxing sunset walks along the palm-lined oceanfront pedestrian promenade.", "연인들은 야자수가 늘어선 해변 보행자 전용 산책로(프롬나드)를 따라 여유로운 일몰 산책을 즐겼습니다."),
        ("leisure", "여가, 휴식", "noun", "leisure activities / at your leisure", "free time / recreation / relaxation",
         "Review the attached itinerary at your leisure and let us know if modifications are needed.", "첨부된 여행 일정을 여가 시간에 편안히 검토하시고 수정할 부분이 있으면 알려주십시오."),
        ("spectator", "관중, 구경꾼", "noun", "sports spectator / spectator sport", "onlooker / viewer / watcher",
         "Tens of thousands of cheering spectators lined the streets to watch the annual marathon.", "연례 마라톤 대회를 관람하기 위해 수만 명의 환호하는 관중들이 거리로 쏟아져 나왔습니다."),
        ("concession", "구내매점, 양보, 인정", "noun", "concession stand / food concessions", "snack bar / kiosk / compromise",
         "Spectators queued outside the stadium concession stands to grab hot pretzels and sodas.", "관중들은 따뜻한 프레첼과 탄산음료를 사기 위해 경기장 구내매점 앞에 줄을 섰습니다."),
        ("will-call", "현장 티켓 수령처", "noun", "pick up at will-call / will-call window", "ticket pickup / box office pickup",
         "Internet ticket orders must be collected in person with a photo ID at the will-call booth.", "인터넷 예매 티켓은 사진이 부착된 신분증을 지참하여 현장 수령처(윌콜) 부스에서 직접 수령해야 합니다."),
        ("standing ovation", "기립 박수", "noun", "receive a standing ovation / thunderous standing ovation", "plaudits / cheers / applause",
         "The young soprano received a five-minute standing ovation for her breathtaking high notes.", "젊은 소프라노 가수는 숨이 멎을 듯한 고음 열창으로 5분간의 우레와 같은 기립 박수를 받았습니다."),
        ("amphitheater", "원형 극장, 계단식 강당", "noun", "open-air amphitheater / Roman amphitheater", "arena / colosseum / bowl",
         "The summer rock festival takes place inside a scenic natural open-air stone amphitheater.", "여름 록 페스티벌은 경치 좋은 자연 야외 석조 원형 극장에서 펼쳐집니다."),
        ("choreography", "안무, 무용 구성", "noun", "innovative choreography / intricate choreography", "dance routine / staging",
         "Critics lauded the contemporary ballet production for its demanding, athletic choreography.", "평론가들은 그 현대 발레 작품의 고난도이자 역동적인 안무에 대해 아낌없는 찬사를 보냈습니다."),
        ("maestro", "거장, 마에스트로 (지휘자)", "noun", "esteemed maestro / guest maestro", "conductor / master / musical director",
         "The esteemed guest maestro raised his baton to commence the Beethoven Fifth Symphony.", "존경받는 객원 마에스트로(지휘자)가 베토벤 교향곡 5번 연주를 시작하기 위해 지휘봉을 들어 올렸습니다."),
        ("monument", "기념비, 기념물", "noun", "historic monument / national monument", "memorial / shrine / landmark",
         "The granite obelisk stands in the town plaza as a solemn monument to wartime veterans.", "화강암 오벨리스크는 참전 용사들을 기리는 엄숙한 기념비로서 마을 광장에 우뚝 서 있습니다.")
    ]),

    # DAY 25: 외식, 식음료 및 요리 (34 words)
    25: ("외식/식음료", "800필수", [
        ("culinary", "요리의, 음식의, 주방의", "adj", "culinary arts / culinary excellence", "cooking / gastronomic / cuisine",
         "The French institute offers rigorous professional diplomas in pastry and culinary arts.", "그 프랑스 전문학교는 제과 제빵 및 전문 조리 예술(요리) 디플로마 과정을 제공합니다."),
        ("appetizer", "전채 요리, 에피타이저", "noun", "order an appetizer / savory appetizer", "starter / hors d'oeuvre / bite",
         "Diners enjoyed a refreshing chilled seafood ceviche as an opening gourmet appetizer.", "식사 손님들은 입맛을 돋우는 고급 전채 요리로 시원하고 상큼한 해산물 세비체를 즐겼습니다."),
        ("entree", "주 요리, 메인 요리, 전채", "noun", "select an entree / vegetarian entree", "main course / main dish",
         "For the wedding banquet entree, guests may select either pan-seared salmon or ribeye steak.", "결혼 피로연 메인 요리(앙트레)로 하객들은 팬에 구운 연어 또는 립아이 스테이크 중 하나를 선택할 수 있습니다."),
        ("delicacy", "진미, 별미, 진귀한 음식", "noun", "local delicacy / culinary delicacy", "treat / gourmet food / rarity",
         "Truffles harvested from deep beneath oak groves are prized as a global luxury delicacy.", "참나무 숲 깊은 곳에서 채취한 송로버섯(트러플)은 전 세계적인 최고급 진미로 귀하게 여겨집니다."),
        ("dietary", "식사의, 음식의, 식이요법의", "adj", "dietary restrictions / dietary needs", "nutritional / food / health",
         "Inform the banquet captain ahead of time regarding any allergy or vegetarian dietary needs.", "알레르기나 채식주의 등 식이요법 요구 사항이 있는 경우 연회 캡틴에게 미리 알려주십시오."),
        ("ingredient", "식재료, 성분, 구성요소", "noun", "fresh ingredients / locally sourced ingredients", "component / element / foodstuff",
         "The farm-to-table bistro sources all organic salad ingredients from surrounding family farms.", "그 팜투테이블 비스트로는 주변 가족 농장에서 모든 유기농 샐러드 식재료를 직송받습니다."),
        ("beverage", "음료, 마실 것", "noun", "refreshing beverage / hot beverages", "drink / refreshment / liquid",
         "Patrons are invited to choose complimentary hot coffee or iced tea from the beverage bar.", "손님들은 음료 바에서 무료 따뜻한 커피나 아이스티를 마음껏 선택해 드실 수 있습니다."),
        ("palate", "미각, 입맛, 구개", "noun", "sophisticated palate / please the palate", "taste / appetite / flavor sense",
         "The sommelier recommended crisp Riesling wine formulated to please the discerning palate.", "소믈리에는 안목 있는 까다로운 입맛(미각)을 만족시키도록 빚어진 산뜻한 리슬링 와인을 추천했습니다."),
        ("sommelier", "소믈리에, 와인 전문가", "noun", "certified sommelier / consult the sommelier", "wine steward / wine expert",
         "A certified sommelier assisted the hosting executive in pairing vintage wines with steaks.", "공인 소믈리에는 주최 임원이 스테이크 요리에 어울리는 빈티지 와인을 페어링하는 것을 도왔습니다."),
        ("ambiance", "분위기, 환경", "noun", "romantic ambiance / cozy ambiance", "atmosphere / mood / vibe",
         "Soft acoustic jazz melodies and dim candlelight lent an intimate ambiance to the dining room.", "감미로운 어쿠스틱 재즈 선율과 은은한 촛불 조명이 식당에 아늑하고 다정한 분위기를 더해주었습니다."),
        ("cater", "음식을 공급하다, 부응하다", "verb", "cater to dietary needs / cater the reception", "provide food / serve / accommodate",
         "An award-winning bistro was contracted to cater the opening art gallery gala reception.", "개관 미술관 갈라 리셉션의 출장 뷔페 음식을 공급하도록 수상 경력의 비스트로가 계약되었습니다."),
        ("patronage", "애용, 단골 이용, 후원", "noun", "loyal patronage / appreciate your patronage", "custom / business / support",
         "The historic cafe rewarded ten years of continuous patronage with a VIP tasting evening.", "그 유서 깊은 카페는 10년간의 지속적인 단골 이용에 보답하기 위해 VIP 시식의 밤을 열었습니다."),
        ("specialty", "전문, 특기, 특선 요리", "noun", "house specialty / regional specialty", "signature dish / expertise / forte",
         "Slow-braised rosemary lamb shank is the undisputed chef's house specialty at the tavern.", "로즈마리를 곁들여 푹 조린 양정강이 찜 요리는 그 레스토랑 주방장의 자타 공인 대표 특선 요리입니다."),
        ("seasoning", "양념, 조미료", "noun", "flavorful seasoning / natural seasonings", "spice / condiment / dressing",
         "A subtle dusting of smoked sea salt seasoning elevated the flavor profile of the roasted duck.", "훈제 천일염 양념을 살짝 뿌려 구운 오리 요리의 풍미를 한 단계 끌어올렸습니다."),
        ("condiment", "조미료, 소스류", "noun", "mustard and condiments / condiment station", "seasoning / sauce / relish",
         "Grab napkins and squeeze bottles of hot sauce from the self-serve condiment station.", "셀프서비스 조미료(소스) 거치대에서 냅킨과 핫소스 병을 챙겨 가시기 바랍니다."),
        ("flavorful", "풍미가 넘치는, 맛있는", "adj", "flavorful broth / rich and flavorful", "tasty / delicious / savory",
         "Simmering marrow bones overnight created an intensely aromatic and flavorful noodle broth.", "밤새 골수를 우려내어 향긋하고 깊은 풍미가 넘치는 국수 육수를 완성했습니다."),
        ("savory", "짭짤한, 감칠맛 나는, 풍미 있는", "adj", "savory pastry / savory filling", "salty / piquant / appetizing",
         "The brunch bakery serves both sweet fruit tarts and warm savory mushroom quiches.", "그 브런치 베이커리는 달콤한 과일 타르트와 따뜻하고 짭짤한 버섯 키슈를 모두 판매합니다."),
        ("confectionery", "제과류, 과자 가게", "noun", "fine confectionery / handmade confectionery", "sweets / pastries / candy shop",
         "The boutique Swiss confectionery crafts artisanal truffles wrapped in gold metallic foil.", "그 부티크 스위스 제과점은 금박 호일로 감싼 수제 트러플 초콜릿을 만듭니다."),
        ("gratuity", "팁, 봉사료", "noun", "leave a gratuity / gratuity included", "tip / service charge / gift",
         "For parties numbering six diners or more, an eighteen percent gratuity is automatically billed.", "6인 이상의 단체 손님의 경우 18%의 봉사료(팁)가 계산서에 자동으로 청구됩니다."),
        ("bill", "계산서, 청구서; 청구하다", "noun", "split the bill / request the bill", "check / invoice / tab",
         "Colleagues decided to split the dinner bill evenly across their corporate charge cards.", "동료들은 법인 카드를 나누어 저녁 식사 계산서를 똑같이 분할 결제하기로 했습니다."),
        ("perishable", "잘 상하는, 부패하기 쉬운; 부패성 식품", "adj", "perishable goods / perishable foods", "spoilable / delicate / fresh",
         "Refrigerated containers safeguard dairy produce and perishable seafood during transport.", "냉장 컨테이너는 운송 중에 유제품과 부패하기 쉬운 신선 해산물을 안전하게 보호합니다."),
        ("spoilage", "부패, 손상, 음식 낭비", "noun", "prevent food spoilage / rapid spoilage", "decay / rot / degradation",
         "Vacuum-sealing sliced meats dramatically impedes bacterial growth and costly spoilage.", "얇게 썬 육류를 진공 밀봉 포장하면 세균 번식과 손실 비용이 큰 음식 부패를 획기적으로 막아줍니다."),
        ("hygiene", "위생, 청결", "noun", "kitchen hygiene / maintain strict hygiene", "cleanliness / sanitation / sterility",
         "Commercial chefs wash their hands between food prep stations to maintain strict kitchen hygiene.", "전문 주방 요리사들은 엄격한 주방 위생을 유지하기 위해 조리대 사이를 오갈 때마다 손을 씻습니다."),
        ("sanitation", "공중위생, 위생 관리", "noun", "sanitation inspection / meet sanitation codes", "hygiene / cleanliness / disinfection",
         "The municipal health inspector gave the seafood restaurant top grades for sanitation.", "시 보건 위생 점검관은 그 해산물 레스토랑의 위생 관리 상태에 최고 점수를 부여했습니다."),
        ("reservation", "식사 예약", "noun", "table reservation / make a reservation", "booking / table hold",
         "Diners seeking weekend terrace tables must submit an online reservation two weeks ahead.", "주말 테라스 테이블을 원하는 손님은 2주 전에 온라인으로 사전 예약을 해야 합니다."),
        ("waitlist", "대기자 명단; 대기자 명단에 올리다", "noun", "join the waitlist / long waitlist", "waiting list / standby",
         "Walk-in patrons were invited to enter their cellular phone numbers on the digital waitlist.", "예약 없이 방문한 손님들은 디지털 대기자 명단에 휴대폰 번호를 등록하도록 안내받았습니다."),
        ("complimentary", "무료의, 서비스로 제공되는", "adj", "complimentary dessert / complimentary drinks", "free / gratis / on the house",
         "The head chef sent over complimentary chocolate souffles to apologize for the seating delay.", "총주방장은 자리 안내가 지연된 것에 사과하는 의미로 무료 초콜릿 수플레를 서비스로 제공했습니다."),
        ("buffet", "뷔페; 강타하다", "noun", "buffet dinner / all-you-can-eat buffet", "smorgasbord / self-service spread",
         "The Sunday luxury hotel brunch buffet features bottomless mimosas and carved roast meats.", "호텔의 고급 일요일 브런치 뷔페는 무제한 미모사 칵테일과 즉석에서 썰어주는 로스트 비프를 자랑합니다."),
        ("courteous", "예의 바른, 정중한", "adj", "courteous servers / courteous greeting", "polite / respectful / civil",
         "The courteous waitstaff promptly filled empty water glasses without being prompted.", "정중하고 친절한 서버들은 요청하지 않아도 빈 물잔을 즉시 채워 주었습니다."),
        ("beverage", "음료", "noun", "alcoholic beverages / non-alcoholic beverage", "drinks / libations / refreshments",
         "The lounge offers an extensive list of non-alcoholic herbal mocktails and artisan beverages.", "그 라운지는 무알코올 허브 목테일과 수제 음료의 다양한 메뉴 목록을 선보입니다."),
        ("gourmet", "미식의, 미식가; 고급의", "adj", "gourmet cuisine / gourmet coffee", "gastronomic / fine / high-end",
         "The city center bakery is acclaimed for artisan sourdough loaves and gourmet pastries.", "도심의 그 빵집은 수제 사워도우 빵과 고급 미식 페이스트리로 큰 찬사를 받고 있습니다."),
        ("vintage", "포도주 생산 연도; 고전적인, 최고의", "noun", "vintage wine / prime vintage", "year / classic / antique",
         "Collectors paid thousands of dollars at auction for a rare 1982 Bordeaux vintage bottle.", "수집가들은 경매에서 진귀한 1982년산 보르도 빈티지 와인 한 병에 수천 달러를 지불했습니다."),
        ("refreshing", "상쾌한, 신선한", "adj", "refreshing beverage / refreshing taste", "invigorating / crisp / cooling",
         "After a warm afternoon conference, delegates enjoyed a refreshing glass of chilled iced tea.", "따뜻한 오후 회의를 마친 후, 대표단은 시원하고 상쾌한 냉아이스티 한 잔을 즐겼습니다."),
        ("decaffeinated", "카페인을 제거한, 디카페인의", "adj", "decaffeinated coffee / decaf blend", "decaf / caffeine-free",
         "Diners seeking evening coffee without sleep disruption requested decaffeinated espresso.", "수면 방해 없이 저녁 커피를 즐기려는 손님들은 디카페인 에스프레소를 주문했습니다.")
    ]),

    # DAY 26: 소매 유통, 이커머스 및 배송 (34 words)
    26: ("유통/배송", "800필수", [
        ("logistics", "물류, 유통 체계", "noun", "logistics hub / logistics network", "distribution / freight handling / supply chain",
         "The e-commerce conglomerate operates a state-of-the-art automated logistics distribution hub.", "그 전자상거래 대기업은 최첨단 자동화 물류 유통 허브를 운영하고 있습니다."),
        ("inventory", "재고, 재고 목록; 재고를 조사하다", "noun", "inventory management / take inventory", "stock / merchandise / goods",
         "Radio-frequency scanners allow warehouse staff to track real-time pallet inventory instantly.", "무선 주파수(RFID) 스캐너 덕분에 창고 직원들은 파레트 실시간 재고를 즉시 추적할 수 있습니다."),
        ("procurement", "조달, 구매, 확보", "noun", "procurement department / government procurement", "purchasing / sourcing / acquisition",
         "The procurement manager renegotiated raw rubber supply contracts to curb rising costs.", "자재 조달 부서 관리자는 원가 상승을 억제하기 위해 생고무 원자재 공급 계약을 재협상했습니다."),
        ("warehouse", "창고, 물류창고; 창고에 넣다", "noun", "storage warehouse / automated warehouse", "depot / storehouse / repository",
         "Autonomous robotic carts navigate the two-million-square-foot distribution warehouse.", "자율주행 물류 로봇 카트가 200만 평방피트 규모의 대형 물류 창고를 누비고 다닙니다."),
        ("consignment", "위탁 판매, 탁송 물품", "noun", "on consignment / shipping consignment", "batch / delivery / cargo shipment",
         "Art galleries display paintings on consignment, collecting a thirty percent cut upon sale.", "미술관들은 그림을 위탁 판매(콘사인먼트) 방식으로 전시하며, 판매 시 30%의 수수료를 받습니다."),
        ("clearance", "재고 정리 세일, 통관, 승인", "noun", "clearance sale / customs clearance", "liquidation / disposal / permission",
         "Shoppers crowded the aisles to snag designer coats during the annual winter clearance sale.", "알뜰 쇼핑객들은 연례 겨울 재고 정리(클리어런스) 세일 기간 동안 디자이너 코트를 구매하기 위해 통로를 가득 메웠습니다."),
        ("tracking", "배송 추적, 추적", "noun", "tracking number / package tracking", "monitoring / tracing / following",
         "Customers receive a text containing an active tracking number when packages depart the dock.", "고객들은 소포가 물류창고를 출발할 때 실시간 배송 추적 번호가 포함된 문자 메시지를 받습니다."),
        ("courier", "택배원, 특송업체, 급송 택배", "noun", "express courier / courier service", "messenger / delivery service / carrier",
         "Confidential legal instruments were delivered across the metropolis via express bicycle courier.", "비밀 법률 문서는 특급 자전거 퀵배송(택배) 서비스를 통해 도심 전역으로 배달되었습니다."),
        ("fulfillment", "주문 처리 이행, 완수, 충족", "noun", "fulfillment center / order fulfillment", "execution / completion / dispatch",
         "Orders placed prior to noon are processed in the automated fulfillment center within one hour.", "정오 이전에 접수된 주문은 자동화 풀필먼트(주문 이행) 센터에서 1시간 이내에 처리 완료됩니다."),
        ("packaging", "포장재, 포장", "noun", "eco-friendly packaging / protective packaging", "wrapping / containers / boxing",
         "The retail chain transitioned to hundred percent recyclable molded paper pulp packaging.", "그 소매 유통 체인은 100% 재활용 가능한 성형 종이 펄프 포장재로 전면 전환했습니다."),
        ("shipment", "선적, 발송, 탁송 화물", "noun", "track a shipment / international shipment", "cargo / consignment / delivery",
         "The overseas container shipment was delayed three days due to severe tropical typhoons.", "해외 컨테이너 선적 화물은 강력한 열대성 태풍으로 인해 사흘간 지연되었습니다."),
        ("in transit", "운송 중인, 수송 중인", "phrase", "goods in transit / damaged in transit", "en route / on the way / traveling",
         "Electronic fragile sensor equipment was safely shock-cushioned while in transit across the ocean.", "충격에 민감한 전자 센서 장비는 대양을 건너 운송되는 동안 안전하게 완충 포장되었습니다."),
        ("carton", "판지 상자, 상자", "noun", "sealed carton / shipping carton", "cardboard box / pack / container",
         "Inspectors opened a random carton from the pallet to examine ceramic coffee mug quality.", "검사관들은 도자기 커피 머그잔의 품질을 확인하기 위해 파레트에서 무작위 상자 하나를 열었습니다."),
        ("crate", "나무 상자, 포장용 틀", "noun", "wooden crate / packing crate", "case / box / container",
         "Heavy machinery gears were bolted inside reinforced wooden crates for maritime freight.", "중장비 기어 부품들은 해상 화물 운송을 위해 보강된 목재 상자(크레이트) 내부에 볼트로 고정되었습니다."),
        ("pallet", "화물 운반대, 파레트", "noun", "wooden pallet / stack pallets", "skid / platform / wooden frame",
         "Forklift drivers stacked dozens of shrink-wrapped pallets neatly into double-decker racks.", "지게차 운전사들은 수축 필름으로 감싼 수십 개의 파레트를 2단 적재 랙에 깔끔하게 쌓아 올렸습니다."),
        ("dispatcher", "배차원, 운항 관리원", "noun", "freight dispatcher / emergency dispatcher", "controller / coordinator / manager",
         "The central freight dispatcher rerouted fifteen tractor-trailers around the expressway pileup.", "중앙 화물 배차원은 고속도로 다중 추돌 사고 구간을 피해 대형 트레일러 15대의 경로를 우회시켰습니다."),
        ("surcharge", "추가 요금, 할증료", "noun", "heavy-item surcharge / fuel surcharge", "extra charge / addition / levy",
         "Packages weighing over seventy pounds incur a twenty-dollar oversized handling surcharge.", "70파운드를 초과하는 무거운 소포에는 20달러의 대형 화물 취급 추가 할증료가 부과됩니다."),
        ("receipt", "영수증, 수령", "noun", "store receipt / acknowledge receipt", "proof of purchase / voucher / slip",
         "Keep your original purchase receipt in case you require an exchange or manufacturer warranty service.", "교환이나 제조사 보증 수리가 필요할 경우에 대비하여 구매 영수증 원본을 잘 보관하십시오."),
        ("refund", "환불, 반환; 환불하다", "noun", "issue a full refund / demand a refund", "reimbursement / repayment / rebate",
         "When returned items arrive at the warehouse dock, the system issues a prompt automated refund.", "반품된 물품이 물류창고 도크에 입고되면 시스템이 즉시 자동 환불을 처리합니다."),
        ("voucher", "할인 쿠폰, 상품권, 바우처", "noun", "gift voucher / redeem a voucher", "coupon / token / certificate",
         "First-time app shoppers enter promo code SAVE20 to redeem a ten-dollar checkout voucher.", "앱 첫 구매 고객은 프로모션 코드 SAVE20을 입력하여 10달러 결제 할인 바우처를 사용할 수 있습니다."),
        ("bulk", "대량의, 대규모의; 부피", "adj", "bulk purchase / buy in bulk", "wholesale / mass / volume",
         "Commercial offices save up to twenty percent on printer paper when buying in bulk cartons.", "사무실에서는 상자 단위로 대량 구매(벌크 구매)할 때 복사용지 비용을 최대 20% 절감할 수 있습니다."),
        ("wholesale", "도매의, 대량의; 도매로", "adj", "wholesale prices / wholesale distributor", "bulk / trade / distributor",
         "Boutique owners source hand-woven apparel from wholesale distributors in Florence.", "부티크 숍 점주들은 피렌체의 도매 유통업체로부터 손으로 짠 고급 의류를 사들입니다."),
        ("retail", "소매의, 소매업; 소매로 팔다", "adj", "retail store / retail price", "consumer / store / shop",
         "Online shopping giants are acquiring traditional brick-and-mortar retail brick stores.", "온라인 유통 공룡 기업들이 전통적인 오프라인 소매 매장들을 인수하고 있습니다."),
        ("distributor", "유통업자, 배급사", "noun", "authorized distributor / exclusive distributor", "wholesaler / dealer / supplier",
         "Our enterprise was selected as the sole authorized distributor for the German camera brand.", "저희 회사는 그 독일 카메라 브랜드의 유일한 공인 독점 유통업체로 선정되었습니다."),
        ("barcode", "바코드", "noun", "scan a barcode / printed barcode", "UPC / QR code / product code",
         "Self-checkout lanes allow shoppers to swiftly scan barcodes without waiting for cashiers.", "셀프 계산대를 이용하면 쇼핑객들이 계산원을 기다리지 않고 바코드를 신속히 스캔할 수 있습니다."),
        ("outlet", "아울렛 직영점, 배출구, 콘센트", "noun", "factory outlet / retail outlet", "store / shop / branch",
         "The designer fashion group opened a two-hundred-store discount factory outlet village.", "그 디자이너 패션 그룹은 200개 매장 규모의 대형 할인 팩토리 아울렛 빌리지를 개장했습니다."),
        ("overstock", "과잉 재고; 과잉 공급하다", "noun", "clear overstock / overstock merchandise", "excess inventory / surplus / glut",
         "To clear overstock winter parkas, the warehouse manager slashed prices by sixty percent.", "겨울 파카의 과잉 재고를 소진하기 위해 창고 관리자는 가격을 60% 대폭 인하했습니다."),
        ("backorder", "이월 주문 (재고 부족으로 인한 배송 지연 주문)", "noun", "placed on backorder / item on backorder", "delayed order / pending shipment",
         "The popular cordless drill sold out in an hour and had to be placed on backorder.", "인기 있는 무선 전동 드릴이 1시간 만에 매진되어 이월 주문(백오더) 처리를 해야 했습니다."),
        ("discrepancy", "불일치, 차이", "noun", "inventory discrepancy / billing discrepancy", "mismatch / variance / inconsistency",
         "An annual audit revealed a two percent discrepancy between physical inventory and ledger counts.", "연례 회계감사 결과 실제 장부 재고와 물리적 실물 재고 간에 2%의 불일치가 드러났습니다."),
        ("requisition", "요청서, 청구서; 징발하다", "noun", "purchase requisition / submit a requisition", "order / request / demand",
         "The office manager submitted a formal requisition form for twenty ergonomic desk chairs.", "총무과장은 인체공학적 사무용 의자 20개에 대한 정식 구매 요청서(청구서)를 제출했습니다."),
        ("merchandise", "상품, 물품; 매매하다", "noun", "damaged merchandise / display merchandise", "goods / wares / products",
         "Store staff must inspect incoming boxes for damaged merchandise before stocking shelves.", "매장 직원들은 진열대에 진열하기 전에 파손된 상품이 없는지 입고 상자를 검사해야 합니다."),
        ("vendor", "공급업체, 판매자, 노점상", "noun", "approved vendor / reliable vendor", "supplier / merchant / seller",
         "The municipal school board maintains an approved vendor directory for cafeteria produce.", "시 교육위원회는 구내식당 농산물 납품을 위한 공인 공급업체(벤더) 명단을 관리합니다."),
        ("expedite", "신속히 처리하다, 진척시키다", "verb", "expedite shipment / expedite processing", "speed up / hasten / accelerate",
         "Clients may pay an additional thirty dollars to expedite delivery within twenty-four hours.", "고객들은 24시간 이내의 특급 배송 처리를 위해 30달러의 추가 수수료를 지불할 수 있습니다."),
        ("defective", "결함이 있는, 하자가 있는", "adj", "defective unit / defective merchandise", "faulty / flawed / damaged",
         "Consumers who receive a defective blender may request an immediate free courier replacement.", "결함이 있는 믹서기를 배송받은 소비자는 즉시 무료 택배 교환을 요청할 수 있습니다.")
    ]),

    # DAY 27: 무역, 관세 및 통관 절차 (34 words)
    27: ("무역/통관", "850+킬러", [
        ("tariff", "관세, 관세율", "noun", "import tariff / retaliatory tariff", "customs duty / tax / levy",
         "Governments imposed a twenty percent import tariff on overseas manufactured steel bars.", "정부는 해외 수입산 제조 강철봉에 대해 20%의 수입 관세를 부과했습니다."),
        ("customs", "세관, 관세청, 통관", "noun", "customs declaration / clear customs", "border control / duties / port authority",
         "Freight forwarders submitted digital shipping manifests to clear customs at the seaport.", "화물 운송 주선업자들은 해항 세관 통관을 진행하기 위해 디지털 적하목록을 제출했습니다."),
        ("embargo", "통상 금지령, 수출입 금지", "noun", "trade embargo / lift an embargo", "sanction / ban / blockade",
         "The international trade coalition voted to lift the two-decade economic trade embargo.", "국제 무역 연합체는 20년간 지속되어 온 경제 통상 금지령(엠바고)을 해제하기로 결의했습니다."),
        ("quota", "할당량, 쿼터", "noun", "import quota / production quota", "allowance / limit / ceiling",
         "Bilateral accords established a strict annual import quota of fifty thousand cattle tons.", "양자 협정에 따라 연간 5만 톤의 소고기 수입 할당량(쿼터)이 엄격히 설정되었습니다."),
        ("manifest", "적하목록; 명백한; 드러내다", "noun", "cargo manifest / customs manifest", "shipping list / inventory / clear",
         "Inspectors verified every shipping pallet against the official maritime cargo manifest.", "검사관들은 공식 해상 화물 적하목록과 모든 운송 파레트를 일일이 대조 확인했습니다."),
        ("freight", "화물, 화물 운송, 운임", "noun", "air freight / freight forwarder", "cargo / shipment / payload",
         "Shipping urgent semiconductor supplies via air freight is faster but significantly costlier.", "시급한 반도체 공급품을 항공 화물로 운송하는 것은 훨씬 빠르지만 비용이 상당히 비쌉니다."),
        ("vessel", "대형 선박, 배, 용기", "noun", "container vessel / commercial vessel", "cargo ship / freighter / craft",
         "The ultra-large container vessel can haul twenty-four thousand standardized steel boxes.", "그 초대형 컨테이너 선박은 2만 4천 개의 표준 규격 강철 컨테이너를 운송할 수 있습니다."),
        ("consortium", "컨소시엄, 연합체", "noun", "international consortium / banking consortium", "syndicate / coalition / alliance",
         "A multinational consortium of civil engineers was chosen to construct the deepwater port.", "수심 깊은 심해 항구를 건설하기 위해 다국적 토목 엔지니어링 컨소시엄이 선정되었습니다."),
        ("subsidy", "보조금, 장려금", "noun", "export subsidy / agricultural subsidies", "grant / aid / financial support",
         "World Trade Organization panels ruled that the domestic aircraft export subsidies were unfair.", "세계무역기구(WTO) 패널은 국내 항공기 수출 보조금 지급이 불공정하다고 판정했습니다."),
        ("countervailing", "상쇄하는, 대항하는 (상쇄관세)", "adj", "countervailing duty / countervailing measures", "offsetting / compensating",
         "The commerce department instituted a countervailing duty to offset unfair state funding.", "상무부는 불공정한 국가 보조금을 상쇄하기 위해 상쇄관세(CVD)를 부과했습니다."),
        ("bilateral", "양국의, 쌍방의", "adj", "bilateral trade / bilateral agreement", "mutual / two-sided / joint",
         "Both prime ministers signed a bilateral trade treaty dismantling duties on automotive parts.", "양국 총리는 자동차 부품에 대한 관세를 철폐하는 양자 무역 협정에 서명했습니다."),
        ("multilateral", "다국간의, 다자간의", "adj", "multilateral negotiations / multilateral pact", "many-sided / international / global",
         "Multilateral trade summits in Geneva aimed to reduce non-tariff international barriers.", "제네바에서 열린 다자간 무역 정상회의는 비관세 국제 장벽을 완화하는 것을 목표로 했습니다."),
        ("dumping", "덤핑 (부당 염매, 헐값 투매)", "noun", "anti-dumping duty / predatory dumping", "underselling / price undercutting",
         "Regulators penalized overseas manufacturers for deliberate predatory steel price dumping.", "규제 당국은 고의적인 약탈적 철강 덤핑(헐값 투매)을 자행한 해외 제조사들에 징벌적 조치를 취했습니다."),
        ("clearance", "통관 허가, 정리", "noun", "customs clearance / regulatory clearance", "authorization / approval / release",
         "The cargo crate cannot leave the bonded maritime warehouse until full customs clearance.", "그 화물 상자는 세관의 완전한 통관 허가가 떨어질 때까지 보세 창고를 벗어날 수 없습니다."),
        ("bonded", "보세의, 보증된 (세금 유예 상태)", "adj", "bonded warehouse / bonded freight", "tax-exempt / secured / guaranteed",
         "Imported alcoholic beverages remain stored securely in the bonded warehouse prior to excise duties.", "수입 주류는 소비세 납부 전까지 안전한 보세 창고에 보관된 상태로 유지됩니다."),
        ("consignment", "위탁 탁송물, 위탁 배송", "noun", "receive a consignment / consignee", "shipment / cargo / batch",
         "The foreign buyer verified the arrival and physical condition of the textile consignment.", "해외 바이어는 직물 탁송 화물의 도착과 외관 상태를 직접 확인했습니다."),
        ("demurrage", "체선료, 체화료 (반납 지연 벌금)", "noun", "incur demurrage / pay demurrage", "holding fee / detention charge",
         "Leaving empty steel containers at the marine terminal past five days incurs heavy demurrage.", "해항 터미널에 빈 컨테이너를 5일 넘게 방치하면 무거운 체화료(체선료)가 부과됩니다."),
        ("stevedore", "항만 하역 인부; 하역하다", "noun", "dock stevedore / cargo stevedore", "docker / longshoreman / loader",
         "Experienced stevedores operated crane hoists to unload cargo from the freighter hold.", "숙련된 항만 하역 인부들은 화물선 선창에서 짐을 내리기 위해 크레인 호이스트를 조작했습니다."),
        ("bill of lading", "선하증권 (B/L)", "noun", "issue a bill of lading / original bill of lading", "shipping receipt / cargo contract",
         "The carrier issues an official bill of lading serving as a conclusive receipt of goods.", "운송업자는 화물 인수를 증명하는 결정적 영수증 역할을 하는 공식 선하증권(B/L)을 발행합니다."),
        ("letter of credit", "신용장 (L/C)", "noun", "irrevocable letter of credit / open an L/C", "bank guarantee / documentary credit",
         "Exporters require an irrevocable letter of credit confirmed by an international tier-one bank.", "수출업자는 1등급 글로벌 은행이 확인한 취소 불능 신용장(L/C)을 요구합니다."),
        ("certificate of origin", "원산지 증명서", "noun", "valid certificate of origin / issue a certificate", "provenance document / origin form",
         "Attach an authorized chamber of commerce certificate of origin to qualify for preferential tariffs.", "특혜 관세 혜택을 받으려면 공인 상공회의소의 원산지 증명서를 첨부하십시오."),
        ("quarantine", "검역, 격리; 검역하다", "noun", "agricultural quarantine / pass quarantine", "inspection / biosecurity / isolation",
         "Fruit crates must undergo stringent pest fumigation before clearing border quarantine.", "수입 과일 상자는 국경 식물 검역을 통과하기 전에 엄격한 해충 훈증 소독을 거쳐야 합니다."),
        ("sanctions", "경제 제재, 승인", "noun", "impose economic sanctions / lift sanctions", "penalties / embargo / restrictions",
         "The multinational alliance voted unanimously to impose stringent new financial sanctions.", "다국적 연합체는 강력한 신규 금융 경제 제재를 부과하는 데 만장일치로 찬성표를 던졌습니다."),
        ("inward", "안으로 향하는, 수입의", "adj", "inward investment / inward cargo", "incoming / inbound / domestic-bound",
         "Pro-business free trade zones sparked a dramatic seventy percent jump in foreign inward investment.", "친기업적인 자유무역특구 덕분에 해외로부터의 국내 직접 유입 투자(내향 투자)가 70% 급증했습니다."),
        ("outward", "밖으로 향하는, 수출의", "adj", "outward freight / outward voyage", "outgoing / outbound / outbound journey",
         "The container vessel embarked on its twenty-day outward voyage across the Pacific basin.", "그 컨테이너선은 태평양을 가로지르는 20일간의 외향(출항) 항해를 시작했습니다."),
        ("arbitrage", "차익 거래, 재정 거래", "noun", "currency arbitrage / regulatory arbitrage", "price exploitation / trading spread",
         "Traders exploit split-second commodity arbitrage opportunities between New York and London.", "거래자들은 뉴욕과 런던 거래소 간의 찰나의 원자재 시세 차익 거래 기회를 활용합니다."),
        ("consignee", "화물 수하인 (받는 사람)", "noun", "notify the consignee / designated consignee", "receiver / recipient / buyer",
         "Port freight coordinators contacted the consignee immediately upon the ship docking.", "항만 화물 코디네이터들은 선박이 부두에 접안하자마자 화물 수하인(받는 사람)에게 즉시 연락했습니다."),
        ("consignor", "화물 송하인 (보내는 사람)", "noun", "authorized consignor / freight consignor", "sender / shipper / exporter",
         "The consignor is responsible for ensuring hazardous chemicals are packed according to code.", "송하인(보내는 사람)은 유해 화학물질이 안전 규정에 맞게 포장되었는지 확인할 책임이 있습니다."),
        ("free on board", "본선 인도 조건 (FOB)", "phrase", "quote FOB terms / FOB Shanghai", "shipping terms / delivery condition",
         "Quoting prices Free on Board means the foreign buyer assumes all freight shipping risks.", "본선 인도 조건(FOB)으로 가격을 견적한다는 것은 해외 구매자가 선적 이후의 모든 화물 운송 위험을 부담함을 뜻합니다."),
        ("CIF", "운임·보험료 포함 인도 조건 (Cost, Insurance, Freight)", "phrase", "quoted CIF / CIF terms", "shipping conditions / delivered price",
         "The exporter agreed to sell the steel billets on CIF terms, paying both transport and marine insurance.", "수출업자는 운송료와 해상보험료를 모두 지불하는 CIF 조건으로 강철 빌릿을 판매하기로 합의했습니다."),
        ("transshipment", "환적 (화물을 다른 배로 옮겨 싣는 것)", "noun", "port of transshipment / container transshipment", "transfer / reloading / resh shipment",
         "Singapore serves as the busiest container transshipment junction throughout Southeast Asia.", "싱가포르는 동남아시아 전역에서 가장 분주한 컨테이너 환적 교차 항구 역할을 합니다."),
        ("wharfage", "부두 사용료", "noun", "pay wharfage fees / port wharfage", "dock dues / quay charges / pier fee",
         "Harbor authorities levy a nominal container wharfage fee for utilizing municipal cranes.", "항만 당국은 시립 크레인 시설 이용에 대해 소액의 컨테이너 부두 사용료(하역료)를 부과합니다."),
        ("pilferage", "소량 도난, 화물 훔치기", "noun", "prevent cargo pilferage / transit pilferage", "theft / petty stealing / shrinkage",
         "Barcoded holographic tamper seals significantly curtailed valuable electronics cargo pilferage.", "바코드가 인쇄된 홀로그램 위변조 방지 씰을 도입하여 귀중한 전자 화물의 소량 도난을 대폭 줄였습니다."),
        ("haulage", "도로 화물 운송, 운반, 운임", "noun", "long-distance haulage / road haulage", "cartage / trucking / drayage",
         "Diesel fuel cost inflation directly inflated cross-country container road haulage rates.", "디젤 연료비 인플레이션은 전국 횡단 컨테이너 도로 화물 운송료를 직접적으로 인상시켰습니다.")
    ]),

    # DAY 28: 조직 개편, 합병 및 인수 (34 words)
    28: ("조직/합병", "850+킬러", [
        ("acquisition", "기업 인수, 획득", "noun", "corporate acquisition / strategic acquisition", "takeover / purchase / buyout",
         "The tech titan concluded its landmark sixty-billion-dollar corporate acquisition of the studio.", "그 기술 대기업은 영화 스튜디오에 대한 600억 달러 규모의 기념비적인 기업 인수를 최종 성사시켰습니다."),
        ("merger", "합병", "noun", "merger and acquisition / proposed merger", "amalgamation / combination / fusion",
         "The two telecommunications operators finalized an equal merger creating a dominant carrier.", "두 이동통신사는 대등 합병을 마무리하여 시장 지배적인 통신사를 탄생시켰습니다."),
        ("synergy", "상승 효과, 시너지", "noun", "operational synergy / achieve synergies", "teamwork / combined power / synthesis",
         "Executive boards projected thirty million dollars in annual operational cost synergies.", "경영진 이사회는 연간 3,000만 달러 규모의 운영비 절감 상승 효과(시너지)를 달성할 것으로 전망했습니다."),
        ("conglomerate", "복합 대기업", "noun", "multinational conglomerate / retail conglomerate", "corporation / group / cartel",
         "The industrial conglomerate divested its aviation leasing division to focus on clean energy.", "그 복합 산업 대기업은 청정에너지에 집중하기 위해 항공기 리스 사업부를 매각(분할)했습니다."),
        ("restructuring", "구조조정, 조직 개편", "noun", "corporate restructuring / organizational restructuring", "reorganization / overhaul / reshuffle",
         "Under the supervision of insolvency courts, the airline underwent comprehensive restructuring.", "파산 법원의 감독하에 그 항공사는 전면적인 기업 구조조정을 거쳤습니다."),
        ("takeover", "인수, 경영권 탈취", "noun", "hostile takeover / friendly takeover", "acquisition / buyout / purchase",
         "The board adopted poison-pill defenses to thwart an unwelcome hostile corporate takeover.", "이사회는 적대적 기업 인수(M&A) 시도를 무산시키기 위해 포이즌 필 방어 전략을 채택했습니다."),
        ("hostile", "적대적인", "adj", "hostile bid / hostile environment", "antagonistic / aggressive / uninviting",
         "Shareholders decisively voted down the hostile buyout bid from the offshore hedge fund.", "주주들은 해외 역외 헤지펀드의 적대적인 공개 매수 인수가를 단호히 부결시켰습니다."),
        ("stakeholder", "이해관계자", "noun", "key stakeholder / corporate stakeholder", "interested party / shareholder / partner",
         "The management consultation forum invited feedback from union leaders and key stakeholders.", "경영 자문 포럼은 노조 지도부 및 주요 이해관계자들의 솔직한 피드백을 청취했습니다."),
        ("downsize", "인력을 감축하다, 축소하다", "verb", "downsize operations / downsize staff", "cut back / trim / reduce",
         "Plummeting automobile sales forced the regional assembly manufacturer to downsize staff.", "자동차 판매 급감으로 인해 지역 조립 제조 공장은 인력을 대대적으로 감축해야 했습니다."),
        ("streamline", "간소화하다, 능률화하다", "verb", "streamline operations / streamline processes", "optimize / simplify / modernize",
         "The firm eliminated three redundant managerial tiers to streamline decision-making.", "그 회사는 의사결정 과정을 간소화하고 신속하게 만들기 위해 불필요한 3개 관리자 직급을 없앴습니다."),
        ("divest", "매각하다, 처분하다, 박탈하다", "verb", "divest non-core assets / divest holdings", "sell off / dispose of / liquidate",
         "To appease antitrust regulators, the media giant consented to divest thirty regional stations.", "반독점 규제 당국을 달래기 위해 그 미디어 대기업은 30개 지방 방송국을 매각(처분)하기로 동의했습니다."),
        ("divestiture", "자산 매각, 사업 분할", "noun", "corporate divestiture / planned divestiture", "sell-off / disposal / spin-off",
         "Proceeds from the strategic corporate divestiture will be utilized to retire legacy debts.", "전략적 기업 사업부 매각에서 발생한 수익금은 노후 부채를 상환하는 데 전액 사용될 것입니다."),
        ("spin-off", "기업 분사, 파생 상품; 분사하다", "noun", "corporate spin-off / profitable spin-off", "offshoot / branch / subsidiary",
         "The pharmaceutical enterprise executed a tax-free spin-off of its consumer skincare arm.", "그 제약 기업은 소비자용 스킨케어 사업부에 대한 비과세 분사(스핀오프)를 단행했습니다."),
        ("consolidation", "통합, 합동, 강화", "noun", "industry consolidation / debt consolidation", "merger / integration / unification",
         "Mounting economic competition triggered widespread consolidation throughout the retail banking space.", "치열해지는 경제 경쟁으로 인해 소매 금융 은행 업계 전반에 대대적인 통폐합(통합) 바람이 불었습니다."),
        ("subsidiary", "자회사; 보조의", "noun", "wholly owned subsidiary / foreign subsidiary", "affiliate / branch / offshoot",
         "The electronics parent corporation operates a wholly owned software development subsidiary.", "그 전자 모기업은 100% 지분을 보유한 소프트웨어 개발 완전 자회사를 운영하고 있습니다."),
        ("parent company", "모회사", "noun", "foreign parent company / parent company guarantee", "holding company / corporate parent",
         "Financial liabilities incurred by the subsidiary are legally guaranteed by the parent company.", "자회사가 떠안은 금융 채무는 모회사가 법적으로 연대 보증합니다."),
        ("holding company", "지주회사", "noun", "form a holding company / financial holding company", "parent corporation / conglomerate umbrella",
         "The founding family structured their varied retail and logistics empires under a single holding company.", "창업주 일가는 다양한 소매 및 물류 기업군을 단일 지주회사 체제 아래로 재편했습니다."),
        ("reorganization", "조직 개편, 재건", "noun", "bankruptcy reorganization / department reorganization", "restructuring / shake-up / reform",
         "The chief executive instituted an aggressive internal reorganization across marketing teams.", "최고경영자는 마케팅 부서 전반에 걸쳐 공격적인 내부 조직 개편을 단행했습니다."),
        ("turnaround", "회생, 호전, 턴어라운드", "noun", "corporate turnaround / turnaround strategy", "recovery / revival / comeback",
         "Thanks to innovative smartphone designs, the struggling brand achieved a miraculous turnaround.", "혁신적인 스마트폰 디자인 덕분에 위기에 빠졌던 그 브랜드는 기적적인 경영 회생(턴어라운드)을 달성했습니다."),
        ("due diligence", "실사 (기업 인수 전 철저한 조사)", "noun", "conduct due diligence / thorough due diligence", "investigation / audit / scrutiny",
         "Accountants conducted five months of painstaking due diligence before closing the purchase.", "회계사들은 최종 인수를 성사시키기 전 5개월간의 치밀한 기업 실사(Due Diligence)를 수행했습니다."),
        ("contingency", "비상사태, 만일의 사태", "noun", "contingency plan / prepare for contingencies", "emergency / backup plan / eventuality",
         "The risk officer devised a comprehensive contingency plan in case the overseas port strikes.", "리스크 관리 책임자는 해외 항구 파업 사태에 대비한 종합적인 비상 대책(컨틴전시 플랜)을 수립했습니다."),
        ("buyout", "기업 매수, 인수", "noun", "leveraged buyout / management buyout", "purchase / acquisition / takeover",
         "Private equity executives financed a ten-billion-dollar leveraged buyout of the hospital network.", "사모펀드 경영진은 병원 체인망을 인수하기 위해 100억 달러 규모의 차입 매수(LBO) 자금을 조달했습니다."),
        ("severance", "퇴직금, 고용 종료", "noun", "severance pay / severance package", "redundancy payment / dismissal compensation",
         "Staff affected by factory closures were granted a generous six-month severance package.", "공장 폐쇄로 영향을 받은 직원들에게는 6개월 치의 후한 퇴직금 패키지가 지급되었습니다."),
        ("layoff", "정리해고; 정리해고하다", "noun", "mass layoffs / avoid layoffs", "redundancies / dismissals / staff cuts",
         "The technology sector witnessed painful mass layoffs as advertising revenues cratered.", "광고 수익이 급락함에 따라 기술 업계는 고통스러운 대규모 정리해고 사태를 겪었습니다."),
        ("supervision", "감독, 관리", "noun", "under the supervision / direct supervision", "oversight / surveillance / guidance",
         "Junior technicians assemble delicate circuit components under the direct supervision of seniors.", "초급 기술자들은 선임 기술자의 직접적인 감독 관리하에 정밀한 회로 부품을 조립합니다."),
        ("oversight", "관리, 감독, 실수(간과)", "noun", "regulatory oversight / executive oversight", "supervision / direction / lapse",
         "A parliamentary committee exercised regulatory oversight regarding airline safety lapses.", "의회 위원회는 항공사의 안전 불감증 문제에 관해 철저한 규제 감독권을 행사했습니다."),
        ("governance", "지배구조, 통치, 관리 체계", "noun", "corporate governance / good governance", "management / stewardship / rule",
         "Institutional investors demanded reforms to elevate the firm's transparent corporate governance.", "기관 투자자들은 회사의 투명한 기업 지배구조(ESG 가버넌스)를 개선할 개혁을 요구했습니다."),
        ("realign", "재조정하다, 재편성하다", "verb", "realign priorities / realign resources", "reorganize / readjust / reorient",
         "The board resolved to realign corporate spending toward developing autonomous vehicle sensors.", "이사회는 자율주행차 센서 개발을 향해 기업 R&D 지출을 전면 재조정하기로 결의했습니다."),
        ("benchmark", "비교 평가하다, 기준점", "verb", "benchmark against competitors / industry benchmark", "compare / evaluate / test",
         "Human resources benchmarked our executive compensation tiers against fifty rival corporations.", "인사부는 당사의 임원 보수 체계를 50개 경쟁사와 정밀하게 비교 평가(벤치마킹)했습니다."),
        ("syndicate", "기업 조합, 신디케이트", "noun", "underwriting syndicate / bank syndicate", "consortium / group / cartel",
         "A global underwriting syndicate guaranteed the company's initial public stock offering.", "글로벌 인수 기업 조합(신디케이트)이 그 회사의 기업공개(IPO) 신주 발행을 전액 인수 보증했습니다."),
        ("retention", "유지, 보존, 보유 (직원 잔류)", "noun", "employee retention / retention rate", "keeping / preservation / maintenance",
         "To improve engineer retention, the firm offered attractive stock options and flexible hours.", "핵심 개발자들의 잔류(유지율)를 높이기 위해 회사는 매력적인 스톡옵션과 유연근무제를 제공했습니다."),
        ("moratorium", "지불 유예, 일시 정지", "noun", "debt moratorium / place a moratorium", "halt / suspension / freeze",
         "The treasury declared a twelve-month moratorium on municipal infrastructure bond repayments.", "재무부는 지방 인프라 공채 상환에 대해 12개월간의 일시 지불 유예(모라토리엄)를 선포했습니다."),
        ("attrition", "자연 감소, 마모 (인력)", "noun", "natural attrition / rate of attrition", "staff shrinkage / reduction / wearing down",
         "Instead of enacting layoffs, management froze hiring to reduce headcount through natural attrition.", "인위적인 정리해고 대신, 경영진은 정년퇴직 등 자연 감소를 통해 인력을 감축하고자 신규 채용을 동결했습니다."),
        ("insolvency", "지급 불능, 파산", "noun", "file for insolvency / commercial insolvency", "bankruptcy / ruin / liquidation",
         "Unable to service crushing bank debts, the historic department store was forced into insolvency.", "눈덩이처럼 불어난 은행 빚을 감당하지 못한 그 유서 깊은 백화점은 결국 지급 불능(파산)에 빠졌습니다.")
    ]),

    # DAY 29: 품질 관리, 감사 및 인증 규격 (34 words)
    29: ("품질/감사", "850+킬러", [
        ("quality assurance", "품질 보증 (QA)", "noun", "quality assurance team / QA protocol", "quality control / inspection / compliance",
         "Our rigorous quality assurance team tests randomly sampled circuits on the line every hour.", "저희의 엄격한 품질 보증(QA) 팀은 생산 라인에서 무작위로 추출한 회로 기판을 매시간 검사합니다."),
        ("audit", "회계 감사, 심사; 감사하다", "noun", "external audit / tax audit", "inspection / examination / check",
         "An independent accounting firm conducted the statutory annual financial audit without finding discrepancies.", "독립 회계법인은 아무런 불일치 오류를 발견하지 않고 법정 연례 회계감사를 마쳤습니다."),
        ("compliance", "준수, 컴플라이언스", "noun", "safety compliance / strict compliance", "adherence / conformity / observance",
         "Factory floor foremen guarantee that all operations maintain strict safety compliance.", "공장 현장 십장들은 모든 작업이 엄격한 안전 규정을 준수하도록 보장합니다."),
        ("standardization", "표준화, 규격화", "noun", "process standardization / international standardization", "uniformity / systematization",
         "Global hardware standardization enables components to fit interchangeably across models.", "글로벌 하드웨어 표준화 덕분에 여러 제품 모델 간에 부품을 상호 호환하여 장착할 수 있습니다."),
        ("certification", "인증, 자격증", "noun", "safety certification / ISO certification", "accreditation / endorsement / credential",
         "The factory successfully obtained ISO 9001 quality management system certification.", "그 공장은 ISO 9001 품질경영시스템 인증을 성공적으로 획득했습니다."),
        ("inspection", "검사, 시찰, 감사", "noun", "routine inspection / conduct an inspection", "examination / checkup / review",
         "Aviation regulators carry out a mandatory pre-flight inspection before every departure.", "항공 규제 당국은 비행기가 출발하기 전에 의무적인 사전 비행 검사를 실시합니다."),
        ("discrepancy", "불일치, 괴리", "noun", "unexplained discrepancy / minor discrepancy", "variance / inconsistency / difference",
         "The financial auditor identified a ten-thousand-dollar discrepancy in petty cash receipts.", "회계 감사관은 소액 소모품비 영수증에서 1만 달러의 금액 불일치를 찾아냈습니다."),
        ("benchmark", "기준, 벤치마크; 기준 삼다", "noun", "industry benchmark / gold benchmark", "standard / yardstick / criterion",
         "The company's defective parts rate of under one per million is the industry gold benchmark.", "100만 개당 1개 미만이라는 회사의 불량률은 동종 업계의 절대적인 황금 기준(벤치마크)입니다."),
        ("calibrate", "눈금을 조정하다, 보정하다", "verb", "calibrate instruments / precisely calibrate", "adjust / fine-tune / measure",
         "Specialists must calibrate digital laboratory scales every morning to ensure accuracy.", "정밀도를 보장하기 위해 전문가들은 매일 아침 실험실의 전자저울 눈금을 정확히 보정해야 합니다."),
        ("flaw", "결함, 흠, 하자", "noun", "microscopic flaw / design flaw", "defect / fault / imperfection",
         "Laser sensors identified a microscopic structural flaw inside the turbine fan blade.", "레이저 센서가 터빈 팬 블레이드 내부에서 미세한 구조적 결함을 감지해 냈습니다."),
        ("rectify", "시정하다, 바로잡다", "verb", "rectify the issue / swiftly rectify", "correct / repair / amend",
         "Assembly engineers halted the line immediately to rectify a mechanical screw alignment error.", "조립 엔지니어들은 나사 정렬 기계 오류를 바로잡기(시정하기) 위해 즉시 라인을 중단했습니다."),
        ("remedy", "개선책, 치료법; 바로잡다", "noun", "corrective remedy / legal remedy", "solution / cure / fix",
         "Installing thermal exhaust hoods provided an instant remedy for factory floor overheating.", "열기 배출 후드를 설치함으로써 공장 작업장의 과열 문제를 즉각 해결(개선)할 수 있었습니다."),
        ("verify", "확인하다, 검증하다", "verb", "verify results / verify identity", "confirm / authenticate / validate",
         "Please submit an official utility bill to verify your permanent home address.", "고객님의 영구 자택 주소를 확인(검증)하기 위해 공식 공과금 고지서를 제출해 주십시오."),
        ("meticulous", "꼼꼼한, 세심한", "adj", "meticulous attention / meticulous records", "precise / scrupulous / painstaking",
         "The laboratory technician maintained meticulous handwritten notes of every chemical titration.", "그 실험실 기술자는 모든 화학 적정 실험에 대해 매우 꼼꼼한 육필 기록을 유지했습니다."),
        ("faulty", "결함이 있는, 오작동하는", "adj", "faulty wiring / faulty mechanism", "defective / flawed / broken",
         "A recall was initiated when twenty vehicles exhibited faulty hydraulic brake valves.", "20대의 차량에서 결함이 있는 유압 브레이크 밸브가 발견되자 즉각 리콜이 발동되었습니다."),
        ("stringent", "엄격한, 철저한", "adj", "stringent standards / stringent regulations", "strict / rigorous / tight",
         "Infant formula packaging must comply with extraordinarily stringent biological hygiene standards.", "유아용 분유 포장은 대단히 엄격한 생물학적 위생 기준을 충족해야 합니다."),
        ("tolerance", "공차 (허용 오차 범위), 관용", "noun", "narrow tolerance / strict tolerance", "allowance / variance / margin",
         "Aerospace valve parts are machined within an ultra-precise microscopic tolerance of 0.001mm.", "항공우주용 밸브 부품은 0.001mm라는 극도로 정밀한 미세 허용 공차 범위 내에서 가공됩니다."),
        ("deviation", "일탈, 편차, 벗어남", "noun", "standard deviation / minor deviation", "aberration / variance / divergence",
         "Any measurable deviation from approved blueprints will trigger an immediate production stop.", "승인된 설계도로부터 측정 가능한 어떠한 사소한 편차라도 발생하면 즉각 생산 중단이 내려집니다."),
        ("criterion", "기준, 평가 척도", "noun", "selection criterion / fulfill criteria", "standard / benchmark / test",
         "Structural durability is the foremost criterion evaluated by the bridge building inspectorate.", "구조적 내구성은 교량 건설 감리단이 평가하는 가장 첫 번째 기준입니다."),
        ("scrutiny", "정밀 조사, 철저한 검토", "noun", "under scrutiny / subject to scrutiny", "inspection / examination / audit",
         "Following accounting irregularities, the enterprise was placed under intense tax scrutiny.", "회계 부정 사건 이후, 그 기업은 국세청의 집중적인 세무 정밀 조사를 받게 되었습니다."),
        ("substandard", "기준 이하의, 불량한", "adj", "substandard goods / substandard materials", "inferior / second-rate / low-grade",
         "Quality inspectors confiscated three crates of substandard counterfeit concrete bolts.", "품질 검사관들은 기준 이하(불량)의 가짜 콘크리트 볼트 세 상자를 전량 압수했습니다."),
        ("uncompromising", "타협하지 않는, 확고한", "adj", "uncompromising quality / uncompromising standards", "inflexible / rigorous / resolute",
         "The luxury chronograph brand built its legendary reputation on uncompromising craftsmanship.", "그 명품 크로노그래프 시계 브랜드는 결코 타협하지 않는 장인정신을 바탕으로 전설적인 명성을 쌓았습니다."),
        ("tamper", "함부로 손대다, 조작하다", "verb", "tamper with evidence / tamper-evident", "alter / interfere / manipulate",
         "Bottles are wrapped in tamper-evident clear plastic seals to guarantee consumer safety.", "소비자의 안전을 보장하기 위해 음료병은 개봉 여부를 한눈에 알 수 있는 밀봉 씰로 포장됩니다."),
        ("recalibrate", "다시 눈금을 조정하다", "verb", "recalibrate sensors / recalibrate equipment", "readjust / re-tune",
         "Field technicians recalibrate the seismic sensors every six months using GPS satellites.", "현장 기술자들은 GPS 인공위성을 활용하여 6개월마다 지진 감지 센서의 눈금을 다시 조정(재보정)합니다."),
        ("rigorous", "엄격한, 혹독한, 철저한", "adj", "rigorous inspection / rigorous training", "demanding / strict / meticulous",
         "New drug formulations undergo rigorous multi-year toxicological testing on cellular models.", "새 약품 포뮬러는 세포 모델을 바탕으로 혹독하고 엄격한 다년간의 독성 검사를 거칩니다."),
        ("defect", "결함, 하자, 결점", "noun", "manufacturing defect / latent defect", "flaw / fault / blemish",
         "The warranty covers any functional manufacturing defect arising from normal household usage.", "품질 보증서는 일반적인 가정 내 사용 중 발생하는 모든 기능적 제조 결함에 대해 무상 수리를 보장합니다."),
        ("assurance", "보증, 확신", "noun", "quality assurance / give assurance", "guarantee / promise / security",
         "Third-party laboratory seals provide consumers with genuine assurance of product purity.", "제3자 공인 시험기관의 인증 마크는 소비자에게 제품 순도에 대한 진정한 보증을 제공합니다."),
        ("accreditation", "공인, 인가, 자격 부여", "noun", "receive accreditation / hospital accreditation", "recognition / certification / approval",
         "The testing laboratory achieved international ISO accreditation for toxic soil screening.", "그 시험 연구소는 유독성 토양 검별 분석과 관련하여 국제 ISO 공인 인가를 획득했습니다."),
        ("conformance", "일치, 적합성, 순응", "noun", "certificate of conformance / ensure conformance", "compliance / adherence / harmony",
         "A signed certificate of conformance must accompany every overseas titanium batch.", "수입되는 모든 티타늄 원자재 묶음에는 서명된 품질 적합성 증명서가 동봉되어야 합니다."),
        ("malfunction", "오작동; 오작동하다", "noun", "equipment malfunction / minor malfunction", "breakdown / failure / fault",
         "Emergency backup generators engaged automatically the moment the power grid suffered a malfunction.", "전력망에 갑작스러운 오작동이 발생한 순간 비상 백업 발전기가 자동으로 가동되었습니다."),
        ("discrepancy", "차이, 불일치", "noun", "reconcile discrepancies / audit discrepancy", "inconsistency / mismatch / variance",
         "The accounting controller spent three days reconciling inventory count discrepancies.", "회계 통제관은 창고 실물 재고와 장부 수량 간의 불일치를 조정하기 위해 사흘을 쏟아부었습니다."),
        ("integrity", "온전함, 무결성, 진실성", "noun", "structural integrity / corporate integrity", "soundness / honesty / unity",
         "Ultrasonic sound waves test the inner structural integrity of pipeline welds without destruction.", "초음파 음파 검사를 통해 배관 용접부 내부의 구조적 온전함(무결성)을 비파괴 방식으로 점검합니다."),
        ("traceability", "추적 가능성 (이력 추적)", "noun", "complete traceability / supply chain traceability", "tracking capability / verification",
         "Barcoded cattle ear tags provide full farm-to-table traceability for all organic beef.", "바코드가 부착된 소의 귀 이표는 모든 유기농 쇠고기에 대해 농장에서 식탁까지 완전한 이력 추적성을 제공합니다."),
        ("revocation", "취소, 철회, 폐지", "noun", "license revocation / accreditation revocation", "annulment / cancellation / withdrawal",
         "Falsifying laboratory emissions records led to the immediate revocation of the factory's operating permit.", "연구소 배출가스 검사 기록을 조작한 행위는 공장 가동 허가의 즉각적인 취소(철회)로 이어졌습니다.")
    ]),

    # DAY 30: 850+ 목표 고난도 킬러 어휘 & 관용구 총정리 (34 words)
    30: ("850+킬러", "850+킬러", [
        ("commensurate", "비례하는, 상응하는", "adj", "commensurate with experience / salary commensurate", "proportional / equivalent / corresponding",
         "Compensation packages will be strictly commensurate with past executive experience.", "급여 및 복리후생 패키지는 과거 임원직 경력과 철저히 비례하여(상응하여) 책정될 것입니다."),
        ("prerequisite", "전제 조건, 필수 과목", "noun", "essential prerequisite / meet prerequisites", "requirement / precondition / qualification",
         "Five years of certified project management is an essential prerequisite for this posting.", "5년간의 공인 프로젝트 관리 경력은 본 직무 채용에 필수적인 전제 조건입니다."),
        ("unprecedented", "전례 없는, 파격적인", "adj", "unprecedented growth / unprecedented demand", "unequaled / unparalleled / unmatched",
         "Surging holiday orders generated unprecedented quarterly demand for organic cosmetics.", "폭발적인 연말 주문으로 인해 유기농 화장품에 대한 전례 없는 분기별 수요가 창출되었습니다."),
        ("tentative", "잠정적인, 확정되지 않은", "adj", "tentative agreement / tentative itinerary", "provisional / unconfirmed / exploratory",
         "The negotiating committees reached a tentative accord subject to rank-and-file union votes.", "협상 위원회는 노조원들의 찬반 투표를 조건으로 잠정적인 합의안에 도달했습니다."),
        ("expedite", "신속히 처리하다, 진척시키다", "verb", "expedite the application / expedite shipping", "accelerate / hasten / speed up",
         "Please phone our helpdesk if you wish to expedite processing for your passport renewal.", "여권 갱신 심사를 신속히 처리(급행)하고자 하시는 경우 안내 센터로 전화해 주십시오."),
        ("contingent", "~에 달려 있는, 조건으로 하는; 파견대", "adj", "contingent upon approval / contingent plan", "dependent on / conditional / subject to",
         "The corporate acquisition is strictly contingent upon securing final antitrust clearance.", "그 기업 인수는 최종 반독점 승인을 확보할 수 있는지 여부에 전적으로 달려 있습니다."),
        ("reimburse", "변제하다, 환급하다", "verb", "reimburse expenses / fully reimburse", "refund / repay / compensate",
         "Submit scanned copies of restaurant receipts to be reimbursed for client business dinners.", "고객 접대 식사 비용을 환급받으시려면 식당 영수증 스캔본을 제출해 주시기 바랍니다."),
        ("lucrative", "수익성이 좋은, 돈벌이가 되는", "adj", "lucrative contract / lucrative market", "profitable / advantageous / gainful",
         "The boutique architecture consultancy secured a lucrative contract to redesign the airport.", "그 부티크 건축 설계 사무소는 공항을 재설계하는 대단히 수익성 높은 알짜 계약을 수주했습니다."),
        ("feasible", "실현 가능한, 그럴싸한", "adj", "economically feasible / feasible plan", "viable / workable / practicable",
         "Constructing a high-speed bullet train spur was deemed financially feasible by auditors.", "고속열차 지선을 건설하는 계획은 회계 감사관들에 의해 재정적으로 실현 가능한 것으로 평가되었습니다."),
        ("stringent", "엄격한, 긴축의", "adj", "stringent regulations / stringent requirements", "strict / rigorous / tight",
         "Pharmaceutical plants are held to extraordinarily stringent sterile cleanroom standards.", "제약 생산 공장은 극도로 엄격하고 빈틈없는 멸균 클린룸 표준 규격을 준수해야 합니다."),
        ("scrutinize", "면밀히 조사하다, 정밀 검토하다", "verb", "scrutinize documents / carefully scrutinize", "examine / inspect / dissect",
         "Underwriters scrutinize five years of personal tax returns prior to releasing mortgage funds.", "주택담보대출금을 지급하기 전에 대출 심사관들은 5년간의 개인 세금 신고서를 면밀히 검토합니다."),
        ("exemplary", "모범적인, 본보기가 되는", "adj", "exemplary performance / exemplary service", "model / outstanding / commendable",
         "The customer care representative was awarded a bonus for her exemplary handling of crises.", "그 고객 지원 상담원은 위기 상황에서의 모범적인 대처 능력을 인정받아 특별 보너스를 받았습니다."),
        ("paramount", "가장 중요한, 최고의", "adj", "of paramount importance / paramount concern", "supreme / primary / vital",
         "Worker personal safety on the construction deck remains of paramount corporate importance.", "건설 현장 작업자의 개인 안전은 회사에서 가장 중요하게(최우선으로) 여기는 가치입니다."),
        ("detrimental", "해로운, 유해한", "adj", "detrimental effect / detrimental to health", "harmful / damaging / adverse",
         "Prolonged factory floor noise without acoustic ear muffs is detrimental to hearing health.", "소음 방지 귀마개 없이 공장 작업장의 소음에 장기간 노출되는 것은 청력 건강에 대단히 해롭습니다."),
        ("mandatory", "의무적인, 필수의", "adj", "mandatory attendance / mandatory training", "compulsory / obligatory / required",
         "Attendance at Friday's fire evacuation safety orientation is mandatory for all personnel.", "금요일에 진행되는 소방 대피 안전 교육에는 모든 임직원의 참석이 의무화되어 있습니다."),
        ("impeccable", "흠잡을 데 없는, 완벽한", "adj", "impeccable timing / impeccable credentials", "flawless / spotless / faultless",
         "The candidate's impeccable academic background and fluency in Japanese impressed the interviewers.", "지원자의 흠잡을 데 없는 완벽한 학력과 유창한 일본어 구사 능력은 면접관들에게 깊은 인상을 남겼습니다."),
        ("alleviate", "완화하다, 덜다", "verb", "alleviate congestion / alleviate pain", "relieve / ease / lessen",
         "Constructing an elevated expressway flyover will alleviate rush-hour downtown gridlock.", "고가 고속도로를 건설하면 출퇴근 시간대 도심 교통 정체를 크게 완화할 수 있을 것입니다."),
        ("discretionary", "자유재량의, 임의의", "adj", "discretionary spending / discretionary budget", "optional / voluntary / flexible",
         "Department directors hold discretionary authority to disburse small spot performance bonuses.", "부서장들은 소액의 즉석 성과 보너스를 지급할 수 있는 독자적인 자유재량 권한을 보유합니다."),
        ("adversely", "불리하게, 부정적으로", "adj", "adversely affect / adversely impacted", "negatively / unfavorably / harmfully",
         "Skyrocketing freight shipping charges adversely affected fourth-quarter profit margins.", "치솟는 해상 화물 운임 요금은 4분기 순이익률에 부정적인(불리한) 영향을 미쳤습니다."),
        ("unanimously", "만장일치로", "adv", "voted unanimously / unanimously approved", "with one voice / solid",
         "The municipal council voted unanimously to designate the historic theater a protected landmark.", "시의회는 유서 깊은 극장을 보호 기념 문화재로 지정하는 안을 만장일치로 가결했습니다."),
        ("reluctant", "꺼리는, 주저하는", "adj", "reluctant to commit / reluctant to invest", "unwilling / hesitant / disinclined",
         "Due to economic volatility, conservative institutional lenders are reluctant to finance projects.", "경기 불확실성으로 인해 보수적인 금융 대출 기관들은 대형 프로젝트 자금 지원을 꺼리고 있습니다."),
        ("complimentary", "무료의, 칭찬하는", "adj", "complimentary shuttle / complimentary breakfast", "free / gratis / at no cost",
         "Hotel guests enjoy complimentary high-speed optical fiber internet throughout the facilities.", "호텔 투숙객들은 전 시설에서 무료 초고속 광섬유 인터넷을 마음껏 즐기실 수 있습니다."),
        ("subsequent", "그 후의, 차후의", "adj", "subsequent to the meeting / subsequent events", "following / ensuing / successive",
         "Subsequent investigations revealed that a loose conveyor belt triggered the equipment jam.", "그 후의 정밀 조사 결과 느슨해진 컨베이어 벨트가 장비 걸림 사고를 유발했던 것으로 밝혀졌습니다."),
        ("unprecedented", "전례 없는, 유례없는", "adj", "unprecedented success / unprecedented scale", "unrivaled / unmatched",
         "The biotech firm achieved unprecedented success in engineering targeted antibodies.", "그 바이오 기업은 표적 항체를 설계하는 연구에서 유례없는 눈부신 성공을 거두었습니다."),
        ("imperative", "반드시 해야 하는, 필수적인; 긴요한 과제", "adj", "imperative that / business imperative", "vital / essential / urgent",
         "It is imperative that all field audit reports be delivered to compliance by 5:00 PM.", "모든 현장 감사 보고서가 오후 5시까지 준법감시팀에 제출되는 것은 절대적으로 필수적인 사항입니다."),
        ("lucrative", "유리한, 짭짤한", "adj", "lucrative agreement / lucrative career", "rewarding / profitable",
         "Specializing in patent law proved to be a highly lucrative career path for the attorney.", "특허법을 전문으로 다루는 것은 그 변호사에게 매우 높은 수익을 안겨주는 진로임이 입증되었습니다."),
        ("negligible", "무시해도 될 정도의, 하찮은", "adj", "negligible impact / negligible cost", "insignificant / minor / trivial",
         "The slight increase in carton shipping postage had a negligible impact on overall earnings.", "상자 배송 우편료의 소폭 인상은 전체 순이익에 무시해도 될 만큼 미미한 영향을 미쳤습니다."),
        ("appraise", "살피다, 평가하다", "verb", "appraise performance / accurately appraise", "assess / evaluate / rate",
         "Supervisors meet with department subordinates twice annually to appraise work performance.", "관리자들은 업무 성과를 평가(고과)하기 위해 부서 부하 직원들과 연 2회 정기 면담을 갖습니다."),
        ("receptive", "수용적인, 잘 받아들이는", "adj", "receptive to feedback / highly receptive", "open-minded / responsive / welcoming",
         "Senior leadership was exceptionally receptive to the employee proposals on flexible telework.", "최고 경영진은 유연 재택근무에 관한 직원들의 개선 제안을 대단히 열린 마음으로 수용했습니다."),
        ("substantial", "상당한, 실질적인", "adj", "substantial increase / substantial savings", "significant / considerable / sizable",
         "Transitioning to LED lighting generated substantial savings on quarterly utility invoices.", "LED 조명으로 전면 교체하여 분기별 전기 공과금 청구서에서 상당한 비용 절감을 달성했습니다."),
        ("provisional", "임시의, 일시적인", "adj", "provisional license / provisional results", "temporary / interim / tentative",
         "Inspectors issued a provisional occupancy certificate while minor fire sprinklers were fixed.", "경미한 소방 스프링클러 배관이 수리되는 동안 점검관들은 임시 입주 허가증을 발급했습니다."),
        ("unanimous", "만장일치의", "adj", "unanimous consent / unanimous resolution", "undisputed / harmonious",
         "With the unanimous consent of the shareholder assembly, the stock split was authorized.", "주주총회의 만장일치 찬성 동의를 얻어 주식 액면분할이 공식 승인되었습니다."),
        ("commensurate", "걸맞은, 비례하는", "adj", "commensurate rewards / commensurate pay", "proportionate / matching",
         "Top-performing sales agents receive quarterly cash rewards commensurate with their quota output.", "최고의 실적을 올린 영업사원들은 초과 달성한 목표치에 걸맞은 분기별 현금 포상을 받습니다."),
        ("impeccable", "결점 없는, 훌륭한", "adj", "impeccable craftsmanship / impeccable taste", "flawless / immaculate",
         "The luxury limousine interior was appointed with handcrafted Italian leather of impeccable quality.", "고급 리무진 내부는 흠잡을 데 없는 최상의 품질을 자랑하는 이탈리아 수제 가죽으로 꾸며졌습니다.")
    ])
}

print("Part 3 loaded successfully (Days 21 to 30)")
