#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TOEIC 1000 Vocab Part 1: Days 1 to 10 (~340 words)
"""

DAYS_1_TO_10 = {
    # DAY 1: 채용 및 구직 (34 words)
    1: ("인사/채용", "620도약", [
        ("applicant", "지원자, 신청자", "noun", "prospective applicant / qualified applicant", "candidate / job seeker", 
         "All applicants must submit their portfolios before the end of this week.", "모든 지원자는 이번 주 말까지 포트폴리오를 제출해야 합니다."),
        ("candidate", "후보자, 지원자", "noun", "ideal candidate / shortlisted candidate", "applicant / prospective hire",
         "The search committee selected the top three candidates for final interviews.", "선발 위원회는 최종 면접을 위해 상위 3명의 후보자를 선정했습니다."),
        ("qualified", "자격이 있는, 적임의", "adj", "highly qualified / fully qualified", "eligible / competent / certified",
         "We are looking for a highly qualified accountant to head our fiscal division.", "우리는 재무 부서를 이끌 고도로 자격을 갖춘 회계사를 찾고 있습니다."),
        ("vacancy", "공석, 빈자리", "noun", "fill a vacancy / job vacancy", "opening / unfilled position",
         "The human resources department announced an unexpected vacancy in the legal branch.", "인사부는 법무 부서에 예상치 못한 공석이 생겼다고 발표했습니다."),
        ("credential", "자격 요건, 경력 증명서", "noun", "impressive credentials / verify credentials", "qualification / license / certification",
         "The hiring director requested copies of his academic and professional credentials.", "채용 담당 이사는 그의 학력 및 경력 증명서 사본을 요청했습니다."),
        ("probation", "수습 기간, 시험 채용", "noun", "probationary period / on probation", "trial period / testing phase",
         "New recruits undergo a three-month probation before receiving permanent status.", "신입 사원들은 정규직 전환 전 3개월간의 수습 기간을 거칩니다."),
        ("screening", "서류 심사, 선발 검사", "noun", "initial screening / background screening", "evaluation / vetting / assessment",
         "The initial candidate screening will be completed by the end of this Friday.", "1차 후보자 서류 심사는 이번 주 금요일까지 완료될 예정입니다."),
        ("recruit", "채용하다, 모집하다; 신입 사원", "verb", "recruit talented personnel / actively recruit", "hire / enlist / employ",
         "The tech enterprise launched a nationwide campaign to recruit software developers.", "그 IT 기업은 소프트웨어 개발자를 모집하기 위해 전국적인 캠페인을 시작했습니다."),
        ("interviewee", "면접 대상자, 피면접자", "noun", "interviewee feedback / prospective interviewee", "applicant / candidate",
         "Each interviewee will be asked standard situational questions by the panel.", "각 면접 대상자는 면접관 패널로부터 표준 상황별 질문을 받게 됩니다."),
        ("interview", "면접하다; 면접, 인터뷰", "noun", "conduct an interview / follow-up interview", "meeting / screening session",
         "The final interview is scheduled with the managing director on Tuesday.", "최종 면접은 화요일에 상무이사와 진행될 예정입니다."),
        ("orientation", "신입 사원 교육, 오리엔테이션", "noun", "orientation session / employee orientation", "induction / introduction program",
         "All newly hired employees are required to attend the orientation session tomorrow.", "새로 채용된 모든 직원은 내일 오리엔테이션 세션에 참석해야 합니다."),
        ("personnel", "직원, 전 직원; 인사과", "noun", "personnel department / authorized personnel", "staff / workforce / human resources",
         "Only authorized personnel are permitted inside the server maintenance vault.", "오직 인가된 직원만이 서버 유지보수실 내부 출입이 허가됩니다."),
        ("headhunt", "스카우트하다, 인재를 발굴하다", "verb", "headhunt top talent / be headhunted by", "scout / recruit / hire away",
         "Our new chief financial officer was headhunted from an international competitor.", "우리의 새 최고재무책임자는 글로벌 경쟁사로부터 스카우트되었습니다."),
        ("apprentice", "수습생, 견습생", "noun", "skilled apprentice / apprentice program", "trainee / intern / novice",
         "The engineering firm accepted twenty apprentices for hands-on factory training.", "그 엔지니어링 회사는 실무 공장 교육을 위해 20명의 견습생을 받아들였습니다."),
        ("shortlist", "최종 후보자 명단", "noun", "draw up a shortlist / be on the shortlist", "selection list / finalist roster",
         "The committee drew up a shortlist of four applicants for the position of art director.", "위원회는 아트 디렉터 직책을 위해 4명의 지원자로 구성된 최종 후보 명단을 작성했습니다."),
        ("stipend", "급료, 수당, 장학금", "noun", "monthly stipend / receive a stipend", "allowance / subsidy / per diem",
         "Interns receive a modest monthly stipend to cover public transportation costs.", "인턴들은 대중교통 비용을 충당하기 위해 약간의 월 수당을 지급받습니다."),
        ("eligible", "자격이 있는, ~할 자격이 되는", "adj", "be eligible for promotion / eligible applicant", "qualified / entitled / suitable",
         "Employees with two consecutive years of service are eligible for tuition assistance.", "2년 연속 근속한 직원은 학자금 지원을 받을 자격이 있습니다."),
        ("prerequisite", "필수 조건, 전제 조건", "noun", "prerequisite for the position / essential prerequisite", "requirement / precondition",
         "Proficiency in spreadsheet applications is an absolute prerequisite for this role.", "스프레드시트 소프트웨어 능숙도는 이 직무의 절대적인 필수 조건입니다."),
        ("recommendation", "추천, 추천서", "noun", "letter of recommendation / strong recommendation", "endorsement / reference / testimonial",
         "She secured the promotion largely due to the strong recommendation from her team lead.", "그녀는 팀장의 강력한 추천 덕분에 주로 승진을 확정지었습니다."),
        ("designate", "지정하다, 지명하다", "verb", "designate a successor / designate parking areas", "appoint / assign / nominate",
         "Management decided to designate Mr. Kim as the lead coordinator for the expansion.", "경영진은 김 부장을 확장 프로젝트의 총괄 책임자로 지명하기로 결정했습니다."),
        ("appoint", "임명하다, 지명하다", "verb", "appoint a new director / formally appoint", "assign / designate / name",
         "The board of directors moved quickly to appoint an interim executive officer.", "이사회는 임시 경영인을 신속히 임명하기로 결의했습니다."),
        ("assign", "배정하다, 맡기다", "verb", "assign tasks / assign responsibilities", "delegate / allocate / allot",
         "The supervisor will assign specific inspection routes to each technician.", "감독관은 각 기술자에게 구체적인 점검 경로를 배정할 것입니다."),
        ("delegate", "위임하다; 대표자", "verb", "delegate authority / international delegates", "assign / transfer / entrust",
         "Effective managers know how to delegate repetitive duties to team members.", "유능한 관리자는 반복적인 업무를 팀원들에게 위임하는 방법을 잘 알고 있습니다."),
        ("headquarters", "본사, 본부", "noun", "relocate the headquarters / corporate headquarters", "main office / home office",
         "The senior team was summoned to the corporate headquarters in Chicago for talks.", "임원진은 회담을 위해 시카고 본사로 소집되었습니다."),
        ("probationary", "수습의, 시험적인", "adj", "probationary employee / probationary period", "trial / provisional / temporary",
         "During the probationary period, work output is reviewed on a biweekly basis.", "수습 기간 동안 업무 성과는 격주 단위로 검토됩니다."),
        ("prospect", "유망한 후보, 전망, 가망", "noun", "job prospect / prospective hire", "potential / outlook / candidate",
         "The agency evaluated several top prospects before extending a contract offer.", "그 대행사는 계약 제의를 전달하기 전에 몇몇 최우수 유망 후보를 평가했습니다."),
        ("reference", "추천인, 참고 문헌, 언급", "noun", "check references / provide three references", "recommendation / testimonial / referee",
         "HR agents contacted all professional references to verify previous employment.", "인사 담당자는 이전 근무 기록을 확인하기 위해 모든 전문 추천인에게 연락했습니다."),
        ("competence", "역량, 능력", "noun", "demonstrate competence / core competence", "ability / capability / proficiency",
         "The candidate demonstrated exceptional linguistic competence during the oral test.", "후보자는 구술 테스트에서 뛰어난 언어적 역량을 입증했습니다."),
        ("receptive", "수용적인, 잘 받아들이는", "adj", "receptive to feedback / receptive attitude", "open / responsive / amenable",
         "The newly appointed department head proved remarkably receptive to staff suggestions.", "새로 임명된 부서장은 직원들의 제안을 매우 잘 받아들이는 태도를 보였습니다."),
        ("tenure", "재임 기간, 재직 기간", "noun", "during his tenure / secure tenure", "term of office / incumbency",
         "During her five-year tenure, the firm saw an unprecedented 40% growth in profits.", "그녀의 5년 재임 기간 동안 회사는 전례 없는 40%의 이익 성장을 기록했습니다."),
        ("appraisal", "평가, 감정, 사정", "noun", "performance appraisal / property appraisal", "evaluation / assessment / review",
         "Annual performance appraisals determine year-end bonuses and rank advancements.", "연례 인사 평가는 연말 보너스와 승진 순위를 결정합니다."),
        ("remuneration", "보수, 급여", "noun", "competitive remuneration / remuneration package", "compensation / salary / wage",
         "The enterprise offers a handsome remuneration package including stock options.", "그 기업은 스톡옵션을 포함한 매력적인 보수 패키지를 제공합니다."),
        ("background", "배경, 이력, 경력", "noun", "extensive background / educational background", "experience / history / credentials",
         "The applicant has an extensive background in both international law and logistics.", "해당 지원자는 국제법과 물류 분야 모두에서 풍부한 경력을 갖추고 있습니다."),
        ("hire", "고용하다, 채용하다; 신입 사원", "verb", "hire new staff / new hire", "employ / recruit / take on",
         "The company intends to hire twenty additional customer service representatives.", "회사는 20명의 고객 서비스 상담원을 추가로 채용할 계획입니다.")
    ]),

    # DAY 2: 근무 조건 및 사내 복지 (34 words)
    2: ("인사/채용", "620도약", [
        ("compensation", "보상, 급여, 배상", "noun", "compensation package / financial compensation", "remuneration / salary / payment",
         "The compensation package includes health coverage and annual performance dividends.", "급여 보상 패키지에는 건강보험과 연간 성과 배당금이 포함됩니다."),
        ("benefit", "복리후생, 혜택; 이익을 얻다", "noun", "employee benefits / fringe benefits", "perk / advantage / welfare",
         "A comprehensive benefits package is provided to all full-time corporate staff.", "모든 정규직 기업 직원에게 포괄적인 복리후생 패키지가 제공됩니다."),
        ("perk", "특전, 부가 혜택", "noun", "attractive perks / corporate perks", "benefit / privilege / bonus",
         "Free gym memberships and catered lunches are among the popular office perks.", "무료 피트니스 회원권과 구내 점심 식사는 인기 있는 사내 특전 중 하나입니다."),
        ("severance", "퇴직금, 고용 계약 종료", "noun", "severance pay / severance package", "termination pay / dismissal allowance",
         "Employees impacted by the restructuring were awarded six months of severance pay.", "구조조정의 영향을 받은 직원들에게 6개월 치의 퇴직금이 지급되었습니다."),
        ("pension", "연금", "noun", "pension plan / retirement pension", "annuity / retirement fund",
         "The corporation matches up to 5 percent of employee contributions to the pension fund.", "회사는 연금 기금에 대한 직원의 납입금 중 최대 5%까지 매칭 지원합니다."),
        ("leave", "휴가; 떠나다", "noun", "paid leave / maternity leave / sick leave", "vacation / time off / absence",
         "Staff members are entitled to fifteen working days of paid annual leave.", "직원들은 연간 15일의 유급 연차 휴가를 누릴 자격이 주어집니다."),
        ("overtime", "초과 근무, 야근; 시간 외로", "noun", "work overtime / overtime pay", "extra hours / after-hours duty",
         "All overtime must be approved in advance by the respective department director.", "모든 초과 근무는 각 부서장에게 사전 승인을 받아야 합니다."),
        ("telecommute", "재택근무하다, 원격 근무하다", "verb", "telecommute twice a week / telecommuting policy", "work remotely / work from home",
         "The revised guidelines permit senior software architects to telecommute full-time.", "개정된 가이드라인은 수석 소프트웨어 아키텍트의 전면 재택근무를 허용합니다."),
        ("flexitime", "탄력 근무제, 유연 근무제", "noun", "operate on flexitime / flexitime schedule", "flexible hours / variable schedule",
         "Adopting flexitime significantly improved employee satisfaction and punctuality.", "탄력 근무제 도입은 직원의 만족도와 근태 준수율을 크게 향상시켰습니다."),
        ("absenteeism", "잦은 결근, 무단결근", "noun", "reduce absenteeism / chronic absenteeism", "truancy / habitual absence",
         "The wellness initiative was launched primarily to curb workplace absenteeism.", "웰빙 프로그램은 직장 내 잦은 결근을 억제하기 위해 주로 시작되었습니다."),
        ("tardiness", "지각", "noun", "unexcused tardiness / chronic tardiness", "lateness / unpunctuality",
         "Repeated tardiness without valid medical notice may lead to disciplinary measures.", "정당한 병가 통보 없는 반복적 지각은 징계 조치로 이어질 수 있습니다."),
        ("grievance", "고충, 불만", "noun", "file a grievance / address grievances", "complaint / objection / dispute",
         "Employees are encouraged to file a formal grievance if workplace harassment occurs.", "직장 내 괴롭힘 발생 시 정식 고충 접수를 신청하도록 권장됩니다."),
        ("morale", "사기, 의욕", "noun", "boost employee morale / high morale", "spirit / confidence / motivation",
         "The leadership retreat was planned expressly to boost team morale after the audit.", "리더십 수련회는 감사 이후 팀의 사기를 북돋우기 위해 명시적으로 기획되었습니다."),
        ("incentive", "장려금, 보상 인센티브", "noun", "performance incentive / financial incentive", "bonus / motivation / reward",
         "Sales managers receive generous financial incentives upon surpassing quarterly targets.", "영업 관리자들은 분기별 목표치를 초과 달성할 시 후한 성과 인센티브를 받습니다."),
        ("allowance", "수당, 지급액, 허용치", "noun", "housing allowance / travel allowance", "stipend / subsidy / budget",
         "Expatriate executives are provided with a monthly residential housing allowance.", "해외 파견 임원에게는 월별 주택 거주 수당이 제공됩니다."),
        ("reimbursement", "환급, 변제", "noun", "expense reimbursement / prompt reimbursement", "refund / repayment / compensation",
         "Submit all original dinner receipts within thirty days to ensure reimbursement.", "환급을 받으시려면 30일 이내에 모든 저녁 식사 영수증 원본을 제출하십시오."),
        ("payroll", "급여 명부, 총급여", "noun", "payroll department / on the payroll", "wages / salary ledger / employee roster",
         "The firm added thirty full-time software engineers to its monthly payroll.", "회사는 월간 급여 명부에 30명의 정규직 소프트웨어 엔지니어를 추가했습니다."),
        ("deduction", "공제, 차감", "noun", "tax deduction / payroll deduction", "withholding / discount / subtraction",
         "Health insurance premiums are automatically withheld via monthly payroll deduction.", "건강보험료는 매월 급여 공제를 통해 자동으로 원천징수됩니다."),
        ("gross", "총, 총계의; 총수익을 올리다", "adj", "gross income / gross salary", "total / overall / before tax",
         "His gross annual salary is seventy thousand dollars prior to state tax withholdings.", "그의 세전 총연봉은 주세 원천징수 전 기준으로 7만 달러입니다."),
        ("net", "순, 순수한 (세후)", "adj", "net profit / net earnings / net pay", "take-home / after tax / clear",
         "The contract specifies the exact net salary to be transferred each calendar month.", "계약서에는 매달 입금될 정확한 실수령 세후 순급여액이 명시되어 있습니다."),
        ("shift", "교대 근무, 교대 조; 이동하다", "noun", "night shift / rotating shift", "work period / roster / stint",
         "Workers on the overnight shift receive a fifteen percent differential wage premium.", "야간 교대 조 근무자들은 15%의 추가 임금 할증을 지급받습니다."),
        ("roster", "근무자 명단, 당번표", "noun", "duty roster / staffing roster", "schedule / rota / timetable",
         "The clinic supervisor posted the revised weekly nurse roster on the staff board.", "병원 관리자는 직원 게시판에 수정된 주간 간호사 근무 당번표를 게시했습니다."),
        ("resignation", "사직, 사임; 사직서", "noun", "tender one's resignation / accept a resignation", "departure / stepping down / notice",
         "The chief executive handed in his resignation following the contentious merger.", "대표이사는 논란이 된 합병 이후 사직서를 제출했습니다."),
        ("notice", "통지, 예고, 사직 통보", "noun", "two weeks' notice / give advance notice", "notification / warning / announcement",
         "Standard employment agreements demand at least four weeks of written notice.", "표준 고용 계약서는 최소 4주의 서면 사직 통보를 요구합니다."),
        ("retire", "은퇴하다, 퇴직하다", "verb", "retire from public service / retire early", "step down / leave work / withdraw",
         "After thirty-five dedicated years, the vice president will retire next month.", "35년간 헌신적인 근무 후, 부사장은 다음 달 은퇴할 예정입니다."),
        ("annuity", "연금, 연금 보험", "noun", "lifetime annuity / fixed annuity", "pension / regular payment",
         "Retirees may elect to receive their retirement savings as an ongoing monthly annuity.", "퇴직자는 퇴직 저축을 지속적인 월별 연금 형태로 수령하도록 선택할 수 있습니다."),
        ("workplace", "직장, 업무 장소", "noun", "safe workplace / workplace environment", "office / premises / jobsite",
         "Management implemented ergonomic workstations to improve workplace well-being.", "경영진은 직장 내 웰빙을 개선하기 위해 인체공학적 워크스테이션을 도입했습니다."),
        ("ergonomic", "인체공학의", "adj", "ergonomic keyboard / ergonomic office chair", "user-friendly / bodily comfortable",
         "Investing in ergonomic furniture proved effective at reducing back fatigue.", "인체공학적 가구에 대한 투자는 허리 피로를 줄이는 데 효과적임이 입증되었습니다."),
        ("wellness", "건강, 웰빙", "noun", "wellness program / corporate wellness", "well-being / fitness / healthiness",
         "The corporate wellness program features subsidized memberships to local gyms.", "사내 웰빙 프로그램은 지역 체육관에 대한 보조금 지원 혜택을 특징으로 합니다."),
        ("subsidize", "보조금을 지급하다", "verb", "subsidize tuition / heavily subsidized", "fund / sponsor / underwrite",
         "The company agrees to subsidize commuter passes up to seventy dollars per month.", "회사는 통근 대중교통 카드를 매월 최대 70달러까지 보조하기로 합의했습니다."),
        ("mandatory", "의무적인, 필수의", "adj", "mandatory training / mandatory compliance", "obligatory / compulsory / required",
         "Attendance at the annual workplace safety workshop is strictly mandatory for all.", "연례 직장 안전 워크숍 참석은 전 직원에게 엄격히 의무적입니다."),
        ("voluntary", "자발적인, 임의의", "adj", "voluntary severance / voluntary contribution", "optional / elective / willing",
         "The corporation proposed a voluntary severance scheme for senior managers.", "기업은 고위 관리자를 대상으로 자발적 명예퇴직 제도를 제안했습니다."),
        ("punctual", "시간을 잘 지키는", "adj", "punctual arrival / be extremely punctual", "on time / prompt / reliable",
         "Consistently punctual employees are prioritized for prestigious overseas assignments.", "지속적으로 시간을 엄수하는 직원들은 명망 높은 해외 파견 근무에서 우선 고려됩니다."),
        ("attendance", "출석, 근태, 참석자 수", "noun", "perfect attendance / record attendance", "presence / turnout / participation",
         "Mr. Gomez was honored with an award for maintaining perfect attendance this year.", "고메즈 씨는 올해 개근(완벽한 근태)을 유지한 공로로 표창을 받았습니다.")
    ]),

    # DAY 3: 사내 조직 및 업무 관리 (34 words)
    3: ("사내 조직/관리", "620도약", [
        ("streamline", "간소화하다, 능률화하다", "verb", "streamline operations / streamline workflow", "simplify / optimize / modernize",
         "The new cloud platform was deployed to streamline global purchase order approvals.", "새 클라우드 플랫폼은 글로벌 구매 발주서 승인을 간소화하기 위해 도입되었습니다."),
        ("oversee", "감독하다, 총괄하다", "verb", "oversee daily operations / oversee the project", "supervise / manage / direct",
         "Ms. Watson was recruited to oversee the construction of the overseas research hub.", "왓슨 씨는 해외 연구 허브 기지 건설을 총괄 감독하기 위해 영입되었습니다."),
        ("supervise", "지도하다, 관리하다", "verb", "supervise subordinate staff / closely supervise", "oversee / monitor / inspect",
         "Experienced technicians supervise interns throughout the machinery assembly drills.", "노련한 기술자들이 기계 조립 훈련 내내 인턴들을 면밀히 지도합니다."),
        ("coordinate", "조정하다, 조율하다", "verb", "coordinate schedules / coordinate cross-team efforts", "organize / harmonize / align",
         "The event planner must coordinate catering, audiovisual setups, and guest lodging.", "행사 기획자는 출장 뷔페, 시청각 장비 설치 및 고객 숙소를 조율해야 합니다."),
        ("restructure", "구조조정하다, 개편하다", "verb", "restructure corporate divisions / financial restructuring", "reorganize / overhaul / remodel",
         "The enterprise decided to restructure its sales divisions to respond faster to market shifts.", "기업은 시장 변화에 더 빠르게 대응하기 위해 영업 부서를 개편하기로 결정했습니다."),
        ("implement", "시행하다, 이행하다", "verb", "implement new policies / successfully implement", "execute / carry out / enforce",
         "We intend to implement stricter password protocols starting next Monday morning.", "우리는 다음 주 월요일 아침부터 더 엄격한 암호 보안 프로토콜을 시행할 계획입니다."),
        ("facilitate", "촉진하다, 원활하게 하다", "verb", "facilitate discussions / facilitate communication", "assist / ease / expedite",
         "The open-plan layout was explicitly chosen to facilitate spontaneous collaboration.", "열린 사무실 배치는 자발적인 협업을 촉진하기 위해 명시적으로 선택되었습니다."),
        ("prioritize", "우선순위를 매기다, 우선시하다", "verb", "prioritize critical tasks / prioritize safety", "rank / give precedence to",
         "Customer service managers must prioritize resolving unresolved billing discrepancies.", "고객 지원팀 관리자는 해결되지 않은 청구서 불일치를 우선적으로 해결해야 합니다."),
        ("delegate", "위임하다; 대표 파견원", "verb", "delegate authority / delegate responsibility", "assign / transfer / entrust",
         "Leadership development seminars teach executives how to delegate operational duties.", "리더십 개발 세미나는 임원들에게 운영 업무를 위임하는 방법을 가르칩니다."),
        ("subordinate", "하급자, 부하 직원; 종속된", "noun", "treat subordinates fairly / direct subordinate", "junior / employee / assistant",
         "An empathetic director solicits candid opinions from both peers and subordinates.", "공감 능력이 뛰어난 이사는 동료와 부하 직원 모두로부터 솔직한 의견을 구합니다."),
        ("superior", "상급자; 우수한, 우월한", "noun", "report to a superior / superior quality", "boss / manager / supervisor",
         "All formal expense authorization forms must be signed by an immediate superior.", "모든 공식 비용 승인 양식은 직속 상급자의 서명을 받아야 합니다."),
        ("hierarchy", "계층 구조, 위계 서열", "noun", "corporate hierarchy / rigid hierarchy", "chain of command / pecking order",
         "The startup flattened its management hierarchy to foster rapid agile experimentation.", "그 스타트업은 신속한 애자일 실험을 촉진하기 위해 관리 계층 구조를 수평화했습니다."),
        ("benchmarking", "벤치마킹, 비교 평가", "noun", "benchmarking analysis / competitive benchmarking", "standardization / comparison",
         "Through careful benchmarking, the factory reduced cycle downtime by eighteen percent.", "정밀한 벤치마킹을 통해 공장은 가동 중단 시간을 18% 줄였습니다."),
        ("overhaul", "철저한 점검, 전면 개편; 점검하다", "noun", "complete overhaul / machinery overhaul", "revamp / inspection / renovation",
         "The entire logistics management system underwent a comprehensive overhaul last year.", "전체 물류 관리 시스템은 작년에 포괄적인 전면 개편을 거쳤습니다."),
        ("initiative", "계획, 주도권, 진취성", "noun", "strategic initiative / take the initiative", "project / venture / campaign",
         "The CEO praised the regional team for launching the green packaging initiative.", "CEO는 친환경 포장 계획을 추진한 지역 팀을 칭찬했습니다."),
        ("milestone", "중요한 이정표, 단계적 목표", "noun", "reach a major milestone / key milestone", "achievement / turning point / breakthrough",
         "Finalizing the prototype ahead of schedule was a celebrated project milestone.", "일정보다 앞서 시제품을 완성한 것은 프로젝트의 축하할 만한 주요 이정표였습니다."),
        ("protocol", "행동 수칙, 프로토콜, 의전", "noun", "security protocol / safety protocol", "rules / code / guidelines / procedure",
         "Strict adherence to sanitary protocols is mandatory throughout the laboratory cleanroom.", "실험실 클린룸 전체에서 위생 수칙의 엄격한 준수가 필수적입니다."),
        ("procedure", "절차, 순서, 규정", "noun", "standard operating procedure / emergency procedure", "process / method / steps",
         "Employees are reminded to observe official travel authorization procedures.", "직원들은 공식 출장 승인 절차를 준수해야 함을 다시 한번 상기하시기 바랍니다."),
        ("collaborate", "협력하다, 공동 작업하다", "verb", "collaborate with teams / closely collaborate", "cooperate / work together / partner",
         "Engineers will collaborate with external designers to build the electric vehicle chassis.", "엔지니어들은 전기차 차체 제작을 위해 외부 디자이너들과 긴밀히 협력할 것입니다."),
        ("liaison", "연락 담당자, 소통 창구", "noun", "serve as a liaison / act as liaison", "intermediary / contact / coordinator",
         "Mr. Tanaka serves as the primary liaison between our Tokyo branch and Seoul HQ.", "다나카 씨는 도쿄 지사와 서울 본사 사이의 주요 연락 담당자로 일하고 있습니다."),
        ("empower", "권한을 부여하다", "verb", "empower frontline workers / empower staff", "authorize / enable / permit",
         "The corporate charter seeks to empower branch managers to resolve refund disputes.", "회사 정관은 지점장들이 환불 분쟁을 직접 해결할 수 있도록 권한을 부여하고자 합니다."),
        ("appraise", "평가하다, 감정하다", "verb", "appraise employee performance / appraise assets", "evaluate / assess / judge",
         "Department directors meet quarterly to appraise staff contribution toward milestones.", "부서장들은 분기별로 모여 목표 달성을 향한 직원들의 기여도를 평가합니다."),
        ("commend", "칭찬하다, 표창하다", "verb", "commend for outstanding work / highly commend", "praise / applaud / compliment",
         "The hospital superintendent commended the nursing staff for their tireless devotion.", "병원장은 지칠 줄 모르는 헌신을 보여준 간호 인력을 표창했습니다."),
        ("exemplary", "모범적인, 귀감이 되는", "adj", "exemplary performance / exemplary leadership", "model / outstanding / commendable",
         "Ms. Diaz was honored with an award for her exemplary leadership during the crisis.", "디아즈 씨는 위기 상황에서 보여준 모범적인 리더십으로 표창을 받았습니다."),
        ("merit", "공적, 장점, 가치", "noun", "promote based on merit / intrinsic merit", "excellence / worth / virtue",
         "Promotions within the multinational advisory firm are awarded strictly on merit.", "그 다국적 자문 회사 내에서의 승진은 전적으로 직무 성과와 능력(공적)에 따라 주어집니다."),
        ("demote", "강등시키다", "verb", "demote to a junior rank / be demoted", "downgrade / reduce in rank",
         "The manager was demoted following repeated violations of workplace ethics.", "그 관리자는 사내 윤리 규범을 반복적으로 위반한 후 하위 직급으로 강등되었습니다."),
        ("dismiss", "해고하다, 기각하다", "verb", "dismiss an employee / dismiss allegations", "fire / discharge / terminate",
         "The arbitration board voted to dismiss the contractor's appeal without merit.", "중재 위원회는 계약업체의 이유 없는 항소를 기각하기로 투표했습니다."),
        ("relocate", "이전하다, 재배치하다", "verb", "relocate to the regional hub / corporate relocation", "move / transfer / resettle",
         "The design studio will relocate to modern loft quarters in downtown Seattle.", "디자인 스튜디오는 시애틀 시내의 현대적인 로프트 사옥으로 이전할 예정입니다."),
        ("transfer", "전근시키다, 이동하다; 전근", "verb", "transfer to another division / bank transfer", "relocate / move / shift",
         "He requested a formal transfer to the overseas marketing division in London.", "그는 런던에 있는 해외 마케팅 부서로의 공식 전근을 요청했습니다."),
        ("succession", "승계, 계승, 연속", "noun", "succession plan / in rapid succession", "continuation / inheritance / replacement",
         "The board enacted a clear leadership succession plan before the founder retired.", "이사회는 창업주가 은퇴하기 전에 명확한 리더십 승계 계획을 제정했습니다."),
        ("affiliate", "계열사, 자회사; 제휴하다", "noun", "corporate affiliate / overseas affiliate", "subsidiary / branch / partner",
         "Our European affiliate handles localized distribution across fourteen member nations.", "우리의 유럽 계열사는 14개 회원국 전역의 현지화된 유통을 총괄합니다."),
        ("subsidiary", "자회사; 부수적인", "noun", "wholly owned subsidiary / foreign subsidiary", "affiliate / branch / division",
         "The electronics giant launched a financial subsidiary to provide buyer loans.", "그 전자 대기업은 구매자 대출을 제공하기 위해 금융 자회사를 설립했습니다."),
        ("conglomerate", "대기업 복합체, 재벌", "noun", "multinational conglomerate / commercial conglomerate", "corporation / group / enterprise",
         "The conglomerate holds diversified assets in shipbuilding, logistics, and retail.", "그 복합 대기업은 조선, 물류, 소매업 전반에 걸쳐 다각화된 자산을 보유하고 있습니다."),
        ("executive", "임원, 경영진; 경영의", "noun", "chief executive officer / senior executive", "director / manager / leader",
         "The senior executive meeting convened behind closed doors to debate the bid.", "인수 입찰을 논의하기 위해 비공개로 고위 임원 회의가 소집되었습니다.")
    ]),

    # DAY 4: 비즈니스 운영 및 경영 전략 (34 words)
    4: ("비즈니스 운영", "800필수", [
        ("optimize", "최적화하다", "verb", "optimize performance / optimize supply chains", "maximize / improve / refine",
         "Automating invoice reconciliation allowed the firm to optimize financial throughput.", "청구서 대사 자동화를 통해 회사는 재무 처리 효율을 최적화할 수 있었습니다."),
        ("leverage", "활용하다; 지렛대 효과", "verb", "leverage core technology / financial leverage", "utilize / capitalize on / exploit",
         "The media brand plans to leverage its vast subscriber base to launch a streaming app.", "그 미디어 브랜드는 방대한 구독자 기반을 활용해 스트리밍 앱을 출시할 계획입니다."),
        ("feasible", "실행 가능한", "adj", "economically feasible / feasible solution", "viable / practical / workable",
         "Engineers concluded that building the solar array on the warehouse roof was feasible.", "엔지니어들은 창고 지붕에 태양광 설비를 구축하는 것이 기술적으로 실행 가능하다고 결론지었습니다."),
        ("contingency", "만일의 사태, 우발 사건", "noun", "contingency plan / prepare for contingencies", "backup plan / emergency / fallback",
         "Management drafted a contingency plan in case port strikes disrupt shipments.", "경영진은 항만 파업으로 선적이 중단될 경우에 대비해 비상 대책(만일의 사태 대비 계획)을 수립했습니다."),
        ("disruption", "차질, 붕괴, 지연", "noun", "supply chain disruption / service disruption", "interruption / disturbance / disorder",
         "Severe winter weather caused minor operational disruptions across Midwestern hubs.", "혹독한 겨울 날씨로 인해 중서부 거점 전역에서 경미한 운행 차질이 빚어졌습니다."),
        ("diversify", "다각화하다, 다양화하다", "verb", "diversify product lines / diversify investments", "broaden / expand / vary",
         "To mitigate economic volatility, the manufacturer sought to diversify its clients.", "경기 변동성을 완화하기 위해 그 제조사는 고객층을 다각화하고자 노력했습니다."),
        ("expansion", "확장, 팽창", "noun", "overseas expansion / aggressive expansion", "growth / enlargement / development",
         "The supermarket chain announced the aggressive expansion of twenty express stores.", "그 슈퍼마켓 체인은 20개 익스프레스 매장의 공격적인 확장을 발표했습니다."),
        ("consolidate", "통합하다, 강화하다", "verb", "consolidate shipments / consolidate market position", "merge / combine / unify",
         "The parcel service will consolidate regional distribution into one automated center.", "그 택배 서비스 회사는 지역 유통망을 하나의 자동화 물류센터로 통합할 것입니다."),
        ("venture", "모험적 사업, 벤처; 과감히 착수하다", "noun", "joint venture / commercial venture", "enterprise / undertaking / project",
         "The two telecommunication giants formed a lucrative joint venture to install 5G cables.", "두 통신 대기업은 5G 케이블을 가설하기 위해 수익성 높은 합작 투자 사업을 시작했습니다."),
        ("profitability", "수익성", "noun", "boost profitability / long-term profitability", "financial return / earnings power",
         "Cutting redundant administrative layers helped boost operating profitability by 12%.", "불필요한 관리 계층을 축소한 덕분에 영업 수익성을 12% 끌어올릴 수 있었습니다."),
        ("volatile", "변동성이 심한, 불안정한", "adj", "volatile stock market / volatile pricing", "unstable / erratic / fluctuating",
         "Trading commodities requires deep expertise due to volatile currency shifts.", "통화 환율의 심한 변동성 때문에 원자재 거래에는 깊은 전문성이 요구됩니다."),
        ("fluctuate", "변동하다, 요동치다", "verb", "prices fluctuate wildly / continuously fluctuate", "vary / oscillate / change",
         "Crude petroleum prices fluctuate based on geopolitical developments in the region.", "원유 가격은 해당 지역의 지정학적 상황 전개에 따라 요동칩니다."),
        ("sustainable", "지속 가능한, 친환경의", "adj", "sustainable growth / sustainable energy", "enduring / viable / eco-friendly",
         "Investors demand clear evidence of sustainable governance before releasing capital.", "투자자들은 자금을 집행하기 전에 지속 가능한 경영 체계에 대한 명확한 증거를 요구합니다."),
        ("surpass", "능가하다, 뛰어넘다", "verb", "surpass expectations / surpass quarterly targets", "exceed / outdo / beat",
         "Third-quarter electric vehicle deliveries surpassed the most optimistic projections.", "3분기 전기차 인도량은 가장 낙관적이었던 전망치를 뛰어넘었습니다."),
        ("exceed", "초과하다, 넘어서다", "verb", "exceed budget / exceed passenger capacity", "surpass / outstrip / go beyond",
         "The total refurbishment cost did not exceed the strict budget approved by the board.", "총 리모델링 비용은 이사회가 승인한 엄격한 예산 한도를 초과하지 않았습니다."),
        ("unprecedented", "전례 없는", "adj", "unprecedented growth / unprecedented success", "historic / groundbreaking / novel",
         "The brand enjoyed unprecedented subscriber demand upon releasing the mobile portal.", "그 브랜드는 모바일 포털 출시 즉시 전례 없는 구독자 수요를 누렸습니다."),
        ("stagnant", "침체된, 고여 있는", "adj", "stagnant economy / stagnant sales", "inactive / sluggish / sluggish",
         "Sales remained stagnant throughout the autumn quarter despite advertising outlays.", "광고비 지출에도 불구하고 가을 분기 내내 매출은 침체 상태를 면치 못했습니다."),
        ("sluggish", "부진한, 둔화된", "adj", "sluggish market demand / sluggish growth", "slow / stagnant / slack",
         "Retailers blamed sluggish consumer foot traffic on prolonged stormy weather.", "소매업체들은 장기화된 악천후로 인해 매장 방문객 수요가 둔화되었다고 지적했습니다."),
        ("robust", "탄탄한, 견고한", "adj", "robust financial health / robust growth", "strong / sturdy / resilient",
         "Despite global macroeconomic head winds, our balance sheet remains remarkably robust.", "글로벌 거시 경제의 역풍에도 불구하고 우리의 재무제표는 매우 견고하게 유지되고 있습니다."),
        ("resilient", "회복력 있는, 탄력적인", "adj", "resilient economy / resilient supply chain", "durable / adaptable / tough",
         "A resilient logistics infrastructure enables timely product delivery during crises.", "회복력 있는 물류 인프라 덕분에 위기 상황에서도 적시 제품 배송이 가능합니다."),
        ("turnaround", "호전, 흑자 전환, 반등", "noun", "remarkable turnaround / turnaround plan", "recovery / rebound / revival",
         "The new chief executive engineered an astonishing turnaround within just eighteen months.", "새 대표이사는 불과 18개월 만에 놀라운 경영 흑자 전환을 이뤄냈습니다."),
        ("downturn", "경기 하강, 침체", "noun", "economic downturn / market downturn", "recession / slump / decline",
         "Firms that maintain substantial liquid reserves can better survive a sudden downturn.", "상당한 유동성 유보금을 유지하는 기업들은 갑작스러운 경기 침체를 더 잘 버텨낼 수 있습니다."),
        ("slump", "급락하다, 침체되다; 불황", "verb", "profits slumped sharply / sales slump", "drop / plunge / plummet",
         "Commercial real estate investments slumped drastically following interest hikes.", "금리 인상 이후 상업용 부동산 투자가 급격히 침체되었습니다."),
        ("plummet", "곤두박질치다, 급락하다", "verb", "shares plummeted by 20% / plummet to new lows", "plunge / dive / tumble",
         "The airline's stock plummeted following the sudden cancellation of holiday flights.", "연휴 항공편의 갑작스러운 취소 사태 이후 항공사 주가가 곤두박질쳤습니다."),
        ("soar", "치솟다, 급증하다", "verb", "demand soared / prices soar", "skyrocket / surge / climb",
         "Consumer orders soared immediately after the televised product demonstration.", "TV 제품 시연 방송 직후 소비자 주문이 무섭게 치솟았습니다."),
        ("skyrocket", "급등하다, 치솟다", "verb", "revenues skyrocketed / costs skyrocket", "soar / surge / leap",
         "Shipping container leasing rates skyrocketed due to congested maritime canals.", "해상 운하의 정체로 인해 선적 컨테이너 임대료가 급등했습니다."),
        ("surge", "급증하다, 밀려들다; 급증", "noun", "surge in customer orders / power surge", "upswing / jump / spike",
         "Logistics managers hired temporary staff to handle the seasonal surge in freight.", "물류 관리자들은 계절적인 화물 급증을 처리하기 위해 임시 직원을 고용했습니다."),
        ("plateau", "안정기에 접어들다, 정체기", "noun", "reach a plateau / revenue plateau", "level off / stabilization",
         "After two years of meteoric adoption, user sign-ups reached a natural plateau.", "2년간의 폭발적인 도입기를 거친 후, 신규 사용자 가입은 자연스러운 안정기에 도달했습니다."),
        ("curtail", "축소하다, 줄이다", "verb", "curtail expenditures / curtail business travel", "reduce / cut back / trim",
         "The corporation was forced to curtail nonessential travel to protect cash reserves.", "기업은 현금 유보금을 보호하기 위해 불필요한 출장을 축소해야만 했습니다."),
        ("streamline", "합리화하다, 효율화하다", "verb", "streamline supply chains / streamline procurement", "rationalize / simplify",
         "The manufacturer relocated parts storage next to the assembly bay to streamline work.", "제조업체는 작업을 능률화하기 위해 조립 라인 바로 옆으로 부품 창고를 옮겼습니다."),
        ("outsource", "외주를 주다, 아웃소싱하다", "verb", "outsource customer support / outsource payroll", "contract out / farm out",
         "To focus on core software development, the startup opted to outsource server security.", "핵심 소프트웨어 개발에 집중하기 위해 그 스타트업은 서버 보안을 외주 처리하기로 결정했습니다."),
        ("synergy", "상승 효과, 시너지", "noun", "create synergies / organizational synergy", "cooperation / combined effect",
         "The merger generated massive operational synergies across mutual distribution channels.", "그 합병은 상호 유통 채널 전반에 걸쳐 막대한 운영 시너지 효과를 창출했습니다."),
        ("concur", "동의하다, 의견이 일치하다", "verb", "concur with the assessment / fully concur", "agree / coincide / assent",
         "All executive board members concurred that aggressive Asian expansion was warranted.", "모든 이사회 구성원은 공격적인 아시아 진출이 타당하다는 점에 만장일치로 동의했습니다."),
        ("unanimous", "만장일치의, 전원 합의의", "adj", "unanimous decision / unanimous approval", "undisputed / agreed by all",
         "The committee reached a unanimous consensus to adopt the revised emission targets.", "위원회는 수정된 탄소 배출 목표를 채택하기로 만장일치 합의에 도달했습니다.")
    ]),

    # DAY 5: 재무 회계 및 예산 감사 (34 words)
    5: ("재무/회계", "800필수", [
        ("audit", "회계 감사; 감사하다", "noun", "internal audit / independent financial audit", "inspection / review / scrutiny",
         "The external accounting firm completed an independent financial audit of the firm.", "외부 회계 법인은 해당 기업에 대한 독립적인 재무 회계 감사를 완료했습니다."),
        ("expenditure", "지출, 비용, 경비", "noun", "capital expenditure / annual expenditure", "spending / outlay / expenses",
         "Approved capital expenditures for the cleanroom upgrade total twelve million dollars.", "클린룸 업그레이드를 위해 승인된 자본 지출 총액은 1,200만 달러에 달합니다."),
        ("revenue", "수익, 세입", "noun", "generate revenue / gross revenue", "income / proceeds / earnings",
         "Subscription software recurring revenue climbed twenty-two percent year on year.", "구독형 소프트웨어의 정기 수익은 전년 동기 대비 22% 증가했습니다."),
        ("deficit", "적자, 부족액", "noun", "budget deficit / trade deficit", "shortfall / loss / deficiency",
         "The regional branch managed to turn a six-digit deficit into an operational surplus.", "지역 지사는 6자릿수 적자를 성공적으로 영업 흑자로 반전시켰습니다."),
        ("surplus", "흑자, 잉여금, 과잉", "noun", "budget surplus / surplus equipment", "excess / overflow / profit",
         "Remaining surplus funds at fiscal year-end will be allocated to employee training.", "회계연도 말에 남은 잉여 자금은 직원 역량 강화 교육에 배정될 것입니다."),
        ("allocation", "할당, 배분", "noun", "budget allocation / resource allocation", "allotment / assignment / distribution",
         "The finance committee approved a generous allocation of funds for server expansion.", "재무위원회는 서버 증설을 위한 넉넉한 예산 배분을 승인했습니다."),
        ("margin", "마진, 이윤, 차이", "noun", "profit margin / operating margin", "markup / gain / leeway",
         "Switching to domestic suppliers widened our net profit margin on medical sensors.", "국내 공급업체로 전환하면서 의료용 센서에 대한 순이익 마진이 확대되었습니다."),
        ("discrepancy", "불일치, 차이", "noun", "discrepancy in billing / resolve discrepancies", "inconsistency / disparity / mismatch",
         "Auditors noticed a significant discrepancy between the paper receipts and ledger sums.", "감사관들은 종이 영수증과 장부상 합계 금액 사이에 상당한 불일치가 있음을 발견했습니다."),
        ("ledger", "원장, 회계 장부", "noun", "general ledger / audit the ledger", "account book / records / register",
         "The senior bookkeeper meticulously reconciled every line entry in the general ledger.", "수석 경리 담당자는 총계정원장의 모든 입력 항목을 꼼꼼하게 대사했습니다."),
        ("reconcile", "대사하다, 일치시키다, 화해시키다", "verb", "reconcile accounts / reconcile discrepancies", "balance / adjust / harmonize",
         "Accountants work overtime at month-end to reconcile all corporate card expenditures.", "회계사들은 모든 법인카드 지출 내역을 대사(일치)하기 위해 월말에 야근합니다."),
        ("invoice", "송장, 청구서; 청구서를 보내다", "noun", "issue an invoice / outstanding invoice", "bill / statement / receipt",
         "Kindly pay the attached invoice within thirty days to avoid late interest penalties.", "연체 가산금을 피하기 위해 30일 이내에 첨부된 송장 대금을 결제해 주시기 바랍니다."),
        ("depreciation", "감가상각, 가치 하락", "noun", "accumulated depreciation / asset depreciation", "devaluation / write-down",
         "Tax accountants calculated the five-year depreciation allowance for the factory vans.", "세무 회계사들은 공장 밴 차량에 대한 5년 감가상각 공제액을 계산했습니다."),
        ("amortize", "분할 상환하다, 상각하다", "verb", "amortize the loan over ten years / amortize costs", "pay off / write off in installments",
         "The financing agreement allows the developer to amortize the debt over twenty years.", "금융 협약에 따라 개발업체는 20년에 걸쳐 부채를 분할 상환할 수 있습니다."),
        ("liability", "부채, 법적 책임", "noun", "assets and liabilities / assume liability", "debt / financial obligation / legal responsibility",
         "The financial statement clearly distinguishes between short-term and long-term liabilities.", "재무제표는 유동 부채(단기 부채)와 비유동 부채(장기 부채)를 명확히 구분합니다."),
        ("equity", "자기자본, 보통주, 지분", "noun", "shareholders' equity / equity stake", "net worth / ownership / capital",
         "The venture capital consortium acquired a twenty percent equity stake in the startup.", "벤처 캐피털 컨소시엄은 해당 스타트업의 지분 20%를 인수했습니다."),
        ("asset", "자산, 귀중한 것", "noun", "liquid assets / valuable corporate asset", "resources / property / holdings",
         "Patents and customer loyalty constitute the laboratory's most prized intangible assets.", "특허권과 고객 충성도는 연구소가 보유한 가장 귀중한 무형 자산입니다."),
        ("solvent", "지불 능력이 있는", "adj", "remain solvent / commercially solvent", "financially sound / stable",
         "Securing the bridge loan ensured the manufacturer remained solvent through the dry spell.", "브릿지 론을 확보한 덕분에 제조사는 자금 경색기에도 지불 능력을 유지할 수 있었습니다."),
        ("insolvent", "파산한, 지급 불능의", "adj", "declared insolvent / insolvent corporation", "bankrupt / broke / ruined",
         "The overseas contractor was declared insolvent after failing to honor bond obligations.", "그 해외 계약업체는 채권 의무를 이행하지 못한 후 지급 불능(파산)을 선고받았습니다."),
        ("remit", "송금하다, 면제하다", "verb", "remit payment / remit funds via wire", "transfer / send money / pay",
         "Please remit the final milestone payment directly to the designated escrow account.", "지정된 에스크로 계좌로 최종 마일스톤 대금을 직접 송금해 주십시오."),
        ("remittance", "송금, 송금액", "noun", "wire remittance / foreign remittance", "transfer / payment / money order",
         "Overseas vendors receive electronic remittance confirmations automatically by email.", "해외 공급업체는 이메일을 통해 전자 송금 확인서를 자동으로 수신합니다."),
        ("fiscal", "회계의, 재정의", "adj", "fiscal year / fiscal policy", "financial / monetary / budgetary",
         "Our corporate fiscal year concludes on December 31 with an annual investor gala.", "당사의 회계연도는 연례 투자자의 밤 행사와 함께 12월 31일에 종료됩니다."),
        ("quote", "견적, 인용; 견적을 내다", "noun", "obtain a quote / competitive quote", "estimate / price / bid",
         "We requested a competitive price quote from three certified logistics providers.", "우리는 3곳의 공인 물류 공급업체에 경쟁력 있는 가격 견적을 요청했습니다."),
        ("estimate", "견적서, 추정치; 추산하다", "noun", "preliminary estimate / cost estimate", "calculation / approximation / quote",
         "The preliminary cost estimate for the conference room renovation is fifty thousand dollars.", "회의실 리모델링에 대한 사전 비용 견적 추산치는 5만 달러입니다."),
        ("dividend", "배당금", "noun", "quarterly dividend / dividend yield", "share of profits / payout",
         "Shareholders celebrated as the board voted to increase the quarterly dividend by ten cents.", "이사회가 분기 배당금을 주당 10센트 인상하기로 결의하자 주주들은 환호했습니다."),
        ("deductible", "공제 가능한; 자기부담금", "adj", "tax-deductible expense / deductible amount", "allowable / exempt",
         "Charitable donations made through the corporate foundation are fully tax-deductible.", "기업 재단을 통해 기부된 자선 성금은 전액 세액 공제가 가능합니다."),
        ("outstanding", "미결제의; 뛰어난", "adj", "outstanding balance / outstanding performance", "unpaid / due / exceptional",
         "Please settle the outstanding balance on your invoice before the end of the month.", "월말이 지나기 전에 송장의 미결제 잔액을 모두 정산해 주시기 바랍니다."),
        ("overdue", "기한이 지난, 연체된", "adj", "overdue payment / overdue account", "late / delinquent / behindhand",
         "The accounting software automatically flags overdue accounts for collections follow-up.", "회계 소프트웨어는 수금 후속 조치를 위해 연체 계정을 자동으로 표시합니다."),
        ("lucrative", "수익성이 좋은, 돈벌이가 되는", "adj", "lucrative contract / lucrative partnership", "profitable / high-paying / gainful",
         "Securing the government cloud contract proved extraordinarily lucrative for the provider.", "정부 클라우드 사업 수주는 서비스 공급자에게 대단히 수익성 높은 것으로 입증되었습니다."),
        ("overhead", "간접비, 고정비; 머리 위의", "noun", "reduce overhead costs / low overhead", "operating expenses / fixed costs",
         "Transitioning to automated customer support reduced recurring office overhead significantly.", "고객 지원을 자동화로 전환하여 반복적인 사무실 간접비를 크게 줄였습니다."),
        ("procure", "조달하다, 획득하다", "verb", "procure equipment / procure raw materials", "obtain / acquire / purchase",
         "The purchasing department will procure industrial generators before peak storm season.", "구매 부서는 태풍 성수기 전에 산업용 발전기를 조달할 것입니다."),
        ("break-even", "손익분기점의", "adj", "break-even point / achieve break-even", "balanced / non-profit",
         "Analysts forecast the newly launched mobile subscription will reach break-even by July.", "애널리스트들은 새로 출시된 모바일 구독 서비스가 7월까지 손익분기점에 도달할 것으로 전망합니다."),
        ("solvency", "지불 능력", "noun", "maintain financial solvency / test solvency", "creditworthiness / soundness",
         "The state banking authority conducts stress tests to verify each institution's solvency.", "주 금융 당국은 각 금융기관의 지급 능력을 검증하기 위해 스트레스 테스트를 실시합니다."),
        ("reimburse", "변제하다, 환급하다", "verb", "reimburse travel expenses / promptly reimburse", "pay back / compensate / refund",
         "The university will reimburse visiting researchers for economy airfare and lodging.", "대학 측은 방문 연구원들에게 이코노미 항공료와 숙박비를 환급해 드릴 것입니다."),
        ("balance", "잔액, 균형; 잔고를 맞추다", "noun", "account balance / remaining balance", "remainder / rest / equilibrium",
         "Log in to the online portal anytime to view your current checking account balance.", "온라인 포털에 로그인하시면 언제든지 당좌 예금 계좌의 현재 잔액을 확인하실 수 있습니다.")
    ]),

    # DAY 6: 계약 및 거래 협상 (34 words)
    6: ("계약/협상", "800필수", [
        ("negotiate", "협상하다, 절충하다", "verb", "negotiate terms / negotiate a contract", "bargain / discuss terms / settle",
         "Both legal councils worked through the weekend to negotiate favorable license terms.", "양측 법률 자문단은 유리한 라이선스 조건을 협상하기 위해 주말 내내 일했습니다."),
        ("binding", "구속력이 있는, 법적 효력이 있는", "adj", "legally binding / binding agreement", "enforceable / obligatory / contractual",
         "Once countersigned by authorized officers, the memorandum becomes legally binding.", "인가된 임원의 상호 서명이 완료되면, 해당 각서는 법적 구속력을 갖게 됩니다."),
        ("clause", "조항, 조문", "noun", "confidentiality clause / penalty clause", "provision / stipulation / condition",
         "The vendor insisted on inserting a penalty clause in case delivery is delayed past June.", "공급업체는 납품이 6월 이후로 지연될 경우를 대비해 위약금 조항 삽입을 고집했습니다."),
        ("provision", "조항, 규정, 대비", "noun", "statutory provision / contractual provisions", "clause / condition / stipulation",
         "Under the provisions of Article 4, either party may terminate with 30 days' notice.", "제4조의 규정에 의거하여, 어느 당사자든 30일 전 사전 통지로 계약을 해지할 수 있습니다."),
        ("breach", "위반, 불이행; 위반하다", "noun", "breach of contract / security breach", "violation / infringement / breaking",
         "Unauthorized disclosure of client credentials constitutes a critical breach of agreement.", "고객 보안 정보의 무단 유출은 중대한 계약 위반 행위에 해당합니다."),
        ("stipulate", "규정하다, 명기하다", "verb", "as stipulated in the contract / clearly stipulate", "specify / mandate / dictate",
         "The vendor guidelines stipulate that all delivered components must carry UL safety tags.", "협력업체 지침은 납품되는 모든 부품이 UL 안전 인증 태그를 부착해야 한다고 규정합니다."),
        ("nullify", "무효화하다", "verb", "nullify the agreement / nullify a contract", "invalidate / void / annul",
         "Failure to present an official certificate of origin will nullify the reduced tariff rate.", "공식 원산지 증명서를 제출하지 못할 경우 인하된 관세율 적용이 무효화됩니다."),
        ("covenant", "서약, 계약, 조약", "noun", "restrictive covenant / loan covenant", "pledge / promise / commitment",
         "The executive signed a restrictive covenant barring him from joining direct rivals.", "그 임원은 직접적인 경쟁사로 이직하는 것을 금지하는 서약서에 서명했습니다."),
        ("arbitration", "중재", "noun", "binding arbitration / submit to arbitration", "mediation / dispute settlement",
         "All international commercial disputes shall be resolved through binding arbitration in Geneva.", "모든 국제 상업 분쟁은 제네바에서의 구속력 있는 중재를 통해 해결되어야 합니다."),
        ("counterpart", "상대방, 대응 관계에 있는 사람", "noun", "foreign counterpart / corporate counterpart", "opposite number / peer / equivalent",
         "The purchasing director met with his supplier counterpart to finalize unit discounts.", "구매 이사는 단가 할인을 최종 확정 짓기 위해 공급사 측 상대 담당자와 만났습니다."),
        ("indemnity", "배상, 보상, 면책", "noun", "clause of indemnity / seek indemnity", "compensation / insurance / reimbursement",
         "The software publisher agreed to provide complete indemnity against copyright claims.", "소프트웨어 배급사는 저작권 청구 소송에 대해 전액 손해 배상을 제공하기로 합의했습니다."),
        ("waive", "포기하다, 적용하지 않다", "verb", "waive the fee / waive inspection requirements", "relinquish / forfeit / drop",
         "The landlord agreed to waive the first month's parking fee as an incentive to sign.", "임대인은 계약 체결을 유도하기 위해 첫 달 주차 요금을 면제해 주기로 합의했습니다."),
        ("waiver", "포기, 면제, 권리 포기 각서", "noun", "sign a waiver / fee waiver", "renunciation / release / disclaimer",
         "Submitting the electronic liability waiver is required before touring the plant floor.", "공장 작업장을 견학하기 전 전자 책임 면제 서약서 제출이 필수적입니다."),
        ("compromise", "타협하다; 타협", "noun", "reach a compromise / mutually acceptable compromise", "agreement / middle ground / concession",
         "After ten hours of deadlock, the union and airline management reached a sensible compromise.", "10시간 동안 이어진 교착 끝에 노조와 항공사 경영진은 합리적인 타협안에 도달했습니다."),
        ("concession", "양보, 인정; 할인", "noun", "make major concessions / commercial concession", "compromise / yielding / allowance",
         "Management made generous wage concessions to avoid a catastrophic assembly halt.", "경영진은 치명적인 공장 가동 중단을 막기 위해 후한 임금 양보안을 내놓았습니다."),
        ("preliminary", "예비의, 사전의", "adj", "preliminary agreement / preliminary findings", "initial / introductory / preparatory",
         "Both companies executed a preliminary agreement outlining the contours of the merger.", "양사는 합병의 기본 골자를 개괄적으로 기술한 예비 합의서를 체결했습니다."),
        ("terminate", "종료하다, 해지하다", "verb", "terminate a lease / terminate employment", "end / conclude / cancel",
         "The client reserves the right to terminate the service contract upon thirty days' notice.", "고객은 30일 전 서면 통지로 서비스 계약을 해지할 수 있는 권리를 보유합니다."),
        ("renew", "갱신하다, 재개하다", "verb", "renew a subscription / renew a contract", "extend / prolong / continue",
         "Tenants must give written notice sixty days in advance if they wish to renew the lease.", "임차인이 임대 계약을 갱신하고자 할 경우 60일 전에 서면으로 통지해야 합니다."),
        ("execute", "체결하다, 집행하다, 실행하다", "verb", "execute a contract / execute orders", "sign / formalize / carry out",
         "Authorized representatives from both corporations gathered in London to execute the deed.", "양사로부터 위임받은 대표자들은 계약 증서를 공식 체결하기 위해 런던에 모였습니다."),
        ("cancellation", "취소, 철회", "noun", "cancellation policy / late cancellation", "annulment / revocation / termination",
         "Review the hotel's strict cancellation policy before finalizing your reservations.", "예약을 확정하기 전에 호텔의 엄격한 취소 환불 정책을 반드시 확인하십시오."),
        ("confidential", "기밀의, 비밀의", "adj", "strictly confidential / confidential records", "classified / private / secret",
         "All proprietary formulas shared during talks must remain strictly confidential.", "회담 중에 공유된 모든 독점 배합 공식은 엄격히 비밀로 유지되어야 합니다."),
        ("amendment", "수정, 개정안", "noun", "make an amendment / contract amendment", "revision / alteration / modification",
         "The parties drafted an amendment extending the project completion deadline by a month.", "당사자들은 프로젝트 완공 기한을 한 달 연장하는 수정 계약서를 작성했습니다."),
        ("terms", "조건, 조항; 기간", "noun", "terms and conditions / agree on terms", "provisions / stipulations / requirements",
         "Please scrutinize the attached terms and conditions before signing on the dotted line.", "점선 위에 서명하시기 전에 첨부된 이용 약관(거래 조건)을 면밀히 검토해 주십시오."),
        ("duration", "지속 기간, 유효 기간", "noun", "duration of the contract / short duration", "period / term / span",
         "The insurance policy remains in effect for the entire duration of your overseas trip.", "해당 보험 상품은 해외 출장 전 기간 동안 온전히 효력을 유지합니다."),
        ("enforce", "집행하다, 시행하다, 강요하다", "verb", "enforce regulations / strictly enforce", "apply / implement / administer",
         "City inspectors patrol downtown construction sites to enforce safety standards.", "시 점검관들은 안전 표준 규정을 집행하기 위해 시내 건설 현장을 순찰합니다."),
        ("obligation", "의무, 책임", "noun", "contractual obligation / fulfill an obligation", "duty / commitment / responsibility",
         "The software firm has a contractual obligation to provide round-the-clock tech support.", "소프트웨어 회사는 24시간 내내 기술 지원을 제공해야 할 계약상의 의무가 있습니다."),
        ("consensus", "의견 일치, 합의", "noun", "reach a consensus / broad consensus", "agreement / accord / concurrence",
         "The committee took four days of debate to reach a broad consensus on vendor selection.", "위원회는 공급업체 선정에 대해 폭넓은 합의에 도달하는 데 나흘간의 토론을 거쳤습니다."),
        ("accord", "합의, 일치; 부여하다", "noun", "sign an accord / in accord with", "treaty / pact / agreement",
         "Leaders signed a landmark trade accord eliminating import tariffs on electronic parts.", "지도자들은 전자 부품에 대한 수입 관세를 철폐하는 기념비적인 무역 합의안에 서명했습니다."),
        ("counteroffer", "수정 제안, 역제안", "noun", "make a counteroffer / accept a counteroffer", "counterbid / revised proposal",
         "The seller rejected the initial appraisal and submitted an aggressive counteroffer.", "매도인은 최초 감정가를 거부하고 공격적인 수정 제안(역제안)을 제출했습니다."),
        ("dispute", "분쟁, 논쟁; 이의를 제기하다", "noun", "settle a dispute / commercial dispute", "conflict / disagreement / quarrel",
         "A neutral ombudsman was appointed to settle the bitter territorial dispute between reps.", "영업 대표들 간의 치열한 담당 구역 분쟁을 해결하기 위해 중립적인 옴부즈맨이 임명되었습니다."),
        ("memorandum", "각서, 비망록", "noun", "memorandum of understanding / internal memo", "memo / minute / agreement",
         "The two tech universities signed a formal memorandum of understanding on quantum research.", "두 공과대학은 양자 기술 연구에 관한 공식 양해각서(MOU)를 체결했습니다."),
        ("counterpart", "대응자, 상대국 담당관", "noun", "confer with one's counterpart", "peer / equivalent / opposite number",
         "Our chief legal strategist conferred with his Japanese counterpart ahead of the hearing.", "당사의 수석 법무 전략가는 청문회를 앞두고 일본 측 상대 변호사와 협의했습니다."),
        ("warrant", "보증하다; 정당한 이유, 영장", "verb", "warrant a full refund / be warranted", "justify / guarantee / authorize",
         "The minor cosmetic scratch does not warrant a complete replacement of the appliance.", "외관상의 경미한 긁힘은 가전제품의 전면 교체를 요구할 정당한 사유가 되지 않습니다."),
        ("party", "당사자, 정당, 파티", "noun", "third party / interested party / party to a contract", "participant / side / signatory",
         "Neither party shall disclose confidential project metrics to unauthorized third parties.", "어느 당사자도 인가되지 않은 제3자에게 기밀 프로젝트 지표를 공개해서는 안 됩니다.")
    ]),

    # DAY 7: 마케팅 및 광고 홍보 (34 words)
    7: ("마케팅/광고", "620도약", [
        ("unveil", "공개하다, 베일을 벗기다", "verb", "unveil a new product line / officially unveil", "introduce / launch / reveal / present",
         "The chief designer will unveil the flagship smartphone model during tomorrow's keynote.", "수석 디자이너는 내일 기조연설 중에 플래그십 스마트폰 모델을 공식 공개할 것입니다."),
        ("launch", "출시하다, 착수하다; 출시", "verb", "launch a marketing campaign / product launch", "introduce / release / initiate",
         "The cosmetic enterprise plans to launch an organic skincare line this coming spring.", "그 화장품 기업은 다가오는 봄에 유기농 스킨케어 라인을 출시할 계획입니다."),
        ("campaign", "캠페인, 홍보 활동", "noun", "promotional campaign / advertising campaign", "drive / initiative / promotion",
         "The digital advertising campaign generated millions of impressions across social apps.", "디지털 광고 캠페인은 소셜 앱 전반에 걸쳐 수백만 건의 노출을 창출했습니다."),
        ("promotional", "홍보의, 판촉의", "adj", "promotional material / promotional discount", "marketing / advertising / publicity",
         "Brand ambassadors distributed colorful promotional brochures to visitors entering the hall.", "브랜드 앰버서더들은 홀에 들어서는 방문객들에게 다채로운 홍보 책자를 배포했습니다."),
        ("brochure", "안내 책자, 브로슈어", "noun", "glossy brochure / informational brochure", "pamphlet / booklet / leaflet",
         "You can pick up an informational travel brochure at the international terminal lobby.", "국제선 터미널 로비에서 유익한 여행 안내 책자를 가져가실 수 있습니다."),
        ("pamphlet", "소책자, 팸플릿", "noun", "distribute pamphlets / informational pamphlet", "leaflet / brochure / flyer",
         "Health volunteers handed out bilingual pamphlets detailing proper recycling protocols.", "보건 자원봉사자들은 올바른 재활용 수칙을 상세히 기술한 이중언어 팸플릿을 나눠주었습니다."),
        ("demographics", "인구 통계, 인구학적 특성", "noun", "target demographic / changing demographics", "population data / profile",
         "Marketing consultants analyzed urban demographics to pick the ideal coffee shop spot.", "마케팅 컨설턴트들은 최적의 커피숍 위치를 선정하기 위해 도시 인구 통계를 분석했습니다."),
        ("publicize", "널리 알리다, 홍보하다", "verb", "publicize the opening / widely publicize", "advertise / promote / announce",
         "The gallery hired an agency to publicize the retrospective exhibition of local artists.", "미술관은 지역 예술가들의 회고전을 널리 홍보하기 위해 홍보 대행사를 고용했습니다."),
        ("endorse", "지지하다, 홍보하다 (유명인이)", "verb", "endorse a product / celebrity endorsement", "back / support / recommend",
         "World-champion sprinters were contracted to endorse the innovative running sneaker.", "세계 챔피언 단거리 선수들이 혁신적인 러닝화를 광고(보증 홍보)하기로 계약을 맺었습니다."),
        ("penetrate", "침투하다, 진출하다", "verb", "penetrate the market / deeply penetrate", "enter / pierce / break into",
         "Low pricing and local partnerships allowed the brand to penetrate the Latin market quickly.", "저렴한 가격 정책과 현지 파트너십 덕분에 그 브랜드는 중남미 시장에 빠르게 진출할 수 있었습니다."),
        ("awareness", "인지도, 인식", "noun", "brand awareness / raise environmental awareness", "recognition / consciousness / familiarity",
         "Billboard campaigns along busy highways helped double our regional brand awareness.", "번화한 고속도로를 따라 설치된 옥외 광고판 캠페인은 지역 브랜드 인지도를 두 배로 높이는 데 기여했습니다."),
        ("competitor", "경쟁업체, 경쟁자", "noun", "fierce competitor / rival competitor", "rival / opposition / challenger",
         "To stay ahead of our fierce competitors, we consistently reinvest profits into R&D.", "치열한 경쟁업체들보다 앞서 나가기 위해 우리는 지속적으로 수익을 R&D에 재투자합니다."),
        ("questionnaire", "설문지", "noun", "complete a questionnaire / customer questionnaire", "survey / feedback form",
         "Hotel guests are invited to complete a brief satisfaction questionnaire upon checkout.", "호텔 투숙객들은 체크아웃 시 간단한 만족도 설문지를 작성해 주시길 부탁드립니다."),
        ("testimonial", "고객 추천 후기, 사용 소감", "noun", "client testimonial / glowing testimonial", "endorsement / recommendation / review",
         "The company website features genuine customer testimonials praising the quick support.", "회사 웹사이트에는 신속한 고객 지원을 칭찬하는 실제 고객들의 추천 후기가 실려 있습니다."),
        ("patronize", "애용하다, 단골로 삼다", "verb", "patronize local businesses / frequently patronize", "frequent / shop at / support",
         "We deeply thank all neighborhood residents who patronize our independent bookstore.", "저희 독립 서점을 애용해 주시는 모든 동네 주민 여러분께 깊은 감사를 드립니다."),
        ("clientele", "고객들 (집합적)", "noun", "wealthy clientele / loyal clientele", "customers / patrons / buyers",
         "The boutique hotel caters primarily to an upscale business clientele seeking privacy.", "그 부티크 호텔은 프라이버시를 중시하는 고급 비즈니스 고객층을 주 대상으로 합니다."),
        ("loyalty", "충성도, 성실", "noun", "customer loyalty / brand loyalty", "allegiance / faithfulness / devotion",
         "Offering exclusive airline mileage bonuses strengthens long-term customer loyalty.", "독점적인 항공 마일리지 보너스를 제공하면 장기적인 고객 충성도가 강화됩니다."),
        ("discount", "할인; 할인하다", "noun", "substantial discount / volume discount", "reduction / markdown / deduction",
         "Corporate group bookings of twenty rooms or more are eligible for a substantial discount.", "20개 객실 이상의 기업 단체 예약은 대폭적인 할인을 받을 자격이 있습니다."),
        ("voucher", "할인권, 상품권, 바우처", "noun", "redeem a voucher / gift voucher", "coupon / token / certificate",
         "Passengers affected by flight delays were issued fifty-dollar meal vouchers.", "항공편 지연의 영향을 받은 승객들에게 50달러 상당의 식사 바우처가 지급되었습니다."),
        ("showcase", "전시하다, 선보이다; 전시장", "verb", "showcase latest innovations / annual showcase", "display / exhibit / feature",
         "The international electronics expo offers startups a premier stage to showcase devices.", "국제 전자제품 박람회는 스타트업들에게 새로운 기기를 선보일 최고의 무대를 제공합니다."),
        ("merchandise", "상품, 물품; 매매하다", "noun", "display merchandise / promotional merchandise", "goods / products / wares",
         "Damaged merchandise must be reported to the shift supervisor before being returned.", "파손된 상품은 반품 처리하기 전에 근무 조 반장에게 보고해야 합니다."),
        ("outlet", "직판점, 아울렛, 배출구", "noun", "retail outlet / factory outlet", "store / shop / market",
         "The sports apparel maker opened its largest flagship outlet in metropolitan Seoul.", "그 스포츠 의류 제조업체는 서울 수도권에 최대 규모의 플래그십 아울렛을 오픈했습니다."),
        ("niche", "틈새시장, 적소", "noun", "niche market / carve out a niche", "specialized segment / corner",
         "By focusing on allergy-free organic cosmetics, the firm carved out a profitable niche.", "알레르기 유발 물질이 없는 유기농 화장품에 집중함으로써 그 회사는 수익성 높은 틈새시장을 개척했습니다."),
        ("prospective", "잠재적인, 유망한", "adj", "prospective clients / prospective buyers", "potential / future / expected",
         "Real estate agents prepared luxury show condos to impress prospective investors.", "부동산 중개인들은 잠재적인 투자자들에게 깊은 인상을 남기기 위해 고급 모델하우스를 준비했습니다."),
        ("marketable", "시장성 있는, 잘 팔리는", "adj", "highly marketable / marketable skills", "saleable / commercial / attractive",
         "Engineers redesigned the bulky prototype into a sleek, highly marketable appliance.", "엔지니어들은 부피가 큰 시제품을 날렵하고 시장성 높은 가전제품으로 재설계했습니다."),
        ("sponsor", "후원하다, 협찬하다; 후원자", "verb", "sponsor a charity marathon / corporate sponsor", "fund / back / underwrite",
         "The financial conglomerate agreed to sponsor the annual youth science symposium.", "그 금융 대기업은 연례 청소년 과학 심포지엄을 공식 후원하기로 합의했습니다."),
        ("broadcast", "방송하다, 널리 알리다; 방송", "verb", "broadcast live / commercial broadcast", "transmit / air / beam",
         "The championship soccer final will be broadcast live to eighty countries simultaneously.", "챔피언십 축구 결승전은 전 세계 80개국에 동시 생중계로 방송될 예정입니다."),
        ("circulation", "발행 부수, 유통, 순환", "noun", "newspaper circulation / currency circulation", "distribution / readership",
         "The business weekly boasts an impressive paid circulation surpassing one million copies.", "그 경제 주간지는 100만 부를 넘어서는 인상적인 유료 발행 부수를 자랑합니다."),
        ("feature", "특징으로 하다; 특징, 특색", "verb", "feature advanced AI / key feature", "highlight / present / showcase",
         "The newly released tablet features a glare-free anti-reflective display panel.", "새로 출시된 태블릿은 눈부심 없는 반사 방지 디스플레이 패널을 핵심 특징으로 갖추고 있습니다."),
        ("feedback", "피드백, 사용자 반응", "noun", "customer feedback / constructive feedback", "reactions / comments / input",
         "Design teams incorporated valuable consumer feedback into the second hardware build.", "디자인 팀은 소중한 소비자 피드백을 두 번째 하드웨어 버전에 반영했습니다."),
        ("exposure", "노출, 광고 효과", "noun", "media exposure / maximum exposure", "publicity / visibility / coverage",
         "Sponsoring the stadium naming rights provided the auto firm with immense global exposure.", "경기장 명명권을 후원함으로써 그 자동차 회사는 엄청난 전 세계적 미디어 노출 효과를 얻었습니다."),
        ("hype", "과대광고, 대대적인 홍보", "noun", "media hype / live up to the hype", "publicity / buzz / fanfare",
         "Reviewers agreed that the revolutionary noise-canceling headphones lived up to the hype.", "평론가들은 그 혁신적인 노이즈 캔슬링 헤드폰이 대대적인 입소문(기대)에 완전히 부응했다고 동의했습니다."),
        ("pitch", "영업 권유, 프레젠테이션", "noun", "sales pitch / elevator pitch", "presentation / bid / proposal",
         "The advertising agency prepared an energetic five-minute pitch for the shoe brand.", "그 광고 대행사는 신발 브랜드를 사로잡기 위해 활기 넘치는 5분짜리 프레젠테이션(피치)을 준비했습니다."),
        ("target", "목표로 삼다; 대상, 목표", "verb", "target younger demographics / target audience", "aim at / focus on",
         "The promotional campaign specifically targets young urban working professionals.", "그 홍보 캠페인은 도시의 젊은 직장인 계층을 특별한 목표 대상으로 삼고 있습니다.")
    ]),

    # DAY 8: 물류 유통 및 재고 관리 (34 words)
    8: ("물류/유통", "800필수", [
        ("inventory", "재고, 재고품 목록", "noun", "take inventory / inventory control", "stock / merchandise / goods",
         "Staff will close the warehouse this Saturday to conduct the annual physical inventory count.", "직원들은 연례 실물 재고 조사를 실시하기 위해 이번 주 토요일에 창고를 닫을 것입니다."),
        ("dispatch", "발송하다, 급파하다; 발송", "verb", "dispatch a courier / prompt dispatch", "send / expedite / ship",
         "Our distribution center guarantees to dispatch emergency orders within two hours.", "당사 물류 유통센터는 긴급 주문 건을 2시간 이내에 발송할 것을 보장합니다."),
        ("logistics", "물류, 물류 관리", "noun", "logistics network / third-party logistics", "freight management / distribution",
         "Upgrading our logistics infrastructure reduced cross-country transport transit times.", "물류 인프라를 개선한 덕분에 전국 횡단 수송 운송 시간을 단축할 수 있었습니다."),
        ("cargo", "화물, 적재물", "noun", "cargo plane / freight cargo / precious cargo", "freight / shipment / payload",
         "Customs agents examined the container cargo before granting import clearance.", "세관원들은 수입 통관을 허가하기 전에 컨테이너 화물을 정밀 검사했습니다."),
        ("shipment", "배송, 선적, 탁송화물", "noun", "track a shipment / incoming shipment", "consignment / delivery / package",
         "Customers receive automated text updates whenever their online shipment changes depots.", "고객들은 온라인 배송 상품이 물류 거점을 이동할 때마다 자동 문자 알림을 받습니다."),
        ("freight", "화물 운송, 운임; 화물을 싣다", "noun", "air freight / freight charges", "cargo / transportation / consignment",
         "Air freight is considerably more expensive than maritime shipping but cuts days off delivery.", "항공 화물 운송은 해상 운송보다 상당히 비싸지만 배송 소요일수를 며칠씩 단축해 줍니다."),
        ("consignee", "수하인, 물품을 인수하는 사람", "noun", "delivered to the consignee / designated consignee", "recipient / receiver / addressee",
         "The courier must verify photo identification before handing boxes to the consignee.", "택배 기사는 상자를 수하인에게 건네기 전에 사진이 부착된 신분증을 확인해야 합니다."),
        ("depot", "창고, 보관소, 차량 기지", "noun", "central depot / bus depot / supply depot", "warehouse / terminal / storehouse",
         "All regional delivery vans return to the suburban depot each evening for maintenance.", "모든 지역 배송 차량은 정비를 위해 매일 저녁 교외 차량 기지로 복귀합니다."),
        ("wholesale", "도매; 도매로", "noun", "wholesale price / buy wholesale", "bulk / trade / mass",
         "Restaurant owners purchase organic produce at wholesale rates straight from farmers.", "식당 주인들은 농부들로부터 직접 도매가격으로 유기농 농산물을 구매합니다."),
        ("retail", "소매; 소매하다", "noun", "retail price / retail sector", "consumer sales / merchandising",
         "Electronic retailers noticed an aggressive uptick in smart home gadget purchases.", "전자제품 소매업체들은 스마트홈 기기 구매 건수가 급격히 증가한 것을 발견했습니다."),
        ("clearance", "정리, 재고 처분, 통관, 허가", "noun", "clearance sale / customs clearance", "liquidation / approval / authorization",
         "The boutique is staging a clearance sale this weekend to make room for winter garments.", "그 부티크는 겨울 의류를 들여놓을 공간을 확보하기 위해 이번 주말 재고 정리 세일을 진행합니다."),
        ("transit", "수송, 운송; 통과하다", "noun", "in transit / rapid transit", "transportation / carriage / passage",
         "The perishable dairy packages were damaged while in transit between railway junctions.", "부패하기 쉬운 유제품 패키지가 철도 교차로 간 수송 중에 파손되었습니다."),
        ("expedite", "신속히 처리하다, 촉진하다", "verb", "expedite the shipment / expedite processing", "speed up / hasten / accelerate",
         "Pay an additional surcharge if you wish to expedite the delivery of replacement parts.", "교체 부품 배송을 신속히 처리(특급 배송)하고 싶으시다면 추가 요금을 지불하십시오."),
        ("tracking", "추적, 배송 조회", "noun", "tracking number / real-time tracking", "monitoring / tracing / trail",
         "Enter your ten-digit tracking number on the home portal to monitor courier movement.", "배송 기사의 이동 경로를 확인하시려면 메인 포털에 10자리 배송 추적 번호를 입력하십시오."),
        ("courier", "택배 기사, 특송 배달원", "noun", "deliver by courier / courier service", "messenger / express carrier / deliverer",
         "A motorbike courier rushed the urgent legal contracts directly to the courthouse.", "오토바이 특송 기사가 긴급한 법률 계약서를 법원으로 직접 신속하게 전달했습니다."),
        ("manifest", "화물 적재 목록; 명백한; 나타내다", "noun", "shipping manifest / passenger manifest", "cargo list / inventory record",
         "Customs officers compared the physical shipping containers with the vessel's cargo manifest.", "세관 공무원들은 실제 선적 컨테이너를 선박의 화물 적재 목록과 비교했습니다."),
        ("customs", "세관, 관세", "noun", "pass through customs / customs duty", "tariff office / port authority",
         "International travelers must declare commercial samples when passing through customs.", "해외 여행객들은 세관을 통과할 때 상업용 견본품을 반드시 신고해야 합니다."),
        ("tariff", "관세, 수입세", "noun", "impose tariffs / protective tariff", "duty / import tax / levy",
         "The administration announced a ten percent tariff on imported solar silicon cells.", "정부는 수입 태양광 실리콘 셀에 대해 10%의 관세를 부과하겠다고 발표했습니다."),
        ("warehouse", "창고, 물류 보관소; 보관하다", "noun", "automated warehouse / regional warehouse", "storage / repository / storehouse",
         "Robotic arms sort and palletize cartons in our automated regional warehouse.", "자동화된 지역 물류 창고에서는 로봇 팔이 상자를 분류하고 파렛트에 적재합니다."),
        ("dock", "부두, 선착장, 하역장", "noun", "loading dock / dry dock", "pier / wharf / harbor",
         "Truck drivers backed twenty semi-trailers into the distribution loading dock at dawn.", "트럭 운전사들은 새벽에 20대의 트레일러를 물류 하역장으로 후진시켰습니다."),
        ("procurement", "조달, 획득", "noun", "government procurement / procurement department", "purchasing / acquisition / sourcing",
         "The director of procurement negotiated bulk pricing for heavy construction lumber.", "구매 조달 이사는 중장비 건설용 목재에 대한 대량 구매 가격을 협상했습니다."),
        ("carrier", "운송업체, 통신사, 수송기", "noun", "common carrier / preferred shipping carrier", "transporter / courier / freight line",
         "Federal guidelines demand that every licensed common carrier hold comprehensive liability coverage.", "연방 가이드라인은 모든 면허 운송업체가 포괄적인 배상 책임 보험을 보유하도록 요구합니다."),
        ("batch", "한 묶음, 일단, 배치", "noun", "batch of orders / batch processing", "lot / group / collection",
         "Quality controllers rejected the initial batch of glass vials due to microscopic fissures.", "품질 관리자들은 미세한 균열 때문에 유리 바이알의 첫 번째 생산 묶음(배치)을 불합격 처리했습니다."),
        ("replenish", "다시 채우다, 보충하다", "verb", "replenish the stock / replenish supplies", "restock / refill / renew",
         "Store clerks worked overnight to replenish supermarket shelves ahead of the holiday rush.", "매장 직원들은 연휴 대목에 앞서 슈퍼마켓 진열대를 다시 채우기 위해 밤새 일했습니다."),
        ("supplier", "공급업체, 공급처", "noun", "reliable supplier / domestic supplier", "vendor / provider / purveyor",
         "Automakers rely on an intricate global tier of parts suppliers to sustain assembly.", "자동차 제조업체들은 조립 라인을 유지하기 위해 부품 공급업체들의 복잡한 글로벌 계층에 의존합니다."),
        ("vendor", "판매업체, 행상인, 공급사", "noun", "approved vendor / select a vendor", "seller / merchant / supplier",
         "The hospital administration contracted a certified medical sanitation vendor.", "병원 행정부는 공인된 의료 위생 전문 판매 공급업체와 계약을 맺었습니다."),
        ("fragile", "깨지기 쉬운, 취약한", "adj", "fragile items / handle with care", "delicate / breakable / brittle",
         "Stickers reading 'Fragile - Glassware' were affixed to the exterior of each carton.", "각 판지 상자의 외부에 '깨지기 쉬움 - 유리 제품'이라는 스티커가 부착되었습니다."),
        ("handle", "다루다, 취급하다, 처리하다", "verb", "handle with care / handle customer complaints", "manage / deal with / process",
         "Warehouse personnel must wear padded safety gloves when they handle caustic solvents.", "물류창고 직원들은 부식성 용제를 다룰 때 완충 안전장갑을 착용해야 합니다."),
        ("bulk", "대량의, 부피가 큰; 크기", "adj", "buy in bulk / bulk shipment", "large quantity / mass / volume",
         "Purchasing paper goods in bulk saves the school district twenty-five percent annually.", "종이류 용품을 대량으로 구매하면 교육청은 매년 25%의 예산을 절감할 수 있습니다."),
        ("fleet", "차량 선단, 선대, 무리", "noun", "fleet of delivery vans / commercial fleet", "group of vehicles / armada",
         "The courier firm announced plans to electrify fifty percent of its urban delivery fleet.", "그 특송 업체는 도시 배송 차량 선단의 50%를 전기차로 전환할 계획을 발표했습니다."),
        ("pallet", "화물 운반대, 파렛트", "noun", "wooden pallet / stack on pallets", "skid / shipping platform",
         "Forklift operators stacked twenty shrink-wrapped wooden pallets into the high-bay rack.", "지게차 운전자들은 랩으로 감싼 20개의 목재 파렛트를 하이베이 랙에 쌓았습니다."),
        ("crate", "나무 상자; 상자에 포장하다", "noun", "wooden crate / packing crates", "box / container / case",
         "Rare museum sculptures were secured inside padded wooden crates for transoceanic air travel.", "희귀한 박물관 조각품들은 대양 횡단 항공 운송을 위해 완충재를 댄 나무 상자 안에 안전하게 보관되었습니다."),
        ("shortage", "부족, 품귀", "noun", "acute shortage / supply shortage", "scarcity / deficit / lack",
         "A global microchip shortage forced auto manufacturers to halt assembly for two weeks.", "글로벌 마이크로칩 품귀 현상으로 인해 자동차 제조업체들은 2주간 조립 라인을 중단해야 했습니다."),
        ("fulfill", "이행하다, 주문을 처리하다", "verb", "fulfill customer orders / fulfill requirements", "execute / satisfy / complete",
         "The e-commerce fulfillment center can process and fulfill fifty thousand orders daily.", "그 전자상거래 물류 풀필먼트 센터는 하루에 5만 건의 주문을 처리하고 완수할 수 있습니다.")
    ]),

    # DAY 9: 생산 제조 및 품질 관리 (34 words)
    9: ("생산/품질", "800필수", [
        ("defect", "결함, 하자, 결점", "noun", "manufacturing defect / zero defects", "flaw / fault / imperfection",
         "Quality inspectors discard any microchips that exhibit even a microscopic defect.", "품질 검사관들은 현미경 수준의 미세한 결함이라도 보이는 마이크로칩은 즉시 폐기합니다."),
        ("flaw", "결함, 흠, 흠집", "noun", "design flaw / fatal flaw", "defect / blemish / error",
         "Engineers discovered a critical thermal design flaw inside the laptop power module.", "엔지니어들은 노트북 전원 모듈 내부에서 중대한 열역학적 설계 결함을 발견했습니다."),
        ("rigorous", "엄격한, 철저한", "adj", "rigorous testing / rigorous standards", "strict / stringent / thorough",
         "Every prototype undergoes rigorous crash and stress testing before entering production.", "모든 시제품은 양산에 들어가기 전에 엄격한 충돌 및 내구성 부하 테스트를 거칩니다."),
        ("precision", "정밀함, 정확성", "noun", "engineered with precision / precision tools", "accuracy / exactness / meticulousness",
         "Optical lenses for medical lasers must be ground with nanometer precision.", "의료용 레이저의 광학 렌즈는 나노미터 단위의 정밀함으로 연마되어야 합니다."),
        ("specification", "세부 사양, 명세서, 시방서", "noun", "meet technical specifications / detailed specs", "requirements / standards / criteria",
         "Components failed acceptance tests because they did not match blueprint specifications.", "부품들이 설계도면 사양과 일치하지 않아 인수 검사에서 불합격 판정을 받았습니다."),
        ("prototype", "시제품, 프로토타입", "noun", "working prototype / build a prototype", "model / mock-up / experimental design",
         "The automotive laboratory revealed a fully functional hydrogen fuel cell prototype.", "그 자동차 연구소는 완벽하게 작동하는 수소 연료 전지 시제품을 공개했습니다."),
        ("assembly", "조립, 조립 부품; 집회", "noun", "assembly line / final assembly", "construction / manufacturing / fabrication",
         "Robotics have accelerated the final chassis assembly line by forty percent.", "로봇 공학 기술 덕분에 최종 차체 조립 라인의 속도가 40% 빨라졌습니다."),
        ("calibrate", "눈금을 조정하다, 교정하다", "verb", "calibrate instruments / precisely calibrate", "adjust / fine-tune / standardize",
         "Technicians must calibrate optical sensors every morning before running quality checks.", "기술자들은 매일 아침 품질 검사를 시작하기 전에 광학 센서의 눈금을 교정해야 합니다."),
        ("malfunction", "오작동하다; 오작동, 고장", "verb", "malfunction under pressure / equipment malfunction", "break down / fail / glitch",
         "If the pressure relief valve should malfunction, automated emergency sirens sound.", "압력 방출 밸브가 오작동할 경우 자동 비상 사이렌이 울립니다."),
        ("warranty", "품질 보증서, 보증 기간", "noun", "under warranty / three-year warranty", "guarantee / assurance / coverage",
         "The flat-panel television comes backed with a complimentary three-year factory warranty.", "그 평판 TV는 3년간의 무료 공장 품질 보증이 기본 지원됩니다."),
        ("durable", "내구성이 있는, 오래가는", "adj", "durable materials / durable goods", "long-lasting / sturdy / resilient",
         "Industrial work boots are manufactured from exceptionally durable reinforced leather.", "산업용 안전화는 내구성이 매우 뛰어난 강화 가죽으로 제작됩니다."),
        ("output", "생산량, 출력", "noun", "increase factory output / daily output", "production / yield / volume",
         "Adding an automated night shift enabled the steel mill to double its weekly output.", "자동화된 야간 근무 조를 추가한 덕분에 제철소는 주간 생산량을 두 배로 늘릴 수 있었습니다."),
        ("capacity", "수용력, 생산 능력, 용량", "noun", "operating at full capacity / storage capacity", "capability / volume / maximum limit",
         "The chemical manufacturing facility is currently operating at ninety percent capacity.", "그 화학 제조 공장은 현재 90%의 생산 가동률(수용 능력)로 가동 중입니다."),
        ("substandard", "기준 이하의, 조악한", "adj", "substandard materials / substandard performance", "inferior / second-rate / poor",
         "Auditors rejected the shipment of bolts after discovering substandard tensile strength.", "감사관들은 볼트의 인장 강도가 기준 이하임을 발견한 후 해당 선적분을 반품 처리했습니다."),
        ("certified", "공인된, 증명된, 자격을 갖춘", "adj", "certified technician / certified organic", "accredited / licensed / authorized",
         "Only certified electricians are authorized to access high-voltage transformer units.", "오직 공인된 전기 기술자만이 고전압 변압기 시설에 접근할 권한이 있습니다."),
        ("benchmark", "기준점, 벤치마크; 표준을 세우다", "noun", "industry benchmark / set a benchmark", "standard / criterion / yardstick",
         "Our cleanroom contamination controls set the new industry benchmark for silicon fabs.", "당사의 클린룸 오염 제어 시스템은 실리콘 반도체 공장의 새로운 업계 기준점을 세웠습니다."),
        ("plant", "공장, 시설, 설비; 식물", "noun", "manufacturing plant / power plant", "factory / facility / works",
         "The company broke ground on a massive semiconductor packaging plant in Texas.", "그 회사는 텍사스에 대규모 반도체 패키징 공장을 착공했습니다."),
        ("automated", "자동화된", "adj", "automated assembly / automated packaging system", "robotic / computerized / mechanical",
         "Installing an automated robotic packaging system eliminated human packing errors.", "자동화된 로봇 포장 시스템을 도입하여 작업자의 포장 실수를 완전히 없앴습니다."),
        ("blueprint", "설계도, 청사진, 세부 계획", "noun", "architectural blueprint / blueprint for growth", "plan / schematic / design diagram",
         "Structural engineers poured over the blueprint to locate the optimal load-bearing columns.", "구조 엔지니어들은 최적의 내력벽 기둥 위치를 찾기 위해 청사진(설계도)을 면밀히 검토했습니다."),
        ("tolerance", "공차(허용 오차), 관용, 내성", "noun", "tight tolerances / engineering tolerance", "allowance / deviation limit / leeway",
         "Turbine blades must be milled to exceedingly tight tolerances of a few microns.", "터빈 블레이드는 몇 마이크론 수준의 매우 엄격한 허용 공차 내에서 정밀 가공되어야 합니다."),
        ("yield", "생산량, 수율; 산출하다, 양보하다", "noun", "wafer yield / crop yield / yield high returns", "output / harvest / return",
         "Implementing machine-vision inspection raised the semiconductor silicon wafer yield.", "머신 비전 검사를 도입하여 반도체 실리콘 웨이퍼 수율을 끌어올렸습니다."),
        ("patent", "특허, 특허권; 특허를 받다", "noun", "patent pending / hold a patent", "copyright / intellectual property / license",
         "The research institute holds thirty-two international patents covering graphene synthesis.", "그 연구소는 그래핀 합성과 관련된 32건의 국제 특허를 보유하고 있습니다."),
        ("maintenance", "유지보수, 관리", "noun", "routine maintenance / preventive maintenance", "upkeep / repair / servicing",
         "Performing routine preventive maintenance on heavy stamping presses prevents breakdowns.", "대형 프레스기에 대한 정기 예방 유지보수를 수행하면 불시 고장을 방지할 수 있습니다."),
        ("safeguard", "보호 장치, 안전장치; 보호하다", "noun", "safety safeguard / environmental safeguards", "protection / shield / defense",
         "Emergency cutoff switches serve as an indispensable safeguard for factory operators.", "비상 전원 차단 스위치는 공장 작업자들에게 없어서는 안 될 필수 안전장치 역할을 합니다."),
        ("hazard", "위험, 위험 요소", "noun", "occupational hazard / fire hazard", "danger / peril / risk",
         "Cluttered walkways in the machine shop represent a serious tripping and fire hazard.", "기계 작업장의 어수선한 통로는 심각한 보행 걸림 및 화재 위험 요소에 해당합니다."),
        ("scrap", "폐기하다; 폐기물, 고철", "verb", "scrap the project / scrap defective parts", "discard / junk / abandon",
         "Management chose to scrap the entire run of misprinted packaging rather than risk branding.", "경영진은 브랜드 이미지를 해칠 위험을 감수하느니 잘못 인쇄된 포장지 전량을 폐기하기로 결정했습니다."),
        ("inspect", "점검하다, 검사하다", "verb", "inspect facilities / thoroughly inspect", "examine / audit / scrutinize",
         "Safety officers will inspect every hydraulic crane before certifying operations.", "안전 책임자들은 작업 승인을 내리기 전에 모든 유압 크레인을 철저히 점검할 것입니다."),
        ("fabricate", "제작하다, 조립하다", "verb", "fabricate steel beams / custom fabricated", "manufacture / construct / build",
         "The local foundry was commissioned to fabricate customized titanium pipe brackets.", "현지 주물 공장은 맞춤형 티타늄 파이프 브래킷을 제작하도록 의뢰받았습니다."),
        ("overhaul", "전면 분해 수리하다; 총점검", "verb", "overhaul an engine / complete overhaul", "renovate / revamp / recondition",
         "Technicians shut down the thermal boiler to overhaul worn valves and gaskets.", "기술자들은 마모된 밸브와 개스킷을 전면 분해 수리하기 위해 열 보일러 가동을 중단했습니다."),
        ("refurbish", "재단장하다, 개조하다", "verb", "refurbish the workshop / refurbished equipment", "renovate / remodel / restore",
         "The company sells certified refurbished robotics at thirty percent off catalog prices.", "회사는 공인 재단장(리퍼비시) 로봇을 카탈로그 정가 대비 30% 할인된 가격에 판매합니다."),
        ("downtime", "가동 중단 시간", "noun", "minimize downtime / unscheduled downtime", "idle time / stoppage / outage",
         "Predictive vibration sensors helped minimize costly unscheduled assembly downtime.", "진동 예측 센서 덕분에 막대한 비용이 드는 계획에 없던 조립 라인 가동 중단 시간을 최소화할 수 있었습니다."),
        ("streamline", "공정을 간소화하다", "verb", "streamline fabrication / streamline operations", "simplify / optimize / expedite",
         "Rearranging the stamping presses helped streamline the metal fabrication flow.", "프레스기 배치를 재조정하여 금속 가공 공정의 흐름을 능률화할 수 있었습니다."),
        ("component", "부품, 구성 요소", "noun", "electronic components / vital component", "part / element / module",
         "Defective solder joints on a single component can disable an entire avionics system.", "단 하나의 부품에 발생한 납땜 불량도 전체 항공 전자 시스템을 마비시킬 수 있습니다."),
        ("obsolete", "더 이상 쓸모없는, 구식의", "adj", "obsolete machinery / render obsolete", "outdated / antique / superseded",
         "The rapid introduction of 3D printers rendered many traditional plaster molds obsolete.", "3D 프린터의 빠른 보급으로 인해 많은 전통적인 석고 주형이 구식(폐기 대상)이 되었습니다.")
    ]),

    # DAY 10: IT 시스템 및 전산 인프라 (34 words)
    10: ("IT/시스템", "800필수", [
        ("compatibility", "호환성", "noun", "ensure compatibility / backward compatibility", "interoperability / harmony / adaptability",
         "Run diagnostic scripts to ensure full software compatibility with legacy operating systems.", "레거시 운영체제와의 완전한 소프트웨어 호환성을 확인하기 위해 진단 스크립트를 실행하십시오."),
        ("troubleshoot", "문제를 해결하다, 원인을 규명하다", "verb", "troubleshoot network errors / effectively troubleshoot", "diagnose / resolve / fix",
         "Our IT help desk is available around the clock to troubleshoot sudden connectivity outages.", "당사 IT 헬프데스크는 갑작스러운 네트워크 연결 장애를 해결하기 위해 24시간 대기하고 있습니다."),
        ("proprietary", "독점의, 소유권이 있는", "adj", "proprietary software / proprietary technology", "patented / exclusive / copyrighted",
         "The laboratory guards its proprietary data compression algorithms with extreme secrecy.", "그 연구소는 독점 데이터 압축 알고리즘을 극도의 보안 속에 보호하고 있습니다."),
        ("encryption", "암호화", "noun", "end-to-end encryption / 256-bit encryption", "encoding / ciphering / cryptography",
         "Banking protocols mandate high-grade 256-bit encryption for all wire payment transactions.", "금융 규정은 모든 온라인 계좌 이체 거래에 고등급 256비트 암호화를 의무화하고 있습니다."),
        ("authenticate", "인증하다, 진짜임을 증명하다", "verb", "authenticate credentials / multi-factor authentication", "verify / validate / confirm",
         "Employees must authenticate their corporate identity via two-factor mobile tokens.", "직원들은 이중 모바일 보안 토큰을 통해 사내 계정 신원을 인증해야 합니다."),
        ("retrieve", "검색하다, 되찾아오다, 복구하다", "verb", "retrieve lost files / retrieve data", "recover / fetch / restore",
         "The backup drive allows database administrators to retrieve corrupt files within minutes.", "백업 드라이브 덕분에 데이터베이스 관리자는 손상된 파일을 몇 분 만에 복구(회수)할 수 있습니다."),
        ("glitch", "작은 오류, 결함", "noun", "software glitch / minor technical glitch", "bug / malfunction / error",
         "A minor software glitch caused a temporary delay in processing online transactions.", "경미한 소프트웨어 오류로 인해 온라인 거래 처리가 일시적으로 지연되었습니다."),
        ("database", "데이터베이스", "noun", "centralized database / update the database", "repository / records / data bank",
         "The client relationship manager entered updated contact particulars into the database.", "고객 관계 관리자는 데이터베이스에 업데이트된 연락처 세부 정보를 입력했습니다."),
        ("backup", "예비, 백업; 백업하다", "noun", "cloud backup / daily backup", "duplicate / contingency / reserve",
         "Systems administrators schedule automatic encrypted cloud backups every midnight.", "시스템 관리자들은 매일 자정 자동 암호화 클라우드 백업을 예약 실행합니다."),
        ("outage", "정전, 시스템 중단, 장애", "noun", "power outage / network outage", "blackout / downtime / disruption",
         "Technicians worked through the night to restore services following a cloud server outage.", "클라우드 서버 장애 발생 후 기술자들은 서비스를 복구하기 위해 밤새 작업했습니다."),
        ("firewall", "방화벽", "noun", "configure a firewall / robust firewall", "security barrier / cyber defense",
         "Cybersecurity policies require updated enterprise firewalls to block unauthorized traffic.", "사이버 보안 정책은 무단 네트워크 트래픽을 차단하기 위해 업데이트된 기업 방화벽을 요구합니다."),
        ("intranet", "사내 인트라넷 망", "noun", "corporate intranet / access the intranet", "internal network / private portal",
         "Internal policy memos and leave request templates are hosted on the company intranet.", "사내 규정 메모와 휴가 신청 양식은 회사 인트라넷에 게시되어 있습니다."),
        ("portal", "포털 사이트, 출입구", "noun", "employee portal / online billing portal", "gateway / entry point / website",
         "Staff can review monthly payslips and benefit selections on the HR self-service portal.", "직원들은 인사부 셀프서비스 포털에서 월별 급여 명세서와 복리후생 선택 항목을 확인할 수 있습니다."),
        ("digitize", "디지털화하다", "verb", "digitize archived records / digitize paperwork", "computerize / scan / electronic conversion",
         "The municipal library launched an ambitious project to digitize historic city blueprints.", "시립 도서관은 유서 깊은 도시 설계도를 디지털화하는 야심 찬 프로젝트를 시작했습니다."),
        ("spreadsheet", "스프레드시트, 계산표", "noun", "excel spreadsheet / update the spreadsheet", "worksheet / data sheet / table",
         "Financial analysts compile regional quarterly revenues onto a master spreadsheet.", "재무 분석가들은 지역 분기별 매출 내역을 마스터 스프레드시트에 취합합니다."),
        ("transcribe", "기록하다, 옮겨 적다, 음성을 텍스트로 변환하다", "verb", "transcribe audio minutes / transcribe interviews", "record / write down / copy",
         "AI transcription software was utilized to transcribe the three-hour shareholder meeting.", "3시간 동안 진행된 주주총회를 기록(텍스트화)하기 위해 AI 음성 전사 소프트웨어가 사용되었습니다."),
        ("shred", "파쇄하다, 조각조각 찢다", "verb", "shred confidential files / document shredder", "destroy / tear up / scrap",
         "Compliance rules dictate that staff shred sensitive client tax documents after five years.", "컴플라이언스 규정에 따라 직원은 5년이 지난 민감한 고객 세무 서류를 파쇄해야 합니다."),
        ("peripheral", "주변 기기; 지엽적인", "noun", "computer peripherals / peripheral devices", "accessory / auxiliary device",
         "The procurement order included hundred computer peripherals such as mice and headsets.", "구매 발주서에는 마우스와 헤드셋 등 100점의 컴퓨터 주변 기기가 포함되었습니다."),
        ("server", "서버", "noun", "dedicated server / cloud server migration", "host computer / mainframe",
         "Migrating local databases to dedicated cloud servers improved application responsiveness.", "로컬 데이터베이스를 전용 클라우드 서버로 이전한 후 애플리케이션 반응 속도가 개선되었습니다."),
        ("configuration", "환경 설정, 구성, 배치", "noun", "system configuration / network configuration", "setup / arrangement / layout",
         "Review the network configuration manual before installing the high-speed optical switch.", "초고속 광 스위치를 설치하기 전에 네트워크 환경 설정 설명서를 검토하십시오."),
        ("bandwidth", "대역폭, 처리 용량", "noun", "broadband bandwidth / allocate bandwidth", "data capacity / transmission rate",
         "High-definition video teleconferencing requires substantial broadband network bandwidth.", "고화질 화상 회의를 원활히 진행하려면 상당한 광대역 네트워크 대역폭이 필요합니다."),
        ("cybersecurity", "사이버 보안", "noun", "cybersecurity protocols / cybersecurity firm", "digital safety / data protection",
         "Investing in top-tier cybersecurity protects proprietary intellectual property from leaks.", "최고 수준의 사이버 보안에 투자하면 독점적인 지적 재산을 외부 유출로부터 보호할 수 있습니다."),
        ("breach", "침해, 침입, 누출; 뚫다", "noun", "data breach / security breach", "leak / infiltration / violation",
         "The tech corporation suffered an embarrassing data breach compromising user credentials.", "그 IT 기업은 사용자 로그인 정보가 유출되는 뼈아픈 데이터 보안 침해 사고를 겪었습니다."),
        ("phishing", "피싱 (사기 메일)", "noun", "phishing attack / phishing simulation", "email scam / fraudulent link",
         "Staff members undergo regular simulation drills to identify deceptive phishing emails.", "직원들은 속임수 피싱 이메일을 식별하기 위해 정기적인 모의 훈련을 받습니다."),
        ("malware", "악성 소프트웨어", "noun", "malware infection / scan for malware", "virus / spyware / malicious software",
         "Antivirus software actively blocks incoming attachments suspected of harboring malware.", "백신 소프트웨어는 악성코드를 포함하고 있을 것으로 의심되는 수신 첨부파일을 능동적으로 차단합니다."),
        ("cloud", "클라우드", "noun", "cloud storage / cloud-based services", "virtual server / distributed network",
         "Moving storage to the enterprise cloud allows remote teams to collaborate seamlessly.", "기업용 클라우드로 저장소를 이전하여 원격 근무 팀들이 원활하게 협업할 수 있습니다."),
        ("interface", "인터페이스, 접속 장치; 접속하다", "noun", "user interface / intuitive interface", "UI / connection point / display",
         "The mobile application features an intuitive user interface that reduces training time.", "그 모바일 애플리케이션은 직관적인 사용자 인터페이스를 갖추고 있어 교육 시간을 단축해 줍니다."),
        ("algorithm", "알고리즘, 연산 규칙", "noun", "recommendation algorithm / search algorithm", "procedure / computational routine",
         "Our proprietary logistics routing algorithm reduced delivery vehicle fuel usage by 8%.", "당사의 독점 물류 경로 최적화 알고리즘은 배송 차량의 연료 사용량을 8% 줄였습니다."),
        ("automation", "자동화", "noun", "office automation / industrial automation", "computerization / robotic process",
         "Implementing office workflow automation liberated staff from repetitive data entry.", "사무 워크플로 자동화를 도입하여 직원들을 반복적인 데이터 입력 업무에서 해방시켰습니다."),
        ("infrastructure", "인프라, 기간 시설", "noun", "IT infrastructure / critical infrastructure", "framework / backbone / foundation",
         "Upgrading the municipal fiber optic infrastructure attracted technology startups to the city.", "도시 광섬유 기간망 인프라를 확충하여 많은 기술 스타트업들을 유치할 수 있었습니다."),
        ("migration", "이전, 이주", "noun", "cloud migration / database migration", "relocation / transfer / shift",
         "The weekend database migration went smoothly with zero reported data loss.", "주말 동안 진행된 데이터베이스 클라우드 이전 작업은 단 한 건의 데이터 유실 없이 순조롭게 마무리되었습니다."),
        ("upgrade", "업그레이드하다; 개선, 향상", "verb", "upgrade software / system upgrade", "improve / enhance / update",
         "Network engineers will upgrade the core router firmware at midnight to patch flaws.", "네트워크 엔지니어들은 보안 취약점을 패치하기 위해 자정에 핵심 라우터 펌웨어를 업그레이드할 것입니다."),
        ("seamless", "이음매 없는, 매끄러운, 중단 없는", "adj", "seamless integration / seamless transition", "smooth / uninterrupted / flawless",
         "The software ensures a seamless transition between mobile and desktop workstations.", "그 소프트웨어는 모바일과 데스크톱 작업 환경 간의 매끄럽고 중단 없는 전환을 보장합니다."),
        ("vulnerability", "취약점, 약점", "noun", "security vulnerability / patch a vulnerability", "flaw / loophole / weakness",
         "The cybersecurity team patched a critical zero-day vulnerability before hackers noticed.", "사이버 보안팀은 해커들이 인지하기 전에 중대한 제로데이 보안 취약점을 신속히 패치했습니다.")
    ])
}

print("Part 1 loaded successfully (Days 1 to 10)")
